#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class BatchGetDCVSessionsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, response=None, next_token=None):  # noqa: E501
        """BatchGetDCVSessionsResponseContent - a model defined in OpenAPI

        :param response: The response of this BatchGetDCVSessionsResponseContent.  # noqa: E501
        :type response: object
        :param next_token: The next_token of this BatchGetDCVSessionsResponseContent.  # noqa: E501
        :type next_token: str
        """
        self.openapi_types = {
            'response': object,
            'next_token': str
        }

        self.attribute_map = {
            'response': 'response',
            'next_token': 'nextToken'
        }

        self._response = response
        self._next_token = next_token

    @classmethod
    def from_dict(cls, dikt) -> 'BatchGetDCVSessionsResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchGetDCVSessionsResponseContent of this BatchGetDCVSessionsResponseContent.  # noqa: E501
        :rtype: BatchGetDCVSessionsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def response(self) -> object:
        """Gets the response of this BatchGetDCVSessionsResponseContent.

        DCV sessions response data  # noqa: E501

        :return: The response of this BatchGetDCVSessionsResponseContent.
        :rtype: object
        """
        return self._response

    @response.setter
    def response(self, response: object):
        """Sets the response of this BatchGetDCVSessionsResponseContent.

        DCV sessions response data  # noqa: E501

        :param response: The response of this BatchGetDCVSessionsResponseContent.
        :type response: object
        """

        self._response = response

    @property
    def next_token(self) -> str:
        """Gets the next_token of this BatchGetDCVSessionsResponseContent.

        Pagination token for next page  # noqa: E501

        :return: The next_token of this BatchGetDCVSessionsResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token: str):
        """Sets the next_token of this BatchGetDCVSessionsResponseContent.

        Pagination token for next page  # noqa: E501

        :param next_token: The next_token of this BatchGetDCVSessionsResponseContent.
        :type next_token: str
        """

        self._next_token = next_token
