#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class DeletePermissionProfileResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None):  # noqa: E501
        """DeletePermissionProfileResponseContent - a model defined in OpenAPI

        :param success: The success of this DeletePermissionProfileResponseContent.  # noqa: E501
        :type success: bool
        """
        self.openapi_types = {
            'success': bool
        }

        self.attribute_map = {
            'success': 'success'
        }

        self._success = success

    @classmethod
    def from_dict(cls, dikt) -> 'DeletePermissionProfileResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeletePermissionProfileResponseContent of this DeletePermissionProfileResponseContent.  # noqa: E501
        :rtype: DeletePermissionProfileResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this DeletePermissionProfileResponseContent.


        :return: The success of this DeletePermissionProfileResponseContent.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this DeletePermissionProfileResponseContent.


        :param success: The success of this DeletePermissionProfileResponseContent.
        :type success: bool
        """
        if success is None:
            raise ValueError("Invalid value for `success`, must not be `None`")  # noqa: E501

        self._success = success
