#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class DeleteSoftwareStackRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, base_os=None):  # noqa: E501
        """DeleteSoftwareStackRequestContent - a model defined in OpenAPI

        :param base_os: The base_os of this DeleteSoftwareStackRequestContent.  # noqa: E501
        :type base_os: str
        """
        self.openapi_types = {
            'base_os': str
        }

        self.attribute_map = {
            'base_os': 'base_os'
        }

        self._base_os = base_os

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteSoftwareStackRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteSoftwareStackRequestContent of this DeleteSoftwareStackRequestContent.  # noqa: E501
        :rtype: DeleteSoftwareStackRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def base_os(self) -> str:
        """Gets the base_os of this DeleteSoftwareStackRequestContent.


        :return: The base_os of this DeleteSoftwareStackRequestContent.
        :rtype: str
        """
        return self._base_os

    @base_os.setter
    def base_os(self, base_os: str):
        """Sets the base_os of this DeleteSoftwareStackRequestContent.


        :param base_os: The base_os of this DeleteSoftwareStackRequestContent.
        :type base_os: str
        """
        if base_os is None:
            raise ValueError("Invalid value for `base_os`, must not be `None`")  # noqa: E501
        if base_os is not None and len(base_os) < 1:
            raise ValueError("Invalid value for `base_os`, length must be greater than or equal to `1`")  # noqa: E501

        self._base_os = base_os
