#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class InternalServiceExceptionResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """InternalServiceExceptionResponseContent - a model defined in OpenAPI

        :param message: The message of this InternalServiceExceptionResponseContent.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InternalServiceExceptionResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InternalServiceExceptionResponseContent of this InternalServiceExceptionResponseContent.  # noqa: E501
        :rtype: InternalServiceExceptionResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this InternalServiceExceptionResponseContent.


        :return: The message of this InternalServiceExceptionResponseContent.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InternalServiceExceptionResponseContent.


        :param message: The message of this InternalServiceExceptionResponseContent.
        :type message: str
        """

        self._message = message
