#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.res_date_range_serializer import resdaterange_serializer


class ResDateRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, key=None, start=None, end=None):  # noqa: E501
        """ResDateRange - a model defined in OpenAPI

        :param key: The key of this ResDateRange.  # noqa: E501
        :type key: str
        :param start: The start of this ResDateRange.  # noqa: E501
        :type start: float
        :param end: The end of this ResDateRange.  # noqa: E501
        :type end: float
        """
        self.openapi_types = {
            'key': str,
            'start': float,
            'end': float
        }

        self.attribute_map = {
            'key': 'key',
            'start': 'start',
            'end': 'end'
        }

        self._key = key
        self._start = start
        self._end = end

    def to_ddb_dict(self):
        """
        Convert this ResDateRange instance to DynamoDB dictionary format.
        
        Uses the ResDateRangeSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return resdaterange_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create ResDateRange instance from DynamoDB dictionary.
        
        Uses the ResDateRangeSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            ResDateRange instance
        """
        api_data = resdaterange_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'ResDateRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResDateRange of this ResDateRange.  # noqa: E501
        :rtype: ResDateRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this ResDateRange.

        The key identifier for the date range  # noqa: E501

        :return: The key of this ResDateRange.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this ResDateRange.

        The key identifier for the date range  # noqa: E501

        :param key: The key of this ResDateRange.
        :type key: str
        """

        self._key = key

    @property
    def start(self) -> float:
        """Gets the start of this ResDateRange.

        Start date/time for the range  # noqa: E501

        :return: The start of this ResDateRange.
        :rtype: float
        """
        return self._start

    @start.setter
    def start(self, start: float):
        """Sets the start of this ResDateRange.

        Start date/time for the range  # noqa: E501

        :param start: The start of this ResDateRange.
        :type start: float
        """

        self._start = start

    @property
    def end(self) -> float:
        """Gets the end of this ResDateRange.

        End date/time for the range  # noqa: E501

        :return: The end of this ResDateRange.
        :rtype: float
        """
        return self._end

    @end.setter
    def end(self, end: float):
        """Sets the end of this ResDateRange.

        End date/time for the range  # noqa: E501

        :param end: The end of this ResDateRange.
        :type end: float
        """

        self._end = end
