#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.res_memory_serializer import resmemory_serializer


class ResMemory(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, unit=None):  # noqa: E501
        """ResMemory - a model defined in OpenAPI

        :param value: The value of this ResMemory.  # noqa: E501
        :type value: float
        :param unit: The unit of this ResMemory.  # noqa: E501
        :type unit: str
        """
        self.openapi_types = {
            'value': float,
            'unit': str
        }

        self.attribute_map = {
            'value': 'value',
            'unit': 'unit'
        }

        self._value = value
        self._unit = unit

    def to_ddb_dict(self):
        """
        Convert this ResMemory instance to DynamoDB dictionary format.
        
        Uses the ResMemorySerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return resmemory_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create ResMemory instance from DynamoDB dictionary.
        
        Uses the ResMemorySerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            ResMemory instance
        """
        api_data = resmemory_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'ResMemory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResMemory of this ResMemory.  # noqa: E501
        :rtype: ResMemory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> float:
        """Gets the value of this ResMemory.

        Memory value  # noqa: E501

        :return: The value of this ResMemory.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this ResMemory.

        Memory value  # noqa: E501

        :param value: The value of this ResMemory.
        :type value: float
        """

        self._value = value

    @property
    def unit(self) -> str:
        """Gets the unit of this ResMemory.

        Memory unit (e.g., GB, MB)  # noqa: E501

        :return: The unit of this ResMemory.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this ResMemory.

        Memory unit (e.g., GB, MB)  # noqa: E501

        :param unit: The unit of this ResMemory.
        :type unit: str
        """

        self._unit = unit
