#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_permission_profile import VirtualDesktopPermissionProfile
from datamodel import util

from datamodel.models.virtual_desktop_permission_profile import VirtualDesktopPermissionProfile  # noqa: E501

class UpdatePermissionProfileResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, profile=None):  # noqa: E501
        """UpdatePermissionProfileResponseContent - a model defined in OpenAPI

        :param profile: The profile of this UpdatePermissionProfileResponseContent.  # noqa: E501
        :type profile: VirtualDesktopPermissionProfile
        """
        self.openapi_types = {
            'profile': VirtualDesktopPermissionProfile
        }

        self.attribute_map = {
            'profile': 'profile'
        }

        self._profile = profile

    @classmethod
    def from_dict(cls, dikt) -> 'UpdatePermissionProfileResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdatePermissionProfileResponseContent of this UpdatePermissionProfileResponseContent.  # noqa: E501
        :rtype: UpdatePermissionProfileResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def profile(self) -> VirtualDesktopPermissionProfile:
        """Gets the profile of this UpdatePermissionProfileResponseContent.


        :return: The profile of this UpdatePermissionProfileResponseContent.
        :rtype: VirtualDesktopPermissionProfile
        """
        return self._profile

    @profile.setter
    def profile(self, profile: VirtualDesktopPermissionProfile):
        """Sets the profile of this UpdatePermissionProfileResponseContent.


        :param profile: The profile of this UpdatePermissionProfileResponseContent.
        :type profile: VirtualDesktopPermissionProfile
        """
        if profile is None:
            raise ValueError("Invalid value for `profile`, must not be `None`")  # noqa: E501

        self._profile = profile
