#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack
from datamodel import util

from datamodel.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack  # noqa: E501

class UpdateSoftwareStackRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, software_stack=None):  # noqa: E501
        """UpdateSoftwareStackRequestContent - a model defined in OpenAPI

        :param software_stack: The software_stack of this UpdateSoftwareStackRequestContent.  # noqa: E501
        :type software_stack: VirtualDesktopSoftwareStack
        """
        self.openapi_types = {
            'software_stack': VirtualDesktopSoftwareStack
        }

        self.attribute_map = {
            'software_stack': 'software_stack'
        }

        self._software_stack = software_stack

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateSoftwareStackRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateSoftwareStackRequestContent of this UpdateSoftwareStackRequestContent.  # noqa: E501
        :rtype: UpdateSoftwareStackRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def software_stack(self) -> VirtualDesktopSoftwareStack:
        """Gets the software_stack of this UpdateSoftwareStackRequestContent.


        :return: The software_stack of this UpdateSoftwareStackRequestContent.
        :rtype: VirtualDesktopSoftwareStack
        """
        return self._software_stack

    @software_stack.setter
    def software_stack(self, software_stack: VirtualDesktopSoftwareStack):
        """Sets the software_stack of this UpdateSoftwareStackRequestContent.


        :param software_stack: The software_stack of this UpdateSoftwareStackRequestContent.
        :type software_stack: VirtualDesktopSoftwareStack
        """
        if software_stack is None:
            raise ValueError("Invalid value for `software_stack`, must not be `None`")  # noqa: E501

        self._software_stack = software_stack
