#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.virtual_desktop_permission_serializer import virtualdesktoppermission_serializer


class VirtualDesktopPermission(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, key=None, name=None, description=None, enabled=None):  # noqa: E501
        """VirtualDesktopPermission - a model defined in OpenAPI

        :param key: The key of this VirtualDesktopPermission.  # noqa: E501
        :type key: str
        :param name: The name of this VirtualDesktopPermission.  # noqa: E501
        :type name: str
        :param description: The description of this VirtualDesktopPermission.  # noqa: E501
        :type description: str
        :param enabled: The enabled of this VirtualDesktopPermission.  # noqa: E501
        :type enabled: bool
        """
        self.openapi_types = {
            'key': str,
            'name': str,
            'description': str,
            'enabled': bool
        }

        self.attribute_map = {
            'key': 'key',
            'name': 'name',
            'description': 'description',
            'enabled': 'enabled'
        }

        self._key = key
        self._name = name
        self._description = description
        self._enabled = enabled

    def to_ddb_dict(self):
        """
        Convert this VirtualDesktopPermission instance to DynamoDB dictionary format.
        
        Uses the VirtualDesktopPermissionSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return virtualdesktoppermission_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create VirtualDesktopPermission instance from DynamoDB dictionary.
        
        Uses the VirtualDesktopPermissionSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            VirtualDesktopPermission instance
        """
        api_data = virtualdesktoppermission_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopPermission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopPermission of this VirtualDesktopPermission.  # noqa: E501
        :rtype: VirtualDesktopPermission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this VirtualDesktopPermission.

        Permission key identifier  # noqa: E501

        :return: The key of this VirtualDesktopPermission.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this VirtualDesktopPermission.

        Permission key identifier  # noqa: E501

        :param key: The key of this VirtualDesktopPermission.
        :type key: str
        """

        self._key = key

    @property
    def name(self) -> str:
        """Gets the name of this VirtualDesktopPermission.

        Permission display name  # noqa: E501

        :return: The name of this VirtualDesktopPermission.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VirtualDesktopPermission.

        Permission display name  # noqa: E501

        :param name: The name of this VirtualDesktopPermission.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this VirtualDesktopPermission.

        Permission description  # noqa: E501

        :return: The description of this VirtualDesktopPermission.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VirtualDesktopPermission.

        Permission description  # noqa: E501

        :param description: The description of this VirtualDesktopPermission.
        :type description: str
        """

        self._description = description

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this VirtualDesktopPermission.

        Whether the permission is enabled  # noqa: E501

        :return: The enabled of this VirtualDesktopPermission.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this VirtualDesktopPermission.

        Whether the permission is enabled  # noqa: E501

        :param enabled: The enabled of this VirtualDesktopPermission.
        :type enabled: bool
        """

        self._enabled = enabled
