#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.project import Project
from datamodel.models.res_memory import ResMemory
from datamodel.models.virtual_desktop_architecture import VirtualDesktopArchitecture
from datamodel.models.virtual_desktop_base_os import VirtualDesktopBaseOs
from datamodel.models.virtual_desktop_gpu import VirtualDesktopGpu
from datamodel.models.virtual_desktop_placement import VirtualDesktopPlacement
from datamodel import util
from datamodel.serializers.virtual_desktop_software_stack_serializer import virtualdesktopsoftwarestack_serializer

from datamodel.models.project import Project  # noqa: E501
from datamodel.models.res_memory import ResMemory  # noqa: E501
from datamodel.models.virtual_desktop_architecture import VirtualDesktopArchitecture  # noqa: E501
from datamodel.models.virtual_desktop_base_os import VirtualDesktopBaseOs  # noqa: E501
from datamodel.models.virtual_desktop_gpu import VirtualDesktopGpu  # noqa: E501
from datamodel.models.virtual_desktop_placement import VirtualDesktopPlacement  # noqa: E501

class VirtualDesktopSoftwareStack(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, stack_id=None, base_os=None, name=None, description=None, created_on=None, updated_on=None, ami_id=None, failure_reason=None, enabled=None, min_storage=None, min_ram=None, architecture=None, gpu=None, placement=None, version=None, projects=None, allowed_instance_types=None):  # noqa: E501
        """VirtualDesktopSoftwareStack - a model defined in OpenAPI

        :param stack_id: The stack_id of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type stack_id: str
        :param base_os: The base_os of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type base_os: VirtualDesktopBaseOs
        :param name: The name of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type name: str
        :param description: The description of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type description: str
        :param created_on: The created_on of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type created_on: str
        :param updated_on: The updated_on of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type updated_on: str
        :param ami_id: The ami_id of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type ami_id: str
        :param failure_reason: The failure_reason of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type failure_reason: str
        :param enabled: The enabled of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type enabled: bool
        :param min_storage: The min_storage of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type min_storage: ResMemory
        :param min_ram: The min_ram of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type min_ram: ResMemory
        :param architecture: The architecture of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type architecture: VirtualDesktopArchitecture
        :param gpu: The gpu of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type gpu: VirtualDesktopGpu
        :param placement: The placement of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type placement: VirtualDesktopPlacement
        :param version: The version of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type version: int
        :param projects: The projects of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type projects: List[Project]
        :param allowed_instance_types: The allowed_instance_types of this VirtualDesktopSoftwareStack.  # noqa: E501
        :type allowed_instance_types: List[str]
        """
        self.openapi_types = {
            'stack_id': str,
            'base_os': VirtualDesktopBaseOs,
            'name': str,
            'description': str,
            'created_on': str,
            'updated_on': str,
            'ami_id': str,
            'failure_reason': str,
            'enabled': bool,
            'min_storage': ResMemory,
            'min_ram': ResMemory,
            'architecture': VirtualDesktopArchitecture,
            'gpu': VirtualDesktopGpu,
            'placement': VirtualDesktopPlacement,
            'version': int,
            'projects': List[Project],
            'allowed_instance_types': List[str]
        }

        self.attribute_map = {
            'stack_id': 'stack_id',
            'base_os': 'base_os',
            'name': 'name',
            'description': 'description',
            'created_on': 'created_on',
            'updated_on': 'updated_on',
            'ami_id': 'ami_id',
            'failure_reason': 'failure_reason',
            'enabled': 'enabled',
            'min_storage': 'min_storage',
            'min_ram': 'min_ram',
            'architecture': 'architecture',
            'gpu': 'gpu',
            'placement': 'placement',
            'version': 'version',
            'projects': 'projects',
            'allowed_instance_types': 'allowed_instance_types'
        }

        self._stack_id = stack_id
        self._base_os = base_os
        self._name = name
        self._description = description
        self._created_on = created_on
        self._updated_on = updated_on
        self._ami_id = ami_id
        self._failure_reason = failure_reason
        self._enabled = enabled
        self._min_storage = min_storage
        self._min_ram = min_ram
        self._architecture = architecture
        self._gpu = gpu
        self._placement = placement
        self._version = version
        self._projects = projects
        self._allowed_instance_types = allowed_instance_types

    def to_ddb_dict(self):
        """
        Convert this VirtualDesktopSoftwareStack instance to DynamoDB dictionary format.
        
        Uses the VirtualDesktopSoftwareStackSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return virtualdesktopsoftwarestack_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create VirtualDesktopSoftwareStack instance from DynamoDB dictionary.
        
        Uses the VirtualDesktopSoftwareStackSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            VirtualDesktopSoftwareStack instance
        """
        api_data = virtualdesktopsoftwarestack_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopSoftwareStack':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopSoftwareStack of this VirtualDesktopSoftwareStack.  # noqa: E501
        :rtype: VirtualDesktopSoftwareStack
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stack_id(self) -> str:
        """Gets the stack_id of this VirtualDesktopSoftwareStack.

        Unique identifier for the software stack  # noqa: E501

        :return: The stack_id of this VirtualDesktopSoftwareStack.
        :rtype: str
        """
        return self._stack_id

    @stack_id.setter
    def stack_id(self, stack_id: str):
        """Sets the stack_id of this VirtualDesktopSoftwareStack.

        Unique identifier for the software stack  # noqa: E501

        :param stack_id: The stack_id of this VirtualDesktopSoftwareStack.
        :type stack_id: str
        """

        self._stack_id = stack_id

    @property
    def base_os(self) -> VirtualDesktopBaseOs:
        """Gets the base_os of this VirtualDesktopSoftwareStack.


        :return: The base_os of this VirtualDesktopSoftwareStack.
        :rtype: VirtualDesktopBaseOs
        """
        return self._base_os

    @base_os.setter
    def base_os(self, base_os: VirtualDesktopBaseOs):
        """Sets the base_os of this VirtualDesktopSoftwareStack.


        :param base_os: The base_os of this VirtualDesktopSoftwareStack.
        :type base_os: VirtualDesktopBaseOs
        """
        if base_os is None:
            raise ValueError("Invalid value for `base_os`, must not be `None`")  # noqa: E501

        self._base_os = base_os

    @property
    def name(self) -> str:
        """Gets the name of this VirtualDesktopSoftwareStack.

        Human-readable name for the software stack  # noqa: E501

        :return: The name of this VirtualDesktopSoftwareStack.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VirtualDesktopSoftwareStack.

        Human-readable name for the software stack  # noqa: E501

        :param name: The name of this VirtualDesktopSoftwareStack.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this VirtualDesktopSoftwareStack.

        Description of the software stack  # noqa: E501

        :return: The description of this VirtualDesktopSoftwareStack.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VirtualDesktopSoftwareStack.

        Description of the software stack  # noqa: E501

        :param description: The description of this VirtualDesktopSoftwareStack.
        :type description: str
        """

        self._description = description

    @property
    def created_on(self) -> str:
        """Gets the created_on of this VirtualDesktopSoftwareStack.

        Timestamp when the stack was created  # noqa: E501

        :return: The created_on of this VirtualDesktopSoftwareStack.
        :rtype: str
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on: str):
        """Sets the created_on of this VirtualDesktopSoftwareStack.

        Timestamp when the stack was created  # noqa: E501

        :param created_on: The created_on of this VirtualDesktopSoftwareStack.
        :type created_on: str
        """

        self._created_on = created_on

    @property
    def updated_on(self) -> str:
        """Gets the updated_on of this VirtualDesktopSoftwareStack.

        Timestamp when the stack was last updated  # noqa: E501

        :return: The updated_on of this VirtualDesktopSoftwareStack.
        :rtype: str
        """
        return self._updated_on

    @updated_on.setter
    def updated_on(self, updated_on: str):
        """Sets the updated_on of this VirtualDesktopSoftwareStack.

        Timestamp when the stack was last updated  # noqa: E501

        :param updated_on: The updated_on of this VirtualDesktopSoftwareStack.
        :type updated_on: str
        """

        self._updated_on = updated_on

    @property
    def ami_id(self) -> str:
        """Gets the ami_id of this VirtualDesktopSoftwareStack.

        Amazon Machine Image (AMI) ID  # noqa: E501

        :return: The ami_id of this VirtualDesktopSoftwareStack.
        :rtype: str
        """
        return self._ami_id

    @ami_id.setter
    def ami_id(self, ami_id: str):
        """Sets the ami_id of this VirtualDesktopSoftwareStack.

        Amazon Machine Image (AMI) ID  # noqa: E501

        :param ami_id: The ami_id of this VirtualDesktopSoftwareStack.
        :type ami_id: str
        """
        if ami_id is None:
            raise ValueError("Invalid value for `ami_id`, must not be `None`")  # noqa: E501

        self._ami_id = ami_id

    @property
    def failure_reason(self) -> str:
        """Gets the failure_reason of this VirtualDesktopSoftwareStack.

        Reason for any failure in stack creation or update  # noqa: E501

        :return: The failure_reason of this VirtualDesktopSoftwareStack.
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason: str):
        """Sets the failure_reason of this VirtualDesktopSoftwareStack.

        Reason for any failure in stack creation or update  # noqa: E501

        :param failure_reason: The failure_reason of this VirtualDesktopSoftwareStack.
        :type failure_reason: str
        """

        self._failure_reason = failure_reason

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this VirtualDesktopSoftwareStack.

        Whether the software stack is enabled  # noqa: E501

        :return: The enabled of this VirtualDesktopSoftwareStack.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this VirtualDesktopSoftwareStack.

        Whether the software stack is enabled  # noqa: E501

        :param enabled: The enabled of this VirtualDesktopSoftwareStack.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def min_storage(self) -> ResMemory:
        """Gets the min_storage of this VirtualDesktopSoftwareStack.


        :return: The min_storage of this VirtualDesktopSoftwareStack.
        :rtype: ResMemory
        """
        return self._min_storage

    @min_storage.setter
    def min_storage(self, min_storage: ResMemory):
        """Sets the min_storage of this VirtualDesktopSoftwareStack.


        :param min_storage: The min_storage of this VirtualDesktopSoftwareStack.
        :type min_storage: ResMemory
        """
        if min_storage is None:
            raise ValueError("Invalid value for `min_storage`, must not be `None`")  # noqa: E501

        self._min_storage = min_storage

    @property
    def min_ram(self) -> ResMemory:
        """Gets the min_ram of this VirtualDesktopSoftwareStack.


        :return: The min_ram of this VirtualDesktopSoftwareStack.
        :rtype: ResMemory
        """
        return self._min_ram

    @min_ram.setter
    def min_ram(self, min_ram: ResMemory):
        """Sets the min_ram of this VirtualDesktopSoftwareStack.


        :param min_ram: The min_ram of this VirtualDesktopSoftwareStack.
        :type min_ram: ResMemory
        """
        if min_ram is None:
            raise ValueError("Invalid value for `min_ram`, must not be `None`")  # noqa: E501

        self._min_ram = min_ram

    @property
    def architecture(self) -> VirtualDesktopArchitecture:
        """Gets the architecture of this VirtualDesktopSoftwareStack.


        :return: The architecture of this VirtualDesktopSoftwareStack.
        :rtype: VirtualDesktopArchitecture
        """
        return self._architecture

    @architecture.setter
    def architecture(self, architecture: VirtualDesktopArchitecture):
        """Sets the architecture of this VirtualDesktopSoftwareStack.


        :param architecture: The architecture of this VirtualDesktopSoftwareStack.
        :type architecture: VirtualDesktopArchitecture
        """

        self._architecture = architecture

    @property
    def gpu(self) -> VirtualDesktopGpu:
        """Gets the gpu of this VirtualDesktopSoftwareStack.


        :return: The gpu of this VirtualDesktopSoftwareStack.
        :rtype: VirtualDesktopGpu
        """
        return self._gpu

    @gpu.setter
    def gpu(self, gpu: VirtualDesktopGpu):
        """Sets the gpu of this VirtualDesktopSoftwareStack.


        :param gpu: The gpu of this VirtualDesktopSoftwareStack.
        :type gpu: VirtualDesktopGpu
        """
        if gpu is None:
            raise ValueError("Invalid value for `gpu`, must not be `None`")  # noqa: E501

        self._gpu = gpu

    @property
    def placement(self) -> VirtualDesktopPlacement:
        """Gets the placement of this VirtualDesktopSoftwareStack.


        :return: The placement of this VirtualDesktopSoftwareStack.
        :rtype: VirtualDesktopPlacement
        """
        return self._placement

    @placement.setter
    def placement(self, placement: VirtualDesktopPlacement):
        """Sets the placement of this VirtualDesktopSoftwareStack.


        :param placement: The placement of this VirtualDesktopSoftwareStack.
        :type placement: VirtualDesktopPlacement
        """

        self._placement = placement

    @property
    def version(self) -> int:
        """Gets the version of this VirtualDesktopSoftwareStack.

        Version number of the software stack  # noqa: E501

        :return: The version of this VirtualDesktopSoftwareStack.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version: int):
        """Sets the version of this VirtualDesktopSoftwareStack.

        Version number of the software stack  # noqa: E501

        :param version: The version of this VirtualDesktopSoftwareStack.
        :type version: int
        """

        self._version = version

    @property
    def projects(self) -> List[Project]:
        """Gets the projects of this VirtualDesktopSoftwareStack.

        List of projects associated with this software stack  # noqa: E501

        :return: The projects of this VirtualDesktopSoftwareStack.
        :rtype: List[Project]
        """
        return self._projects

    @projects.setter
    def projects(self, projects: List[Project]):
        """Sets the projects of this VirtualDesktopSoftwareStack.

        List of projects associated with this software stack  # noqa: E501

        :param projects: The projects of this VirtualDesktopSoftwareStack.
        :type projects: List[Project]
        """

        self._projects = projects

    @property
    def allowed_instance_types(self) -> List[str]:
        """Gets the allowed_instance_types of this VirtualDesktopSoftwareStack.

        List of allowed EC2 instance types  # noqa: E501

        :return: The allowed_instance_types of this VirtualDesktopSoftwareStack.
        :rtype: List[str]
        """
        return self._allowed_instance_types

    @allowed_instance_types.setter
    def allowed_instance_types(self, allowed_instance_types: List[str]):
        """Sets the allowed_instance_types of this VirtualDesktopSoftwareStack.

        List of allowed EC2 instance types  # noqa: E501

        :param allowed_instance_types: The allowed_instance_types of this VirtualDesktopSoftwareStack.
        :type allowed_instance_types: List[str]
        """

        self._allowed_instance_types = allowed_instance_types
