#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_affinity import VirtualDesktopAffinity
from datamodel.models.virtual_desktop_tenancy import VirtualDesktopTenancy
from datamodel import util
from datamodel.serializers.virtual_desktop_placement_serializer import virtualdesktopplacement_serializer

from datamodel.models.virtual_desktop_affinity import VirtualDesktopAffinity  # noqa: E501
from datamodel.models.virtual_desktop_tenancy import VirtualDesktopTenancy  # noqa: E501

class VirtualDesktopPlacement(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, affinity=None, tenancy=None, host_id=None, host_resource_group_arn=None):  # noqa: E501
        """VirtualDesktopPlacement - a model defined in OpenAPI

        :param affinity: The affinity of this VirtualDesktopPlacement.  # noqa: E501
        :type affinity: VirtualDesktopAffinity
        :param tenancy: The tenancy of this VirtualDesktopPlacement.  # noqa: E501
        :type tenancy: VirtualDesktopTenancy
        :param host_id: The host_id of this VirtualDesktopPlacement.  # noqa: E501
        :type host_id: str
        :param host_resource_group_arn: The host_resource_group_arn of this VirtualDesktopPlacement.  # noqa: E501
        :type host_resource_group_arn: str
        """
        self.openapi_types = {
            'affinity': VirtualDesktopAffinity,
            'tenancy': VirtualDesktopTenancy,
            'host_id': str,
            'host_resource_group_arn': str
        }

        self.attribute_map = {
            'affinity': 'affinity',
            'tenancy': 'tenancy',
            'host_id': 'host_id',
            'host_resource_group_arn': 'host_resource_group_arn'
        }

        self._affinity = affinity
        self._tenancy = tenancy
        self._host_id = host_id
        self._host_resource_group_arn = host_resource_group_arn

    def to_ddb_dict(self):
        """
        Convert this VirtualDesktopPlacement instance to DynamoDB dictionary format.
        
        Uses the VirtualDesktopPlacementSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return virtualdesktopplacement_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create VirtualDesktopPlacement instance from DynamoDB dictionary.
        
        Uses the VirtualDesktopPlacementSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            VirtualDesktopPlacement instance
        """
        api_data = virtualdesktopplacement_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopPlacement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopPlacement of this VirtualDesktopPlacement.  # noqa: E501
        :rtype: VirtualDesktopPlacement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def affinity(self) -> VirtualDesktopAffinity:
        """Gets the affinity of this VirtualDesktopPlacement.


        :return: The affinity of this VirtualDesktopPlacement.
        :rtype: VirtualDesktopAffinity
        """
        return self._affinity

    @affinity.setter
    def affinity(self, affinity: VirtualDesktopAffinity):
        """Sets the affinity of this VirtualDesktopPlacement.


        :param affinity: The affinity of this VirtualDesktopPlacement.
        :type affinity: VirtualDesktopAffinity
        """

        self._affinity = affinity

    @property
    def tenancy(self) -> VirtualDesktopTenancy:
        """Gets the tenancy of this VirtualDesktopPlacement.


        :return: The tenancy of this VirtualDesktopPlacement.
        :rtype: VirtualDesktopTenancy
        """
        return self._tenancy

    @tenancy.setter
    def tenancy(self, tenancy: VirtualDesktopTenancy):
        """Sets the tenancy of this VirtualDesktopPlacement.


        :param tenancy: The tenancy of this VirtualDesktopPlacement.
        :type tenancy: VirtualDesktopTenancy
        """

        self._tenancy = tenancy

    @property
    def host_id(self) -> str:
        """Gets the host_id of this VirtualDesktopPlacement.

        Dedicated host ID  # noqa: E501

        :return: The host_id of this VirtualDesktopPlacement.
        :rtype: str
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id: str):
        """Sets the host_id of this VirtualDesktopPlacement.

        Dedicated host ID  # noqa: E501

        :param host_id: The host_id of this VirtualDesktopPlacement.
        :type host_id: str
        """

        self._host_id = host_id

    @property
    def host_resource_group_arn(self) -> str:
        """Gets the host_resource_group_arn of this VirtualDesktopPlacement.

        Host resource group ARN  # noqa: E501

        :return: The host_resource_group_arn of this VirtualDesktopPlacement.
        :rtype: str
        """
        return self._host_resource_group_arn

    @host_resource_group_arn.setter
    def host_resource_group_arn(self, host_resource_group_arn: str):
        """Sets the host_resource_group_arn of this VirtualDesktopPlacement.

        Host resource group ARN  # noqa: E501

        :param host_resource_group_arn: The host_resource_group_arn of this VirtualDesktopPlacement.
        :type host_resource_group_arn: str
        """

        self._host_resource_group_arn = host_resource_group_arn
