af-south-1: Africa/Johannesburg
ap-east-1: Asia/Hong_Kong
ap-northeast-1: Asia/Tokyo
ap-northeast-2: Asia/Seoul
ap-south-1: Asia/Kolkata
ap-southeast-1: Asia/Singapore
ap-southeast-2: Australia/Sydney
ap-southeast-3: Asia/Jakarta
ca-central-1: America/Regina
il-central-1: Israel
eu-central-1: Europe/Berlin
eu-north-1: Europe/Stockholm
eu-south-1: Europe/Rome
eu-west-1: Europe/Dublin
eu-west-2: Europe/London
eu-west-3: Europe/Paris
me-south-1: Asia/Bahrain
sa-east-1: America/Sao_Paulo
us-east-1: America/New_York
us-east-2: America/New_York
us-west-1: America/Los_Angeles
us-west-2: America/Los_Angeles
us-gov-west-1: America/Los_Angeles
us-gov-east-1: America/New_York
default: America/Los_Angeles
