Version: '2012-10-17'
Statement:
  - Action:
      - logs:CreateLogGroup
    Resource: "{{ context.arns.get_lambda_log_group_arn() }}"
    Effect: Allow
    Sid: CloudWatchLogsPermissions
  - Action:
      - logs:CreateLogStream
      - logs:PutLogEvents
      - logs:DeleteLogStream
    Resource: "{{ context.arns.lambda_log_stream_arn }}"
    Effect: Allow
    Sid: CloudWatchLogStreamPermissions
  - Action:
      - cognito-idp:UpdateUserPoolClient
      - cognito-idp:CreateUserPoolClient
      - cognito-idp:GetIdentityProviderByIdentifier
      - cognito-idp:UpdateIdentityProvider
      - cognito-idp:CreateIdentityProvider
      - cognito-idp:DeleteIdentityProvider
    Resource: "{{ context.arns.user_pool_arn }}"
    Effect: Allow
  - Action:
      - dynamodb:GetItem
      - dynamodb:UpdateItem
      - dynamodb:PutItem
      - dynamodb:DescribeTable
    Resource: "{{ context.arns.get_ddb_table_arn("cluster-settings") }}"
    Effect: Allow
  - Action:
      - secretsmanager:DescribeSecret
      - secretsmanager:CreateSecret
      - secretsmanager:UpdateSecret
      - secretsmanager:TagResource
    Resource: {{ context.arns.get_arn("secretsmanager", "secret:" + context.cluster_name + "-sso-client-secret*") }}
    Effect: Allow