Version: '2012-10-17'
Statement:
  - Action:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:DeleteLogStream
      - logs:PutLogEvents
    Resource: {{ context.arns.get_lambda_log_group_arn() }}
    Effect: Allow
    Sid: CloudWatchLogsPermissions

  - Action:
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      {{ context.utils.to_yaml(context.arns.cluster_config_ddb_arn) | indent(6) }}
    Effect: Allow

    {%- if context.config.get_string('cluster.dynamodb.kms_key_id') %}
  - Action:
      - kms:GenerateDataKey
      - kms:Decrypt
    Resource:
      - '{{ context.arns.kms_dynamodb_key_arn }}'
    Effect: Allow
    {%- endif %}
