#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from typing import Any

import pytest
from aws_cdk.assertions import Match, Template

from idea.infrastructure.install.parameters.common import CommonKey
from idea.infrastructure.install.stack import InstallStack
from tests.unit.infrastructure.install import util


@pytest.fixture
def assume_role_policy_document() -> dict[str, Any]:
    return {
        "Statement": [
            {
                "Action": "sts:AssumeRole",
                "Condition": {
                    "ArnLike": {
                        "aws:SourceArn": {
                            "Fn::Join": [
                                "",
                                [
                                    "arn:",
                                    {"Ref": "AWS::Partition"},
                                    ":ecs:",
                                    {"Ref": "AWS::Region"},
                                    ":",
                                    {"Ref": "AWS::AccountId"},
                                    ":*",
                                ],
                            ]
                        }
                    },
                    "StringEquals": {"aws:SourceAccount": {"Ref": "AWS::AccountId"}},
                },
                "Effect": "Allow",
                "Principal": {"Service": "ecs-tasks.amazonaws.com"},
            }
        ]
    }


def test_role_creation(
    stack: InstallStack,
    template: Template,
    assume_role_policy_document: dict[str, Any],
) -> None:
    util.assert_resource_name_has_correct_type_and_props(
        stack,
        template,
        resources=["Installer", "Tasks", "Permissions", "PipelineRole"],
        cfn_type="AWS::IAM::Role",
        props={
            "Properties": {
                "AssumeRolePolicyDocument": assume_role_policy_document,
                "RoleName": {
                    "Fn::Join": [
                        "",
                        [
                            "Admin-",
                            {"Ref": CommonKey.CLUSTER_NAME},
                            "-",
                            {"Ref": "AWS::Region"},
                            f"-PipelineRole",
                        ],
                    ]
                },
            },
        },
    )
    util.assert_resource_name_has_correct_type_and_props(
        stack,
        template,
        resources=[
            "Installer",
            "Tasks",
            "Permissions",
            "PipelineRole",
            "DefaultPolicy",
        ],
        cfn_type="AWS::IAM::Policy",
        props={
            "Properties": {
                "Roles": [
                    {
                        "Ref": util.get_logical_id(
                            stack, ["Installer", "Tasks", "Permissions", "PipelineRole"]
                        )
                    }
                ]
            }
        },
    )


def test_permission_boundary_attachment_to_all_roles(
    stack: InstallStack, template: Template
) -> None:
    # All roles must have a permission boundary configured based on whether a customer provides one. This test catches roles without permission boundaries. This catches both human-errors, as well as roles generated by CDK helpers.
    template.all_resources_properties(
        "AWS::IAM::Role",
        {
            "PermissionsBoundary": Match.object_equals(
                {
                    "Fn::If": [
                        "PermissionBoundaryProvided",
                        {"Ref": "IAMPermissionBoundary"},
                        {"Ref": "AWS::NoValue"},
                    ]
                }
            )
        },
    )
