# Identity Provider Settings
#
# Supported identity providers are Amazon Cognito User Pool and Keycloak (Opensource IDP: https://www.keycloak.org/).
#
# Use Cognito User Pools, when your target AWS Region supports Cognito User Pools and you can allow exceptions for VPC Endpoints, as Cognito User Pools do not support VPC Endpoints.
# Use Keycloak, when your target AWS Region does not support Cognito IDP and/or your InfoSec policies do not allow any exceptions for VPC Endpoints.
#
# Note: Support for Keycloak is work in progress.

provider: "{{identity_provider}}"

{%- if identity_provider == 'cognito-idp' %}
cognito:
  administrators_group_name: administrators-cluster-group
  managers_group_name: managers-cluster-group
  removal_policy: "DESTROY" # RETAIN will preserve the user pool even if you delete the stack.
  advanced_security_mode: "AUDIT"  # Allowed values: AUDIT, ENFORCED, OFF - Depending on regional ability. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-userpooladdons.html
  email_provider: "cognito"   # "cognito" or "ses"
  # Options that control Cognito interactions with Amazon Simple Email Service (SES)
  # NOTE: You must configure and verify email addresses prior to IDEA installation.
  # NOTE2: These controls can be the same or independent of the cluster.ses settings which cover
  # emails that are generated by IDEA for specific events.
  # Only used if email_provider is set to "ses"
  #
  ses:
    ses_region: ~
    from_email: ~
    configuration_set: ~
    from_name: ~
    reply_to_address: ~
  # to enable SSO, run ./res-admin.sh sso configure. do not modify this configuration to true to enable SSO.
  sso_enabled: false

{%- endif %}
