# coding: utf-8

"""
    DCV Session Manager

    DCV Session Manager API  # noqa: E501

    OpenAPI spec version: 2021.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetSessionConnectionDataResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session': 'Session',
        'connection_token': 'str'
    }

    attribute_map = {
        'session': 'Session',
        'connection_token': 'ConnectionToken'
    }

    def __init__(self, session=None, connection_token=None):  # noqa: E501
        """GetSessionConnectionDataResponse - a model defined in Swagger"""  # noqa: E501
        self._session = None
        self._connection_token = None
        self.discriminator = None
        if session is not None:
            self.session = session
        if connection_token is not None:
            self.connection_token = connection_token

    @property
    def session(self):
        """Gets the session of this GetSessionConnectionDataResponse.  # noqa: E501


        :return: The session of this GetSessionConnectionDataResponse.  # noqa: E501
        :rtype: Session
        """
        return self._session

    @session.setter
    def session(self, session):
        """Sets the session of this GetSessionConnectionDataResponse.


        :param session: The session of this GetSessionConnectionDataResponse.  # noqa: E501
        :type: Session
        """

        self._session = session

    @property
    def connection_token(self):
        """Gets the connection_token of this GetSessionConnectionDataResponse.  # noqa: E501

        The token used to connect to the session  # noqa: E501

        :return: The connection_token of this GetSessionConnectionDataResponse.  # noqa: E501
        :rtype: str
        """
        return self._connection_token

    @connection_token.setter
    def connection_token(self, connection_token):
        """Sets the connection_token of this GetSessionConnectionDataResponse.

        The token used to connect to the session  # noqa: E501

        :param connection_token: The connection_token of this GetSessionConnectionDataResponse.  # noqa: E501
        :type: str
        """

        self._connection_token = connection_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSessionConnectionDataResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSessionConnectionDataResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
