# coding: utf-8

"""
    DCV Session Manager

    DCV Session Manager API  # noqa: E501

    OpenAPI spec version: 2021.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Gpu(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vendor': 'str',
        'model_name': 'str'
    }

    attribute_map = {
        'vendor': 'Vendor',
        'model_name': 'ModelName'
    }

    def __init__(self, vendor=None, model_name=None):  # noqa: E501
        """Gpu - a model defined in Swagger"""  # noqa: E501
        self._vendor = None
        self._model_name = None
        self.discriminator = None
        if vendor is not None:
            self.vendor = vendor
        if model_name is not None:
            self.model_name = model_name

    @property
    def vendor(self):
        """Gets the vendor of this Gpu.  # noqa: E501

        The vendor of the gpu  # noqa: E501

        :return: The vendor of this Gpu.  # noqa: E501
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this Gpu.

        The vendor of the gpu  # noqa: E501

        :param vendor: The vendor of this Gpu.  # noqa: E501
        :type: str
        """

        self._vendor = vendor

    @property
    def model_name(self):
        """Gets the model_name of this Gpu.  # noqa: E501

        The model name of the gpu  # noqa: E501

        :return: The model_name of this Gpu.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this Gpu.

        The model name of the gpu  # noqa: E501

        :param model_name: The model_name of this Gpu.  # noqa: E501
        :type: str
        """

        self._model_name = model_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Gpu, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Gpu):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
