# coding: utf-8

"""
    DCV Session Manager

    DCV Session Manager API  # noqa: E501

    OpenAPI spec version: 2021.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Memory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_bytes': 'int',
        'used_bytes': 'int'
    }

    attribute_map = {
        'total_bytes': 'TotalBytes',
        'used_bytes': 'UsedBytes'
    }

    def __init__(self, total_bytes=None, used_bytes=None):  # noqa: E501
        """Memory - a model defined in Swagger"""  # noqa: E501
        self._total_bytes = None
        self._used_bytes = None
        self.discriminator = None
        if total_bytes is not None:
            self.total_bytes = total_bytes
        if used_bytes is not None:
            self.used_bytes = used_bytes

    @property
    def total_bytes(self):
        """Gets the total_bytes of this Memory.  # noqa: E501

        The total bytes  # noqa: E501

        :return: The total_bytes of this Memory.  # noqa: E501
        :rtype: int
        """
        return self._total_bytes

    @total_bytes.setter
    def total_bytes(self, total_bytes):
        """Sets the total_bytes of this Memory.

        The total bytes  # noqa: E501

        :param total_bytes: The total_bytes of this Memory.  # noqa: E501
        :type: int
        """

        self._total_bytes = total_bytes

    @property
    def used_bytes(self):
        """Gets the used_bytes of this Memory.  # noqa: E501

        The used bytes  # noqa: E501

        :return: The used_bytes of this Memory.  # noqa: E501
        :rtype: int
        """
        return self._used_bytes

    @used_bytes.setter
    def used_bytes(self, used_bytes):
        """Sets the used_bytes of this Memory.

        The used bytes  # noqa: E501

        :param used_bytes: The used_bytes of this Memory.  # noqa: E501
        :type: int
        """

        self._used_bytes = used_bytes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Memory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Memory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
