# coding: utf-8

"""
    DCV Session Manager

    DCV Session Manager API  # noqa: E501

    OpenAPI spec version: 2021.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SessionScreenshot(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_id': 'str',
        'images': 'list[SessionScreenshotImage]'
    }

    attribute_map = {
        'session_id': 'SessionId',
        'images': 'Images'
    }

    def __init__(self, session_id=None, images=None):  # noqa: E501
        """SessionScreenshot - a model defined in Swagger"""  # noqa: E501
        self._session_id = None
        self._images = None
        self.discriminator = None
        if session_id is not None:
            self.session_id = session_id
        if images is not None:
            self.images = images

    @property
    def session_id(self):
        """Gets the session_id of this SessionScreenshot.  # noqa: E501

        The id of the session  # noqa: E501

        :return: The session_id of this SessionScreenshot.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this SessionScreenshot.

        The id of the session  # noqa: E501

        :param session_id: The session_id of this SessionScreenshot.  # noqa: E501
        :type: str
        """

        self._session_id = session_id

    @property
    def images(self):
        """Gets the images of this SessionScreenshot.  # noqa: E501

        The array of session screenshots  # noqa: E501

        :return: The images of this SessionScreenshot.  # noqa: E501
        :rtype: list[SessionScreenshotImage]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this SessionScreenshot.

        The array of session screenshots  # noqa: E501

        :param images: The images of this SessionScreenshot.  # noqa: E501
        :type: list[SessionScreenshotImage]
        """

        self._images = images

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SessionScreenshot, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionScreenshot):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
