SCHEDULE_DB_IDEA_SESSION_ID_KEY = 'idea_session_id'
SCHEDULE_DB_IDEA_SESSION_OWNER_KEY = 'idea_session_owner'
SCHEDULE_DB_SCHEDULE_ID_KEY = 'schedule_id'
SCHEDULE_DB_SCHEDULE_TYPE_KEY = 'schedule_type'
SCHEDULE_DB_START_UP_TIME_KEY = 'shut_down_time'
SCHEDULE_DB_SHUT_DOWN_TIME_KEY = 'start_up_time'
SCHEDULE_DB_HASH_KEY = 'day_of_week'
SCHEDULE_DB_RANGE_KEY = SCHEDULE_DB_SCHEDULE_ID_KEY
