BASE_STACK_PREFIX = 'ss-base'

SOFTWARE_STACK_DB_HASH_KEY = 'base_os'
SOFTWARE_STACK_DB_RANGE_KEY = 'stack_id'
SOFTWARE_STACK_DB_NAME_KEY = 'name'
SOFTWARE_STACK_DB_DESCRIPTION_KEY = 'description'
SOFTWARE_STACK_DB_CREATED_ON_KEY = 'created_on'
SOFTWARE_STACK_DB_UPDATED_ON_KEY = 'updated_on'
SOFTWARE_STACK_DB_AMI_ID_KEY = 'ami_id'
SOFTWARE_STACK_DB_ENABLED_KEY = 'enabled'
SOFTWARE_STACK_DB_MIN_STORAGE_VALUE_KEY = 'min_storage_value'
SOFTWARE_STACK_DB_MIN_STORAGE_UNIT_KEY = 'min_storage_unit'
SOFTWARE_STACK_DB_MIN_RAM_VALUE_KEY = 'min_ram_value'
SOFTWARE_STACK_DB_MIN_RAM_UNIT_KEY = 'min_ram_unit'
SOFTWARE_STACK_DB_ARCHITECTURE_KEY = 'architecture'
SOFTWARE_STACK_DB_GPU_KEY = 'gpu'
SOFTWARE_STACK_DB_PROJECTS_KEY = 'projects'
SOFTWARE_STACK_DB_PROJECT_ID_KEY = 'project_id'
SOFTWARE_STACK_DB_PROJECT_NAME_KEY = 'name'
SOFTWARE_STACK_DB_PROJECT_TITLE_KEY = 'title'

SOFTWARE_STACK_DB_STACK_ID_KEY = SOFTWARE_STACK_DB_RANGE_KEY
SOFTWARE_STACK_DB_FILTER_BASE_OS_KEY = SOFTWARE_STACK_DB_HASH_KEY
SOFTWARE_STACK_DB_FILTER_PROJECT_ID_KEY = SOFTWARE_STACK_DB_PROJECT_ID_KEY
SOFTWARE_STACK_DB_FILTER_CREATED_ON_KEY = SOFTWARE_STACK_DB_CREATED_ON_KEY
SOFTWARE_STACK_DB_FILTER_UPDATED_ON_KEY = SOFTWARE_STACK_DB_UPDATED_ON_KEY
