#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_session import VirtualDesktopSession
from datamodel import util

from datamodel.models.virtual_desktop_session import VirtualDesktopSession  # noqa: E501

class BatchDeleteSessionRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sessions=None):  # noqa: E501
        """BatchDeleteSessionRequestContent - a model defined in OpenAPI

        :param sessions: The sessions of this BatchDeleteSessionRequestContent.  # noqa: E501
        :type sessions: List[VirtualDesktopSession]
        """
        self.openapi_types = {
            'sessions': List[VirtualDesktopSession]
        }

        self.attribute_map = {
            'sessions': 'sessions'
        }

        self._sessions = sessions

    @classmethod
    def from_dict(cls, dikt) -> 'BatchDeleteSessionRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchDeleteSessionRequestContent of this BatchDeleteSessionRequestContent.  # noqa: E501
        :rtype: BatchDeleteSessionRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sessions(self) -> List[VirtualDesktopSession]:
        """Gets the sessions of this BatchDeleteSessionRequestContent.

        List of sessions to delete  # noqa: E501

        :return: The sessions of this BatchDeleteSessionRequestContent.
        :rtype: List[VirtualDesktopSession]
        """
        return self._sessions

    @sessions.setter
    def sessions(self, sessions: List[VirtualDesktopSession]):
        """Sets the sessions of this BatchDeleteSessionRequestContent.

        List of sessions to delete  # noqa: E501

        :param sessions: The sessions of this BatchDeleteSessionRequestContent.
        :type sessions: List[VirtualDesktopSession]
        """
        if sessions is None:
            raise ValueError("Invalid value for `sessions`, must not be `None`")  # noqa: E501
        if sessions is not None and len(sessions) > 1000:
            raise ValueError("Invalid value for `sessions`, number of items must be less than or equal to `1000`")  # noqa: E501
        if sessions is not None and len(sessions) < 1:
            raise ValueError("Invalid value for `sessions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._sessions = sessions
