#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.batch_reboot_session_failure import BatchRebootSessionFailure
from datamodel.models.virtual_desktop_session import VirtualDesktopSession
from datamodel import util

from datamodel.models.batch_reboot_session_failure import BatchRebootSessionFailure  # noqa: E501
from datamodel.models.virtual_desktop_session import VirtualDesktopSession  # noqa: E501

class BatchRebootSessionResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, successful_list=None, unsuccessful_list=None):  # noqa: E501
        """BatchRebootSessionResponseContent - a model defined in OpenAPI

        :param successful_list: The successful_list of this BatchRebootSessionResponseContent.  # noqa: E501
        :type successful_list: List[VirtualDesktopSession]
        :param unsuccessful_list: The unsuccessful_list of this BatchRebootSessionResponseContent.  # noqa: E501
        :type unsuccessful_list: List[BatchRebootSessionFailure]
        """
        self.openapi_types = {
            'successful_list': List[VirtualDesktopSession],
            'unsuccessful_list': List[BatchRebootSessionFailure]
        }

        self.attribute_map = {
            'successful_list': 'successful-list',
            'unsuccessful_list': 'unsuccessful-list'
        }

        self._successful_list = successful_list
        self._unsuccessful_list = unsuccessful_list

    @classmethod
    def from_dict(cls, dikt) -> 'BatchRebootSessionResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchRebootSessionResponseContent of this BatchRebootSessionResponseContent.  # noqa: E501
        :rtype: BatchRebootSessionResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def successful_list(self) -> List[VirtualDesktopSession]:
        """Gets the successful_list of this BatchRebootSessionResponseContent.

        List of sessions that were successfully rebooted  # noqa: E501

        :return: The successful_list of this BatchRebootSessionResponseContent.
        :rtype: List[VirtualDesktopSession]
        """
        return self._successful_list

    @successful_list.setter
    def successful_list(self, successful_list: List[VirtualDesktopSession]):
        """Sets the successful_list of this BatchRebootSessionResponseContent.

        List of sessions that were successfully rebooted  # noqa: E501

        :param successful_list: The successful_list of this BatchRebootSessionResponseContent.
        :type successful_list: List[VirtualDesktopSession]
        """
        if successful_list is None:
            raise ValueError("Invalid value for `successful_list`, must not be `None`")  # noqa: E501

        self._successful_list = successful_list

    @property
    def unsuccessful_list(self) -> List[BatchRebootSessionFailure]:
        """Gets the unsuccessful_list of this BatchRebootSessionResponseContent.

        List of sessions that failed to reboot  # noqa: E501

        :return: The unsuccessful_list of this BatchRebootSessionResponseContent.
        :rtype: List[BatchRebootSessionFailure]
        """
        return self._unsuccessful_list

    @unsuccessful_list.setter
    def unsuccessful_list(self, unsuccessful_list: List[BatchRebootSessionFailure]):
        """Sets the unsuccessful_list of this BatchRebootSessionResponseContent.

        List of sessions that failed to reboot  # noqa: E501

        :param unsuccessful_list: The unsuccessful_list of this BatchRebootSessionResponseContent.
        :type unsuccessful_list: List[BatchRebootSessionFailure]
        """
        if unsuccessful_list is None:
            raise ValueError("Invalid value for `unsuccessful_list`, must not be `None`")  # noqa: E501

        self._unsuccessful_list = unsuccessful_list
