#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_session_screenshot import VirtualDesktopSessionScreenshot
from datamodel import util

from datamodel.models.virtual_desktop_session_screenshot import VirtualDesktopSessionScreenshot  # noqa: E501

class BatchGetSessionScreenshotRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, screenshots=None):  # noqa: E501
        """BatchGetSessionScreenshotRequestContent - a model defined in OpenAPI

        :param screenshots: The screenshots of this BatchGetSessionScreenshotRequestContent.  # noqa: E501
        :type screenshots: List[VirtualDesktopSessionScreenshot]
        """
        self.openapi_types = {
            'screenshots': List[VirtualDesktopSessionScreenshot]
        }

        self.attribute_map = {
            'screenshots': 'screenshots'
        }

        self._screenshots = screenshots

    @classmethod
    def from_dict(cls, dikt) -> 'BatchGetSessionScreenshotRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchGetSessionScreenshotRequestContent of this BatchGetSessionScreenshotRequestContent.  # noqa: E501
        :rtype: BatchGetSessionScreenshotRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def screenshots(self) -> List[VirtualDesktopSessionScreenshot]:
        """Gets the screenshots of this BatchGetSessionScreenshotRequestContent.

        List of sessions to get screenshots for  # noqa: E501

        :return: The screenshots of this BatchGetSessionScreenshotRequestContent.
        :rtype: List[VirtualDesktopSessionScreenshot]
        """
        return self._screenshots

    @screenshots.setter
    def screenshots(self, screenshots: List[VirtualDesktopSessionScreenshot]):
        """Sets the screenshots of this BatchGetSessionScreenshotRequestContent.

        List of sessions to get screenshots for  # noqa: E501

        :param screenshots: The screenshots of this BatchGetSessionScreenshotRequestContent.
        :type screenshots: List[VirtualDesktopSessionScreenshot]
        """
        if screenshots is None:
            raise ValueError("Invalid value for `screenshots`, must not be `None`")  # noqa: E501
        if screenshots is not None and len(screenshots) > 1000:
            raise ValueError("Invalid value for `screenshots`, number of items must be less than or equal to `1000`")  # noqa: E501
        if screenshots is not None and len(screenshots) < 1:
            raise ValueError("Invalid value for `screenshots`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._screenshots = screenshots
