#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.batch_operation_error_code import BatchOperationErrorCode
from datamodel.models.virtual_desktop_session import VirtualDesktopSession
from datamodel import util
from datamodel.serializers.batch_reboot_session_failure_serializer import batchrebootsessionfailure_serializer

from datamodel.models.batch_operation_error_code import BatchOperationErrorCode  # noqa: E501
from datamodel.models.virtual_desktop_session import VirtualDesktopSession  # noqa: E501

class BatchRebootSessionFailure(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session=None, error_code=None, message=None):  # noqa: E501
        """BatchRebootSessionFailure - a model defined in OpenAPI

        :param session: The session of this BatchRebootSessionFailure.  # noqa: E501
        :type session: VirtualDesktopSession
        :param error_code: The error_code of this BatchRebootSessionFailure.  # noqa: E501
        :type error_code: BatchOperationErrorCode
        :param message: The message of this BatchRebootSessionFailure.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'session': VirtualDesktopSession,
            'error_code': BatchOperationErrorCode,
            'message': str
        }

        self.attribute_map = {
            'session': 'session',
            'error_code': 'error-code',
            'message': 'message'
        }

        self._session = session
        self._error_code = error_code
        self._message = message

    def to_ddb_dict(self):
        """
        Convert this BatchRebootSessionFailure instance to DynamoDB dictionary format.
        
        Uses the BatchRebootSessionFailureSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return batchrebootsessionfailure_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create BatchRebootSessionFailure instance from DynamoDB dictionary.
        
        Uses the BatchRebootSessionFailureSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            BatchRebootSessionFailure instance
        """
        api_data = batchrebootsessionfailure_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'BatchRebootSessionFailure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchRebootSessionFailure of this BatchRebootSessionFailure.  # noqa: E501
        :rtype: BatchRebootSessionFailure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session(self) -> VirtualDesktopSession:
        """Gets the session of this BatchRebootSessionFailure.


        :return: The session of this BatchRebootSessionFailure.
        :rtype: VirtualDesktopSession
        """
        return self._session

    @session.setter
    def session(self, session: VirtualDesktopSession):
        """Sets the session of this BatchRebootSessionFailure.


        :param session: The session of this BatchRebootSessionFailure.
        :type session: VirtualDesktopSession
        """
        if session is None:
            raise ValueError("Invalid value for `session`, must not be `None`")  # noqa: E501

        self._session = session

    @property
    def error_code(self) -> BatchOperationErrorCode:
        """Gets the error_code of this BatchRebootSessionFailure.


        :return: The error_code of this BatchRebootSessionFailure.
        :rtype: BatchOperationErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: BatchOperationErrorCode):
        """Sets the error_code of this BatchRebootSessionFailure.


        :param error_code: The error_code of this BatchRebootSessionFailure.
        :type error_code: BatchOperationErrorCode
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def message(self) -> str:
        """Gets the message of this BatchRebootSessionFailure.

        Error message describing why the session failed to reboot  # noqa: E501

        :return: The message of this BatchRebootSessionFailure.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this BatchRebootSessionFailure.

        Error message describing why the session failed to reboot  # noqa: E501

        :param message: The message of this BatchRebootSessionFailure.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
