#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.batch_operation_error_code import BatchOperationErrorCode
from datamodel.models.virtual_desktop_session_screenshot import VirtualDesktopSessionScreenshot
from datamodel import util
from datamodel.serializers.batch_get_session_screenshot_failure_serializer import batchgetsessionscreenshotfailure_serializer

from datamodel.models.batch_operation_error_code import BatchOperationErrorCode  # noqa: E501
from datamodel.models.virtual_desktop_session_screenshot import VirtualDesktopSessionScreenshot  # noqa: E501

class BatchGetSessionScreenshotFailure(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, screenshot=None, error_code=None, message=None):  # noqa: E501
        """BatchGetSessionScreenshotFailure - a model defined in OpenAPI

        :param screenshot: The screenshot of this BatchGetSessionScreenshotFailure.  # noqa: E501
        :type screenshot: VirtualDesktopSessionScreenshot
        :param error_code: The error_code of this BatchGetSessionScreenshotFailure.  # noqa: E501
        :type error_code: BatchOperationErrorCode
        :param message: The message of this BatchGetSessionScreenshotFailure.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'screenshot': VirtualDesktopSessionScreenshot,
            'error_code': BatchOperationErrorCode,
            'message': str
        }

        self.attribute_map = {
            'screenshot': 'screenshot',
            'error_code': 'error_code',
            'message': 'message'
        }

        self._screenshot = screenshot
        self._error_code = error_code
        self._message = message

    def to_ddb_dict(self):
        """
        Convert this BatchGetSessionScreenshotFailure instance to DynamoDB dictionary format.
        
        Uses the BatchGetSessionScreenshotFailureSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return batchgetsessionscreenshotfailure_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create BatchGetSessionScreenshotFailure instance from DynamoDB dictionary.
        
        Uses the BatchGetSessionScreenshotFailureSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            BatchGetSessionScreenshotFailure instance
        """
        api_data = batchgetsessionscreenshotfailure_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'BatchGetSessionScreenshotFailure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchGetSessionScreenshotFailure of this BatchGetSessionScreenshotFailure.  # noqa: E501
        :rtype: BatchGetSessionScreenshotFailure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def screenshot(self) -> VirtualDesktopSessionScreenshot:
        """Gets the screenshot of this BatchGetSessionScreenshotFailure.


        :return: The screenshot of this BatchGetSessionScreenshotFailure.
        :rtype: VirtualDesktopSessionScreenshot
        """
        return self._screenshot

    @screenshot.setter
    def screenshot(self, screenshot: VirtualDesktopSessionScreenshot):
        """Sets the screenshot of this BatchGetSessionScreenshotFailure.


        :param screenshot: The screenshot of this BatchGetSessionScreenshotFailure.
        :type screenshot: VirtualDesktopSessionScreenshot
        """
        if screenshot is None:
            raise ValueError("Invalid value for `screenshot`, must not be `None`")  # noqa: E501

        self._screenshot = screenshot

    @property
    def error_code(self) -> BatchOperationErrorCode:
        """Gets the error_code of this BatchGetSessionScreenshotFailure.


        :return: The error_code of this BatchGetSessionScreenshotFailure.
        :rtype: BatchOperationErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: BatchOperationErrorCode):
        """Sets the error_code of this BatchGetSessionScreenshotFailure.


        :param error_code: The error_code of this BatchGetSessionScreenshotFailure.
        :type error_code: BatchOperationErrorCode
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def message(self) -> str:
        """Gets the message of this BatchGetSessionScreenshotFailure.

        Error message describing why the screenshot could not be retrieved  # noqa: E501

        :return: The message of this BatchGetSessionScreenshotFailure.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this BatchGetSessionScreenshotFailure.

        Error message describing why the screenshot could not be retrieved  # noqa: E501

        :param message: The message of this BatchGetSessionScreenshotFailure.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
