#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_session import VirtualDesktopSession
from datamodel.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack
from datamodel import util

from datamodel.models.virtual_desktop_session import VirtualDesktopSession  # noqa: E501
from datamodel.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack  # noqa: E501

class CreateSoftwareStackFromSessionRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session=None, software_stack=None):  # noqa: E501
        """CreateSoftwareStackFromSessionRequestContent - a model defined in OpenAPI

        :param session: The session of this CreateSoftwareStackFromSessionRequestContent.  # noqa: E501
        :type session: VirtualDesktopSession
        :param software_stack: The software_stack of this CreateSoftwareStackFromSessionRequestContent.  # noqa: E501
        :type software_stack: VirtualDesktopSoftwareStack
        """
        self.openapi_types = {
            'session': VirtualDesktopSession,
            'software_stack': VirtualDesktopSoftwareStack
        }

        self.attribute_map = {
            'session': 'session',
            'software_stack': 'software_stack'
        }

        self._session = session
        self._software_stack = software_stack

    @classmethod
    def from_dict(cls, dikt) -> 'CreateSoftwareStackFromSessionRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateSoftwareStackFromSessionRequestContent of this CreateSoftwareStackFromSessionRequestContent.  # noqa: E501
        :rtype: CreateSoftwareStackFromSessionRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session(self) -> VirtualDesktopSession:
        """Gets the session of this CreateSoftwareStackFromSessionRequestContent.


        :return: The session of this CreateSoftwareStackFromSessionRequestContent.
        :rtype: VirtualDesktopSession
        """
        return self._session

    @session.setter
    def session(self, session: VirtualDesktopSession):
        """Sets the session of this CreateSoftwareStackFromSessionRequestContent.


        :param session: The session of this CreateSoftwareStackFromSessionRequestContent.
        :type session: VirtualDesktopSession
        """
        if session is None:
            raise ValueError("Invalid value for `session`, must not be `None`")  # noqa: E501

        self._session = session

    @property
    def software_stack(self) -> VirtualDesktopSoftwareStack:
        """Gets the software_stack of this CreateSoftwareStackFromSessionRequestContent.


        :return: The software_stack of this CreateSoftwareStackFromSessionRequestContent.
        :rtype: VirtualDesktopSoftwareStack
        """
        return self._software_stack

    @software_stack.setter
    def software_stack(self, software_stack: VirtualDesktopSoftwareStack):
        """Sets the software_stack of this CreateSoftwareStackFromSessionRequestContent.


        :param software_stack: The software_stack of this CreateSoftwareStackFromSessionRequestContent.
        :type software_stack: VirtualDesktopSoftwareStack
        """
        if software_stack is None:
            raise ValueError("Invalid value for `software_stack`, must not be `None`")  # noqa: E501

        self._software_stack = software_stack
