#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_session_connection import VirtualDesktopSessionConnection
from datamodel import util

from datamodel.models.virtual_desktop_session_connection import VirtualDesktopSessionConnection  # noqa: E501

class GetSessionConnectionResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, connection=None):  # noqa: E501
        """GetSessionConnectionResponseContent - a model defined in OpenAPI

        :param connection: The connection of this GetSessionConnectionResponseContent.  # noqa: E501
        :type connection: VirtualDesktopSessionConnection
        """
        self.openapi_types = {
            'connection': VirtualDesktopSessionConnection
        }

        self.attribute_map = {
            'connection': 'connection'
        }

        self._connection = connection

    @classmethod
    def from_dict(cls, dikt) -> 'GetSessionConnectionResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetSessionConnectionResponseContent of this GetSessionConnectionResponseContent.  # noqa: E501
        :rtype: GetSessionConnectionResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def connection(self) -> VirtualDesktopSessionConnection:
        """Gets the connection of this GetSessionConnectionResponseContent.


        :return: The connection of this GetSessionConnectionResponseContent.
        :rtype: VirtualDesktopSessionConnection
        """
        return self._connection

    @connection.setter
    def connection(self, connection: VirtualDesktopSessionConnection):
        """Sets the connection of this GetSessionConnectionResponseContent.


        :param connection: The connection of this GetSessionConnectionResponseContent.
        :type connection: VirtualDesktopSessionConnection
        """
        if connection is None:
            raise ValueError("Invalid value for `connection`, must not be `None`")  # noqa: E501

        self._connection = connection
