#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.res_date_range import ResDateRange
from datamodel.models.res_filter import ResFilter
from datamodel.models.res_paginator import ResPaginator
from datamodel.models.res_sort_by import ResSortBy
from datamodel.models.virtual_desktop_permission_profile import VirtualDesktopPermissionProfile
from datamodel import util

from datamodel.models.res_date_range import ResDateRange  # noqa: E501
from datamodel.models.res_filter import ResFilter  # noqa: E501
from datamodel.models.res_paginator import ResPaginator  # noqa: E501
from datamodel.models.res_sort_by import ResSortBy  # noqa: E501
from datamodel.models.virtual_desktop_permission_profile import VirtualDesktopPermissionProfile  # noqa: E501

class GetPermissionProfileResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, paginator=None, sort_by=None, data_range=None, filters=None, profile=None):  # noqa: E501
        """GetPermissionProfileResponseContent - a model defined in OpenAPI

        :param paginator: The paginator of this GetPermissionProfileResponseContent.  # noqa: E501
        :type paginator: ResPaginator
        :param sort_by: The sort_by of this GetPermissionProfileResponseContent.  # noqa: E501
        :type sort_by: ResSortBy
        :param data_range: The data_range of this GetPermissionProfileResponseContent.  # noqa: E501
        :type data_range: ResDateRange
        :param filters: The filters of this GetPermissionProfileResponseContent.  # noqa: E501
        :type filters: List[ResFilter]
        :param profile: The profile of this GetPermissionProfileResponseContent.  # noqa: E501
        :type profile: VirtualDesktopPermissionProfile
        """
        self.openapi_types = {
            'paginator': ResPaginator,
            'sort_by': ResSortBy,
            'data_range': ResDateRange,
            'filters': List[ResFilter],
            'profile': VirtualDesktopPermissionProfile
        }

        self.attribute_map = {
            'paginator': 'paginator',
            'sort_by': 'sort_by',
            'data_range': 'data_range',
            'filters': 'filters',
            'profile': 'profile'
        }

        self._paginator = paginator
        self._sort_by = sort_by
        self._data_range = data_range
        self._filters = filters
        self._profile = profile

    @classmethod
    def from_dict(cls, dikt) -> 'GetPermissionProfileResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetPermissionProfileResponseContent of this GetPermissionProfileResponseContent.  # noqa: E501
        :rtype: GetPermissionProfileResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paginator(self) -> ResPaginator:
        """Gets the paginator of this GetPermissionProfileResponseContent.


        :return: The paginator of this GetPermissionProfileResponseContent.
        :rtype: ResPaginator
        """
        return self._paginator

    @paginator.setter
    def paginator(self, paginator: ResPaginator):
        """Sets the paginator of this GetPermissionProfileResponseContent.


        :param paginator: The paginator of this GetPermissionProfileResponseContent.
        :type paginator: ResPaginator
        """

        self._paginator = paginator

    @property
    def sort_by(self) -> ResSortBy:
        """Gets the sort_by of this GetPermissionProfileResponseContent.


        :return: The sort_by of this GetPermissionProfileResponseContent.
        :rtype: ResSortBy
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by: ResSortBy):
        """Sets the sort_by of this GetPermissionProfileResponseContent.


        :param sort_by: The sort_by of this GetPermissionProfileResponseContent.
        :type sort_by: ResSortBy
        """

        self._sort_by = sort_by

    @property
    def data_range(self) -> ResDateRange:
        """Gets the data_range of this GetPermissionProfileResponseContent.


        :return: The data_range of this GetPermissionProfileResponseContent.
        :rtype: ResDateRange
        """
        return self._data_range

    @data_range.setter
    def data_range(self, data_range: ResDateRange):
        """Sets the data_range of this GetPermissionProfileResponseContent.


        :param data_range: The data_range of this GetPermissionProfileResponseContent.
        :type data_range: ResDateRange
        """

        self._data_range = data_range

    @property
    def filters(self) -> List[ResFilter]:
        """Gets the filters of this GetPermissionProfileResponseContent.

        List of filters applied to the query  # noqa: E501

        :return: The filters of this GetPermissionProfileResponseContent.
        :rtype: List[ResFilter]
        """
        return self._filters

    @filters.setter
    def filters(self, filters: List[ResFilter]):
        """Sets the filters of this GetPermissionProfileResponseContent.

        List of filters applied to the query  # noqa: E501

        :param filters: The filters of this GetPermissionProfileResponseContent.
        :type filters: List[ResFilter]
        """

        self._filters = filters

    @property
    def profile(self) -> VirtualDesktopPermissionProfile:
        """Gets the profile of this GetPermissionProfileResponseContent.


        :return: The profile of this GetPermissionProfileResponseContent.
        :rtype: VirtualDesktopPermissionProfile
        """
        return self._profile

    @profile.setter
    def profile(self, profile: VirtualDesktopPermissionProfile):
        """Sets the profile of this GetPermissionProfileResponseContent.


        :param profile: The profile of this GetPermissionProfileResponseContent.
        :type profile: VirtualDesktopPermissionProfile
        """

        self._profile = profile
