#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.list_value_serializer import listvalue_serializer


class ListValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, list_value=None):  # noqa: E501
        """ListValue - a model defined in OpenAPI

        :param list_value: The list_value of this ListValue.  # noqa: E501
        :type list_value: List[object]
        """
        self.openapi_types = {
            'list_value': List[object]
        }

        self.attribute_map = {
            'list_value': 'listValue'
        }

        self._list_value = list_value

    def to_ddb_dict(self):
        """
        Convert this ListValue instance to DynamoDB dictionary format.
        
        Uses the ListValueSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return listvalue_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create ListValue instance from DynamoDB dictionary.
        
        Uses the ListValueSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            ListValue instance
        """
        api_data = listvalue_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'ListValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The listValue of this ListValue.  # noqa: E501
        :rtype: ListValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list_value(self) -> List[object]:
        """Gets the list_value of this ListValue.

        List of filter values  # noqa: E501

        :return: The list_value of this ListValue.
        :rtype: List[object]
        """
        return self._list_value

    @list_value.setter
    def list_value(self, list_value: List[object]):
        """Sets the list_value of this ListValue.

        List of filter values  # noqa: E501

        :param list_value: The list_value of this ListValue.
        :type list_value: List[object]
        """
        if list_value is None:
            raise ValueError("Invalid value for `list_value`, must not be `None`")  # noqa: E501

        self._list_value = list_value
