#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.res_date_range import ResDateRange
from datamodel.models.res_filter import ResFilter
from datamodel.models.res_paginator import ResPaginator
from datamodel.models.res_sort_by import ResSortBy
from datamodel.models.virtual_desktop_session import VirtualDesktopSession
from datamodel import util

from datamodel.models.res_date_range import ResDateRange  # noqa: E501
from datamodel.models.res_filter import ResFilter  # noqa: E501
from datamodel.models.res_paginator import ResPaginator  # noqa: E501
from datamodel.models.res_sort_by import ResSortBy  # noqa: E501
from datamodel.models.virtual_desktop_session import VirtualDesktopSession  # noqa: E501

class ListSessionsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, paginator=None, sort_by=None, data_range=None, filters=None, listing=None, next_token=None):  # noqa: E501
        """ListSessionsResponseContent - a model defined in OpenAPI

        :param paginator: The paginator of this ListSessionsResponseContent.  # noqa: E501
        :type paginator: ResPaginator
        :param sort_by: The sort_by of this ListSessionsResponseContent.  # noqa: E501
        :type sort_by: ResSortBy
        :param data_range: The data_range of this ListSessionsResponseContent.  # noqa: E501
        :type data_range: ResDateRange
        :param filters: The filters of this ListSessionsResponseContent.  # noqa: E501
        :type filters: List[ResFilter]
        :param listing: The listing of this ListSessionsResponseContent.  # noqa: E501
        :type listing: List[VirtualDesktopSession]
        :param next_token: The next_token of this ListSessionsResponseContent.  # noqa: E501
        :type next_token: str
        """
        self.openapi_types = {
            'paginator': ResPaginator,
            'sort_by': ResSortBy,
            'data_range': ResDateRange,
            'filters': List[ResFilter],
            'listing': List[VirtualDesktopSession],
            'next_token': str
        }

        self.attribute_map = {
            'paginator': 'paginator',
            'sort_by': 'sort_by',
            'data_range': 'data_range',
            'filters': 'filters',
            'listing': 'listing',
            'next_token': 'nextToken'
        }

        self._paginator = paginator
        self._sort_by = sort_by
        self._data_range = data_range
        self._filters = filters
        self._listing = listing
        self._next_token = next_token

    @classmethod
    def from_dict(cls, dikt) -> 'ListSessionsResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListSessionsResponseContent of this ListSessionsResponseContent.  # noqa: E501
        :rtype: ListSessionsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paginator(self) -> ResPaginator:
        """Gets the paginator of this ListSessionsResponseContent.


        :return: The paginator of this ListSessionsResponseContent.
        :rtype: ResPaginator
        """
        return self._paginator

    @paginator.setter
    def paginator(self, paginator: ResPaginator):
        """Sets the paginator of this ListSessionsResponseContent.


        :param paginator: The paginator of this ListSessionsResponseContent.
        :type paginator: ResPaginator
        """

        self._paginator = paginator

    @property
    def sort_by(self) -> ResSortBy:
        """Gets the sort_by of this ListSessionsResponseContent.


        :return: The sort_by of this ListSessionsResponseContent.
        :rtype: ResSortBy
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by: ResSortBy):
        """Sets the sort_by of this ListSessionsResponseContent.


        :param sort_by: The sort_by of this ListSessionsResponseContent.
        :type sort_by: ResSortBy
        """

        self._sort_by = sort_by

    @property
    def data_range(self) -> ResDateRange:
        """Gets the data_range of this ListSessionsResponseContent.


        :return: The data_range of this ListSessionsResponseContent.
        :rtype: ResDateRange
        """
        return self._data_range

    @data_range.setter
    def data_range(self, data_range: ResDateRange):
        """Sets the data_range of this ListSessionsResponseContent.


        :param data_range: The data_range of this ListSessionsResponseContent.
        :type data_range: ResDateRange
        """

        self._data_range = data_range

    @property
    def filters(self) -> List[ResFilter]:
        """Gets the filters of this ListSessionsResponseContent.

        List of filters applied to the query  # noqa: E501

        :return: The filters of this ListSessionsResponseContent.
        :rtype: List[ResFilter]
        """
        return self._filters

    @filters.setter
    def filters(self, filters: List[ResFilter]):
        """Sets the filters of this ListSessionsResponseContent.

        List of filters applied to the query  # noqa: E501

        :param filters: The filters of this ListSessionsResponseContent.
        :type filters: List[ResFilter]
        """

        self._filters = filters

    @property
    def listing(self) -> List[VirtualDesktopSession]:
        """Gets the listing of this ListSessionsResponseContent.

        List of sessions  # noqa: E501

        :return: The listing of this ListSessionsResponseContent.
        :rtype: List[VirtualDesktopSession]
        """
        return self._listing

    @listing.setter
    def listing(self, listing: List[VirtualDesktopSession]):
        """Sets the listing of this ListSessionsResponseContent.

        List of sessions  # noqa: E501

        :param listing: The listing of this ListSessionsResponseContent.
        :type listing: List[VirtualDesktopSession]
        """

        self._listing = listing

    @property
    def next_token(self) -> str:
        """Gets the next_token of this ListSessionsResponseContent.

        Pagination token for next page  # noqa: E501

        :return: The next_token of this ListSessionsResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token: str):
        """Sets the next_token of this ListSessionsResponseContent.

        Pagination token for next page  # noqa: E501

        :param next_token: The next_token of this ListSessionsResponseContent.
        :type next_token: str
        """

        self._next_token = next_token
