#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.permission_profile_serializer import permissionprofile_serializer


class PermissionProfile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, profile_id=None):  # noqa: E501
        """PermissionProfile - a model defined in OpenAPI

        :param profile_id: The profile_id of this PermissionProfile.  # noqa: E501
        :type profile_id: str
        """
        self.openapi_types = {
            'profile_id': str
        }

        self.attribute_map = {
            'profile_id': 'profile_id'
        }

        self._profile_id = profile_id

    def to_ddb_dict(self):
        """
        Convert this PermissionProfile instance to DynamoDB dictionary format.
        
        Uses the PermissionProfileSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return permissionprofile_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create PermissionProfile instance from DynamoDB dictionary.
        
        Uses the PermissionProfileSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            PermissionProfile instance
        """
        api_data = permissionprofile_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'PermissionProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PermissionProfile of this PermissionProfile.  # noqa: E501
        :rtype: PermissionProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def profile_id(self) -> str:
        """Gets the profile_id of this PermissionProfile.


        :return: The profile_id of this PermissionProfile.
        :rtype: str
        """
        return self._profile_id

    @profile_id.setter
    def profile_id(self, profile_id: str):
        """Sets the profile_id of this PermissionProfile.


        :param profile_id: The profile_id of this PermissionProfile.
        :type profile_id: str
        """
        if profile_id is None:
            raise ValueError("Invalid value for `profile_id`, must not be `None`")  # noqa: E501

        self._profile_id = profile_id
