#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.budget import Budget
from datamodel.models.project_scripts import ProjectScripts
from datamodel import util
from datamodel.serializers.project_serializer import project_serializer

from datamodel.models.budget import Budget  # noqa: E501
from datamodel.models.project_scripts import ProjectScripts  # noqa: E501

class Project(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, project_id=None, name=None, title=None, description=None, budget=None, security_groups=None, policy_arns=None, scripts=None, tags=None):  # noqa: E501
        """Project - a model defined in OpenAPI

        :param project_id: The project_id of this Project.  # noqa: E501
        :type project_id: str
        :param name: The name of this Project.  # noqa: E501
        :type name: str
        :param title: The title of this Project.  # noqa: E501
        :type title: str
        :param description: The description of this Project.  # noqa: E501
        :type description: str
        :param budget: The budget of this Project.  # noqa: E501
        :type budget: Budget
        :param security_groups: The security_groups of this Project.  # noqa: E501
        :type security_groups: List[str]
        :param policy_arns: The policy_arns of this Project.  # noqa: E501
        :type policy_arns: List[str]
        :param scripts: The scripts of this Project.  # noqa: E501
        :type scripts: ProjectScripts
        :param tags: The tags of this Project.  # noqa: E501
        :type tags: List[object]
        """
        self.openapi_types = {
            'project_id': str,
            'name': str,
            'title': str,
            'description': str,
            'budget': Budget,
            'security_groups': List[str],
            'policy_arns': List[str],
            'scripts': ProjectScripts,
            'tags': List[object]
        }

        self.attribute_map = {
            'project_id': 'project_id',
            'name': 'name',
            'title': 'title',
            'description': 'description',
            'budget': 'budget',
            'security_groups': 'security_groups',
            'policy_arns': 'policy_arns',
            'scripts': 'scripts',
            'tags': 'tags'
        }

        self._project_id = project_id
        self._name = name
        self._title = title
        self._description = description
        self._budget = budget
        self._security_groups = security_groups
        self._policy_arns = policy_arns
        self._scripts = scripts
        self._tags = tags

    def to_ddb_dict(self):
        """
        Convert this Project instance to DynamoDB dictionary format.
        
        Uses the ProjectSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return project_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create Project instance from DynamoDB dictionary.
        
        Uses the ProjectSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            Project instance
        """
        api_data = project_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'Project':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project of this Project.  # noqa: E501
        :rtype: Project
        """
        return util.deserialize_model(dikt, cls)

    @property
    def project_id(self) -> str:
        """Gets the project_id of this Project.

        Project identifier  # noqa: E501

        :return: The project_id of this Project.
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: str):
        """Sets the project_id of this Project.

        Project identifier  # noqa: E501

        :param project_id: The project_id of this Project.
        :type project_id: str
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def name(self) -> str:
        """Gets the name of this Project.

        Project name  # noqa: E501

        :return: The name of this Project.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Project.

        Project name  # noqa: E501

        :param name: The name of this Project.
        :type name: str
        """

        self._name = name

    @property
    def title(self) -> str:
        """Gets the title of this Project.

        Project title  # noqa: E501

        :return: The title of this Project.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Project.

        Project title  # noqa: E501

        :param title: The title of this Project.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Project.

        Project description  # noqa: E501

        :return: The description of this Project.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Project.

        Project description  # noqa: E501

        :param description: The description of this Project.
        :type description: str
        """

        self._description = description

    @property
    def budget(self) -> Budget:
        """Gets the budget of this Project.


        :return: The budget of this Project.
        :rtype: Budget
        """
        return self._budget

    @budget.setter
    def budget(self, budget: Budget):
        """Sets the budget of this Project.


        :param budget: The budget of this Project.
        :type budget: Budget
        """

        self._budget = budget

    @property
    def security_groups(self) -> List[str]:
        """Gets the security_groups of this Project.

        Security group IDs associated with the project  # noqa: E501

        :return: The security_groups of this Project.
        :rtype: List[str]
        """
        return self._security_groups

    @security_groups.setter
    def security_groups(self, security_groups: List[str]):
        """Sets the security_groups of this Project.

        Security group IDs associated with the project  # noqa: E501

        :param security_groups: The security_groups of this Project.
        :type security_groups: List[str]
        """
        if security_groups is not None and len(security_groups) > 5:
            raise ValueError("Invalid value for `security_groups`, number of items must be less than or equal to `5`")  # noqa: E501

        self._security_groups = security_groups

    @property
    def policy_arns(self) -> List[str]:
        """Gets the policy_arns of this Project.

        IAM policy ARNs associated with the project  # noqa: E501

        :return: The policy_arns of this Project.
        :rtype: List[str]
        """
        return self._policy_arns

    @policy_arns.setter
    def policy_arns(self, policy_arns: List[str]):
        """Sets the policy_arns of this Project.

        IAM policy ARNs associated with the project  # noqa: E501

        :param policy_arns: The policy_arns of this Project.
        :type policy_arns: List[str]
        """
        if policy_arns is not None and len(policy_arns) > 10:
            raise ValueError("Invalid value for `policy_arns`, number of items must be less than or equal to `10`")  # noqa: E501

        self._policy_arns = policy_arns

    @property
    def scripts(self) -> ProjectScripts:
        """Gets the scripts of this Project.


        :return: The scripts of this Project.
        :rtype: ProjectScripts
        """
        return self._scripts

    @scripts.setter
    def scripts(self, scripts: ProjectScripts):
        """Sets the scripts of this Project.


        :param scripts: The scripts of this Project.
        :type scripts: ProjectScripts
        """

        self._scripts = scripts

    @property
    def tags(self) -> List[object]:
        """Gets the tags of this Project.

        Project tags  # noqa: E501

        :return: The tags of this Project.
        :rtype: List[object]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[object]):
        """Sets the tags of this Project.

        Project tags  # noqa: E501

        :param tags: The tags of this Project.
        :type tags: List[object]
        """
        if tags is not None and len(tags) > 50:
            raise ValueError("Invalid value for `tags`, number of items must be less than or equal to `50`")  # noqa: E501

        self._tags = tags
