#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.res_sort_order import ResSortOrder
from datamodel import util
from datamodel.serializers.res_sort_by_serializer import ressortby_serializer

from datamodel.models.res_sort_order import ResSortOrder  # noqa: E501

class ResSortBy(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, key=None, order=None):  # noqa: E501
        """ResSortBy - a model defined in OpenAPI

        :param key: The key of this ResSortBy.  # noqa: E501
        :type key: str
        :param order: The order of this ResSortBy.  # noqa: E501
        :type order: ResSortOrder
        """
        self.openapi_types = {
            'key': str,
            'order': ResSortOrder
        }

        self.attribute_map = {
            'key': 'key',
            'order': 'order'
        }

        self._key = key
        self._order = order

    def to_ddb_dict(self):
        """
        Convert this ResSortBy instance to DynamoDB dictionary format.
        
        Uses the ResSortBySerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return ressortby_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create ResSortBy instance from DynamoDB dictionary.
        
        Uses the ResSortBySerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            ResSortBy instance
        """
        api_data = ressortby_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'ResSortBy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResSortBy of this ResSortBy.  # noqa: E501
        :rtype: ResSortBy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this ResSortBy.

        The field key to sort by  # noqa: E501

        :return: The key of this ResSortBy.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this ResSortBy.

        The field key to sort by  # noqa: E501

        :param key: The key of this ResSortBy.
        :type key: str
        """

        self._key = key

    @property
    def order(self) -> ResSortOrder:
        """Gets the order of this ResSortBy.


        :return: The order of this ResSortBy.
        :rtype: ResSortOrder
        """
        return self._order

    @order.setter
    def order(self, order: ResSortOrder):
        """Sets the order of this ResSortBy.


        :param order: The order of this ResSortBy.
        :type order: ResSortOrder
        """

        self._order = order
