#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.script import Script
from datamodel import util
from datamodel.serializers.script_events_serializer import scriptevents_serializer

from datamodel.models.script import Script  # noqa: E501

class ScriptEvents(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, on_vdi_start=None, on_vdi_configured=None, rerun_on_reboot=None):  # noqa: E501
        """ScriptEvents - a model defined in OpenAPI

        :param on_vdi_start: The on_vdi_start of this ScriptEvents.  # noqa: E501
        :type on_vdi_start: List[Script]
        :param on_vdi_configured: The on_vdi_configured of this ScriptEvents.  # noqa: E501
        :type on_vdi_configured: List[Script]
        :param rerun_on_reboot: The rerun_on_reboot of this ScriptEvents.  # noqa: E501
        :type rerun_on_reboot: bool
        """
        self.openapi_types = {
            'on_vdi_start': List[Script],
            'on_vdi_configured': List[Script],
            'rerun_on_reboot': bool
        }

        self.attribute_map = {
            'on_vdi_start': 'on_vdi_start',
            'on_vdi_configured': 'on_vdi_configured',
            'rerun_on_reboot': 'rerun_on_reboot'
        }

        self._on_vdi_start = on_vdi_start
        self._on_vdi_configured = on_vdi_configured
        self._rerun_on_reboot = rerun_on_reboot

    def to_ddb_dict(self):
        """
        Convert this ScriptEvents instance to DynamoDB dictionary format.
        
        Uses the ScriptEventsSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return scriptevents_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create ScriptEvents instance from DynamoDB dictionary.
        
        Uses the ScriptEventsSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            ScriptEvents instance
        """
        api_data = scriptevents_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'ScriptEvents':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScriptEvents of this ScriptEvents.  # noqa: E501
        :rtype: ScriptEvents
        """
        return util.deserialize_model(dikt, cls)

    @property
    def on_vdi_start(self) -> List[Script]:
        """Gets the on_vdi_start of this ScriptEvents.

        Scripts to run on VDI start  # noqa: E501

        :return: The on_vdi_start of this ScriptEvents.
        :rtype: List[Script]
        """
        return self._on_vdi_start

    @on_vdi_start.setter
    def on_vdi_start(self, on_vdi_start: List[Script]):
        """Sets the on_vdi_start of this ScriptEvents.

        Scripts to run on VDI start  # noqa: E501

        :param on_vdi_start: The on_vdi_start of this ScriptEvents.
        :type on_vdi_start: List[Script]
        """

        self._on_vdi_start = on_vdi_start

    @property
    def on_vdi_configured(self) -> List[Script]:
        """Gets the on_vdi_configured of this ScriptEvents.

        Scripts to run on VDI configured  # noqa: E501

        :return: The on_vdi_configured of this ScriptEvents.
        :rtype: List[Script]
        """
        return self._on_vdi_configured

    @on_vdi_configured.setter
    def on_vdi_configured(self, on_vdi_configured: List[Script]):
        """Sets the on_vdi_configured of this ScriptEvents.

        Scripts to run on VDI configured  # noqa: E501

        :param on_vdi_configured: The on_vdi_configured of this ScriptEvents.
        :type on_vdi_configured: List[Script]
        """

        self._on_vdi_configured = on_vdi_configured

    @property
    def rerun_on_reboot(self) -> bool:
        """Gets the rerun_on_reboot of this ScriptEvents.

        Whether to rerun scripts on reboot  # noqa: E501

        :return: The rerun_on_reboot of this ScriptEvents.
        :rtype: bool
        """
        return self._rerun_on_reboot

    @rerun_on_reboot.setter
    def rerun_on_reboot(self, rerun_on_reboot: bool):
        """Sets the rerun_on_reboot of this ScriptEvents.

        Whether to rerun scripts on reboot  # noqa: E501

        :param rerun_on_reboot: The rerun_on_reboot of this ScriptEvents.
        :type rerun_on_reboot: bool
        """

        self._rerun_on_reboot = rerun_on_reboot
