#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.script_serializer import script_serializer


class Script(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, script_location=None, arguments=None):  # noqa: E501
        """Script - a model defined in OpenAPI

        :param script_location: The script_location of this Script.  # noqa: E501
        :type script_location: str
        :param arguments: The arguments of this Script.  # noqa: E501
        :type arguments: List[str]
        """
        self.openapi_types = {
            'script_location': str,
            'arguments': List[str]
        }

        self.attribute_map = {
            'script_location': 'script_location',
            'arguments': 'arguments'
        }

        self._script_location = script_location
        self._arguments = arguments

    def to_ddb_dict(self):
        """
        Convert this Script instance to DynamoDB dictionary format.
        
        Uses the ScriptSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return script_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create Script instance from DynamoDB dictionary.
        
        Uses the ScriptSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            Script instance
        """
        api_data = script_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'Script':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Script of this Script.  # noqa: E501
        :rtype: Script
        """
        return util.deserialize_model(dikt, cls)

    @property
    def script_location(self) -> str:
        """Gets the script_location of this Script.

        Location of the script. Supported formats: S3 URI (s3://bucket/script.sh), HTTPS URL (https://example.com/script.sh), or local file (file:///path/to/script.sh)  # noqa: E501

        :return: The script_location of this Script.
        :rtype: str
        """
        return self._script_location

    @script_location.setter
    def script_location(self, script_location: str):
        """Sets the script_location of this Script.

        Location of the script. Supported formats: S3 URI (s3://bucket/script.sh), HTTPS URL (https://example.com/script.sh), or local file (file:///path/to/script.sh)  # noqa: E501

        :param script_location: The script_location of this Script.
        :type script_location: str
        """

        self._script_location = script_location

    @property
    def arguments(self) -> List[str]:
        """Gets the arguments of this Script.

        Arguments to pass to the script  # noqa: E501

        :return: The arguments of this Script.
        :rtype: List[str]
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments: List[str]):
        """Sets the arguments of this Script.

        Arguments to pass to the script  # noqa: E501

        :param arguments: The arguments of this Script.
        :type arguments: List[str]
        """

        self._arguments = arguments
