#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.string_value_serializer import stringvalue_serializer


class StringValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, string_value=None):  # noqa: E501
        """StringValue - a model defined in OpenAPI

        :param string_value: The string_value of this StringValue.  # noqa: E501
        :type string_value: str
        """
        self.openapi_types = {
            'string_value': str
        }

        self.attribute_map = {
            'string_value': 'stringValue'
        }

        self._string_value = string_value

    def to_ddb_dict(self):
        """
        Convert this StringValue instance to DynamoDB dictionary format.
        
        Uses the StringValueSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return stringvalue_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create StringValue instance from DynamoDB dictionary.
        
        Uses the StringValueSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            StringValue instance
        """
        api_data = stringvalue_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'StringValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The stringValue of this StringValue.  # noqa: E501
        :rtype: StringValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def string_value(self) -> str:
        """Gets the string_value of this StringValue.


        :return: The string_value of this StringValue.
        :rtype: str
        """
        return self._string_value

    @string_value.setter
    def string_value(self, string_value: str):
        """Sets the string_value of this StringValue.


        :param string_value: The string_value of this StringValue.
        :type string_value: str
        """
        if string_value is None:
            raise ValueError("Invalid value for `string_value`, must not be `None`")  # noqa: E501

        self._string_value = string_value
