#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_session_permission import VirtualDesktopSessionPermission
from datamodel import util

from datamodel.models.virtual_desktop_session_permission import VirtualDesktopSessionPermission  # noqa: E501

class UpdateSessionPermissionsRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, create=None, update=None, delete=None):  # noqa: E501
        """UpdateSessionPermissionsRequestContent - a model defined in OpenAPI

        :param create: The create of this UpdateSessionPermissionsRequestContent.  # noqa: E501
        :type create: List[VirtualDesktopSessionPermission]
        :param update: The update of this UpdateSessionPermissionsRequestContent.  # noqa: E501
        :type update: List[VirtualDesktopSessionPermission]
        :param delete: The delete of this UpdateSessionPermissionsRequestContent.  # noqa: E501
        :type delete: List[VirtualDesktopSessionPermission]
        """
        self.openapi_types = {
            'create': List[VirtualDesktopSessionPermission],
            'update': List[VirtualDesktopSessionPermission],
            'delete': List[VirtualDesktopSessionPermission]
        }

        self.attribute_map = {
            'create': 'create',
            'update': 'update',
            'delete': 'delete'
        }

        self._create = create
        self._update = update
        self._delete = delete

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateSessionPermissionsRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateSessionPermissionsRequestContent of this UpdateSessionPermissionsRequestContent.  # noqa: E501
        :rtype: UpdateSessionPermissionsRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def create(self) -> List[VirtualDesktopSessionPermission]:
        """Gets the create of this UpdateSessionPermissionsRequestContent.

        List of session permissions to create  # noqa: E501

        :return: The create of this UpdateSessionPermissionsRequestContent.
        :rtype: List[VirtualDesktopSessionPermission]
        """
        return self._create

    @create.setter
    def create(self, create: List[VirtualDesktopSessionPermission]):
        """Sets the create of this UpdateSessionPermissionsRequestContent.

        List of session permissions to create  # noqa: E501

        :param create: The create of this UpdateSessionPermissionsRequestContent.
        :type create: List[VirtualDesktopSessionPermission]
        """

        self._create = create

    @property
    def update(self) -> List[VirtualDesktopSessionPermission]:
        """Gets the update of this UpdateSessionPermissionsRequestContent.

        List of session permissions to update  # noqa: E501

        :return: The update of this UpdateSessionPermissionsRequestContent.
        :rtype: List[VirtualDesktopSessionPermission]
        """
        return self._update

    @update.setter
    def update(self, update: List[VirtualDesktopSessionPermission]):
        """Sets the update of this UpdateSessionPermissionsRequestContent.

        List of session permissions to update  # noqa: E501

        :param update: The update of this UpdateSessionPermissionsRequestContent.
        :type update: List[VirtualDesktopSessionPermission]
        """

        self._update = update

    @property
    def delete(self) -> List[VirtualDesktopSessionPermission]:
        """Gets the delete of this UpdateSessionPermissionsRequestContent.

        List of session permissions to delete  # noqa: E501

        :return: The delete of this UpdateSessionPermissionsRequestContent.
        :rtype: List[VirtualDesktopSessionPermission]
        """
        return self._delete

    @delete.setter
    def delete(self, delete: List[VirtualDesktopSessionPermission]):
        """Sets the delete of this UpdateSessionPermissionsRequestContent.

        List of session permissions to delete  # noqa: E501

        :param delete: The delete of this UpdateSessionPermissionsRequestContent.
        :type delete: List[VirtualDesktopSessionPermission]
        """

        self._delete = delete
