#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_session_permission import VirtualDesktopSessionPermission
from datamodel import util

from datamodel.models.virtual_desktop_session_permission import VirtualDesktopSessionPermission  # noqa: E501

class UpdateSessionPermissionsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, permissions=None):  # noqa: E501
        """UpdateSessionPermissionsResponseContent - a model defined in OpenAPI

        :param permissions: The permissions of this UpdateSessionPermissionsResponseContent.  # noqa: E501
        :type permissions: List[VirtualDesktopSessionPermission]
        """
        self.openapi_types = {
            'permissions': List[VirtualDesktopSessionPermission]
        }

        self.attribute_map = {
            'permissions': 'permissions'
        }

        self._permissions = permissions

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateSessionPermissionsResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateSessionPermissionsResponseContent of this UpdateSessionPermissionsResponseContent.  # noqa: E501
        :rtype: UpdateSessionPermissionsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def permissions(self) -> List[VirtualDesktopSessionPermission]:
        """Gets the permissions of this UpdateSessionPermissionsResponseContent.

        List of session permissions that where create/updated  # noqa: E501

        :return: The permissions of this UpdateSessionPermissionsResponseContent.
        :rtype: List[VirtualDesktopSessionPermission]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions: List[VirtualDesktopSessionPermission]):
        """Sets the permissions of this UpdateSessionPermissionsResponseContent.

        List of session permissions that where create/updated  # noqa: E501

        :param permissions: The permissions of this UpdateSessionPermissionsResponseContent.
        :type permissions: List[VirtualDesktopSessionPermission]
        """

        self._permissions = permissions
