#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.virtual_desktop_session import VirtualDesktopSession
from datamodel import util

from datamodel.models.virtual_desktop_session import VirtualDesktopSession  # noqa: E501

class UpdateSessionRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session=None):  # noqa: E501
        """UpdateSessionRequestContent - a model defined in OpenAPI

        :param session: The session of this UpdateSessionRequestContent.  # noqa: E501
        :type session: VirtualDesktopSession
        """
        self.openapi_types = {
            'session': VirtualDesktopSession
        }

        self.attribute_map = {
            'session': 'session'
        }

        self._session = session

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateSessionRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateSessionRequestContent of this UpdateSessionRequestContent.  # noqa: E501
        :rtype: UpdateSessionRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session(self) -> VirtualDesktopSession:
        """Gets the session of this UpdateSessionRequestContent.


        :return: The session of this UpdateSessionRequestContent.
        :rtype: VirtualDesktopSession
        """
        return self._session

    @session.setter
    def session(self, session: VirtualDesktopSession):
        """Sets the session of this UpdateSessionRequestContent.


        :param session: The session of this UpdateSessionRequestContent.
        :type session: VirtualDesktopSession
        """
        if session is None:
            raise ValueError("Invalid value for `session`, must not be `None`")  # noqa: E501

        self._session = session
