#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.virtual_desktop_session_connection_serializer import virtualdesktopsessionconnection_serializer


class VirtualDesktopSessionConnection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, idea_session_id=None, idea_session_owner=None, endpoint=None, web_url_path=None, access_token=None, failure_reason=None):  # noqa: E501
        """VirtualDesktopSessionConnection - a model defined in OpenAPI

        :param idea_session_id: The idea_session_id of this VirtualDesktopSessionConnection.  # noqa: E501
        :type idea_session_id: str
        :param idea_session_owner: The idea_session_owner of this VirtualDesktopSessionConnection.  # noqa: E501
        :type idea_session_owner: str
        :param endpoint: The endpoint of this VirtualDesktopSessionConnection.  # noqa: E501
        :type endpoint: str
        :param web_url_path: The web_url_path of this VirtualDesktopSessionConnection.  # noqa: E501
        :type web_url_path: str
        :param access_token: The access_token of this VirtualDesktopSessionConnection.  # noqa: E501
        :type access_token: str
        :param failure_reason: The failure_reason of this VirtualDesktopSessionConnection.  # noqa: E501
        :type failure_reason: str
        """
        self.openapi_types = {
            'idea_session_id': str,
            'idea_session_owner': str,
            'endpoint': str,
            'web_url_path': str,
            'access_token': str,
            'failure_reason': str
        }

        self.attribute_map = {
            'idea_session_id': 'idea-session-id',
            'idea_session_owner': 'idea-session-owner',
            'endpoint': 'endpoint',
            'web_url_path': 'web-url-path',
            'access_token': 'access-token',
            'failure_reason': 'failure-reason'
        }

        self._idea_session_id = idea_session_id
        self._idea_session_owner = idea_session_owner
        self._endpoint = endpoint
        self._web_url_path = web_url_path
        self._access_token = access_token
        self._failure_reason = failure_reason

    def to_ddb_dict(self):
        """
        Convert this VirtualDesktopSessionConnection instance to DynamoDB dictionary format.
        
        Uses the VirtualDesktopSessionConnectionSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return virtualdesktopsessionconnection_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create VirtualDesktopSessionConnection instance from DynamoDB dictionary.
        
        Uses the VirtualDesktopSessionConnectionSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            VirtualDesktopSessionConnection instance
        """
        api_data = virtualdesktopsessionconnection_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopSessionConnection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopSessionConnection of this VirtualDesktopSessionConnection.  # noqa: E501
        :rtype: VirtualDesktopSessionConnection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def idea_session_id(self) -> str:
        """Gets the idea_session_id of this VirtualDesktopSessionConnection.

        IDEA session identifier  # noqa: E501

        :return: The idea_session_id of this VirtualDesktopSessionConnection.
        :rtype: str
        """
        return self._idea_session_id

    @idea_session_id.setter
    def idea_session_id(self, idea_session_id: str):
        """Sets the idea_session_id of this VirtualDesktopSessionConnection.

        IDEA session identifier  # noqa: E501

        :param idea_session_id: The idea_session_id of this VirtualDesktopSessionConnection.
        :type idea_session_id: str
        """
        if idea_session_id is None:
            raise ValueError("Invalid value for `idea_session_id`, must not be `None`")  # noqa: E501
        if idea_session_id is not None and len(idea_session_id) < 1:
            raise ValueError("Invalid value for `idea_session_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._idea_session_id = idea_session_id

    @property
    def idea_session_owner(self) -> str:
        """Gets the idea_session_owner of this VirtualDesktopSessionConnection.

        IDEA session owner  # noqa: E501

        :return: The idea_session_owner of this VirtualDesktopSessionConnection.
        :rtype: str
        """
        return self._idea_session_owner

    @idea_session_owner.setter
    def idea_session_owner(self, idea_session_owner: str):
        """Sets the idea_session_owner of this VirtualDesktopSessionConnection.

        IDEA session owner  # noqa: E501

        :param idea_session_owner: The idea_session_owner of this VirtualDesktopSessionConnection.
        :type idea_session_owner: str
        """
        if idea_session_owner is None:
            raise ValueError("Invalid value for `idea_session_owner`, must not be `None`")  # noqa: E501
        if idea_session_owner is not None and len(idea_session_owner) < 1:
            raise ValueError("Invalid value for `idea_session_owner`, length must be greater than or equal to `1`")  # noqa: E501

        self._idea_session_owner = idea_session_owner

    @property
    def endpoint(self) -> str:
        """Gets the endpoint of this VirtualDesktopSessionConnection.

        Connection endpoint URL  # noqa: E501

        :return: The endpoint of this VirtualDesktopSessionConnection.
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint: str):
        """Sets the endpoint of this VirtualDesktopSessionConnection.

        Connection endpoint URL  # noqa: E501

        :param endpoint: The endpoint of this VirtualDesktopSessionConnection.
        :type endpoint: str
        """

        self._endpoint = endpoint

    @property
    def web_url_path(self) -> str:
        """Gets the web_url_path of this VirtualDesktopSessionConnection.

        Web URL path for the session  # noqa: E501

        :return: The web_url_path of this VirtualDesktopSessionConnection.
        :rtype: str
        """
        return self._web_url_path

    @web_url_path.setter
    def web_url_path(self, web_url_path: str):
        """Sets the web_url_path of this VirtualDesktopSessionConnection.

        Web URL path for the session  # noqa: E501

        :param web_url_path: The web_url_path of this VirtualDesktopSessionConnection.
        :type web_url_path: str
        """

        self._web_url_path = web_url_path

    @property
    def access_token(self) -> str:
        """Gets the access_token of this VirtualDesktopSessionConnection.

        Access token for the session connection  # noqa: E501

        :return: The access_token of this VirtualDesktopSessionConnection.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this VirtualDesktopSessionConnection.

        Access token for the session connection  # noqa: E501

        :param access_token: The access_token of this VirtualDesktopSessionConnection.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def failure_reason(self) -> str:
        """Gets the failure_reason of this VirtualDesktopSessionConnection.

        Failure reason if connection could not be established  # noqa: E501

        :return: The failure_reason of this VirtualDesktopSessionConnection.
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason: str):
        """Sets the failure_reason of this VirtualDesktopSessionConnection.

        Failure reason if connection could not be established  # noqa: E501

        :param failure_reason: The failure_reason of this VirtualDesktopSessionConnection.
        :type failure_reason: str
        """

        self._failure_reason = failure_reason
