#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util
from datamodel.serializers.virtual_desktop_session_screenshot_serializer import virtualdesktopsessionscreenshot_serializer


class VirtualDesktopSessionScreenshot(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, idea_session_id=None, format=None, data=None, created_on=None, failure_reason=None):  # noqa: E501
        """VirtualDesktopSessionScreenshot - a model defined in OpenAPI

        :param idea_session_id: The idea_session_id of this VirtualDesktopSessionScreenshot.  # noqa: E501
        :type idea_session_id: str
        :param format: The format of this VirtualDesktopSessionScreenshot.  # noqa: E501
        :type format: str
        :param data: The data of this VirtualDesktopSessionScreenshot.  # noqa: E501
        :type data: str
        :param created_on: The created_on of this VirtualDesktopSessionScreenshot.  # noqa: E501
        :type created_on: str
        :param failure_reason: The failure_reason of this VirtualDesktopSessionScreenshot.  # noqa: E501
        :type failure_reason: str
        """
        self.openapi_types = {
            'idea_session_id': str,
            'format': str,
            'data': str,
            'created_on': str,
            'failure_reason': str
        }

        self.attribute_map = {
            'idea_session_id': 'idea_session_id',
            'format': 'format',
            'data': 'data',
            'created_on': 'created_on',
            'failure_reason': 'failure_reason'
        }

        self._idea_session_id = idea_session_id
        self._format = format
        self._data = data
        self._created_on = created_on
        self._failure_reason = failure_reason

    def to_ddb_dict(self):
        """
        Convert this VirtualDesktopSessionScreenshot instance to DynamoDB dictionary format.
        
        Uses the VirtualDesktopSessionScreenshotSerializer to handle API -> DDB transformation.
        Override the serializer methods to customize conversion logic.
        
        Returns:
            Dictionary suitable for DynamoDB storage
        """
        return virtualdesktopsessionscreenshot_serializer.to_ddb_dict(self)
    
    @classmethod
    def from_ddb_dict(cls, ddb_data):
        """
        Create VirtualDesktopSessionScreenshot instance from DynamoDB dictionary.
        
        Uses the VirtualDesktopSessionScreenshotSerializer to handle DDB -> API transformation.
        Override the serializer methods to customize conversion logic.
        
        Args:
            ddb_data: Dictionary from DynamoDB record
            
        Returns:
            VirtualDesktopSessionScreenshot instance
        """
        api_data = virtualdesktopsessionscreenshot_serializer.from_ddb_dict(ddb_data)
        return cls.from_dict(api_data)

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopSessionScreenshot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopSessionScreenshot of this VirtualDesktopSessionScreenshot.  # noqa: E501
        :rtype: VirtualDesktopSessionScreenshot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def idea_session_id(self) -> str:
        """Gets the idea_session_id of this VirtualDesktopSessionScreenshot.

        IDEA session identifier  # noqa: E501

        :return: The idea_session_id of this VirtualDesktopSessionScreenshot.
        :rtype: str
        """
        return self._idea_session_id

    @idea_session_id.setter
    def idea_session_id(self, idea_session_id: str):
        """Sets the idea_session_id of this VirtualDesktopSessionScreenshot.

        IDEA session identifier  # noqa: E501

        :param idea_session_id: The idea_session_id of this VirtualDesktopSessionScreenshot.
        :type idea_session_id: str
        """
        if idea_session_id is None:
            raise ValueError("Invalid value for `idea_session_id`, must not be `None`")  # noqa: E501
        if idea_session_id is not None and len(idea_session_id) < 1:
            raise ValueError("Invalid value for `idea_session_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._idea_session_id = idea_session_id

    @property
    def format(self) -> str:
        """Gets the format of this VirtualDesktopSessionScreenshot.

        Image format. Supported formats: jpeg, png  # noqa: E501

        :return: The format of this VirtualDesktopSessionScreenshot.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format: str):
        """Sets the format of this VirtualDesktopSessionScreenshot.

        Image format. Supported formats: jpeg, png  # noqa: E501

        :param format: The format of this VirtualDesktopSessionScreenshot.
        :type format: str
        """

        self._format = format

    @property
    def data(self) -> str:
        """Gets the data of this VirtualDesktopSessionScreenshot.

        Base64 encoded image data  # noqa: E501

        :return: The data of this VirtualDesktopSessionScreenshot.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this VirtualDesktopSessionScreenshot.

        Base64 encoded image data  # noqa: E501

        :param data: The data of this VirtualDesktopSessionScreenshot.
        :type data: str
        """

        self._data = data

    @property
    def created_on(self) -> str:
        """Gets the created_on of this VirtualDesktopSessionScreenshot.

        Timestamp when the screenshot was created  # noqa: E501

        :return: The created_on of this VirtualDesktopSessionScreenshot.
        :rtype: str
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on: str):
        """Sets the created_on of this VirtualDesktopSessionScreenshot.

        Timestamp when the screenshot was created  # noqa: E501

        :param created_on: The created_on of this VirtualDesktopSessionScreenshot.
        :type created_on: str
        """

        self._created_on = created_on

    @property
    def failure_reason(self) -> str:
        """Gets the failure_reason of this VirtualDesktopSessionScreenshot.

        Failure reason if the screenshot could not be retrieved  # noqa: E501

        :return: The failure_reason of this VirtualDesktopSessionScreenshot.
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason: str):
        """Sets the failure_reason of this VirtualDesktopSessionScreenshot.

        Failure reason if the screenshot could not be retrieved  # noqa: E501

        :param failure_reason: The failure_reason of this VirtualDesktopSessionScreenshot.
        :type failure_reason: str
        """

        self._failure_reason = failure_reason
