#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
#  and limitations under the License.

GENERAL_ERROR = 'GENERAL_ERROR'
APP_NOT_FOUND = 'APP_NOT_FOUND'
CONFIG_ERROR = 'CONFIG_ERROR'
CONFIG_PARSING_FAILED = 'CONFIG_PARSING_FAILED'
CONFIG_VALIDATION_FAILED = 'CONFIG_VALIDATION_FAILED'
CONFIG_KEY_NOT_FOUND = 'CONFIG_KEY_NOT_FOUND'
CONFIG_TYPE_ERROR = 'CONFIG_TYPE_ERROR'
CONFIG_SUBSTITUTION_FAILED = 'CONFIG_SUBSTITUTION_FAILED'
GENERAL_FAILURE = GENERAL_ERROR
INVALID_PARAMS = 'INVALID_PARAMS'
MEMORY_FORMAT_PARSING_FAILED = 'MEMORY_FORMAT_PARSING_FAILED'
AWS_CLIENT_NOT_SUPPORTED = 'AWS_CLIENT_NOT_SUPPORTED'
EC2_DRY_RUN_FAILED = 'EC2_DRY_RUN_FAILED'
CAPACITY_UNAVAILABLE = 'CAPACITY_UNAVAILABLE'
PERMISSION_ERROR = 'PERMISSION_ERROR'
STACK_ID_NOT_FOUND = 'STACK_ID_NOT_FOUND'
MODULE_ID_NOT_FOUND = 'MODULE_ID_NOT_FOUND'
FAILED_TO_CHECK_EXISTING_CAPACITY = 'FAILED_TO_CHECK_EXISTING_CAPACITY'
VALIDATION_FAILED = 'VALIDATION_FAILED'
EMAIL_NOTIFICATION_FAILED = 'EMAIL_NOTIFICATION_FAILED'
SOCKET_TIMEOUT = 'SOCKET_TIMEOUT'
METRICS_PROVIDER_NOT_FOUND = 'METRICS_PROVIDER_NOT_FOUND'
EC2_INSTANCE_METADATA_FAILED = 'EC2_INSTANCE_METADATA_FAILED'
INVALID_NODE_TYPE = 'INVALID_NODE_TYPE'
INVALID_EC2_INSTANCE_TYPE = 'INVALID_EC2_INSTANCE_TYPE'
DESCRIBE_RESERVED_INSTANCES_FAILED = 'DESCRIBE_RESERVED_INSTANCES_FAILED'
SERVICE_QUOTA_NOT_FOUND = 'SERVICE_QUOTA_NOT_FOUND'
SERVICE_QUOTA_NOT_AVAILABLE = 'SERVICE_QUOTA_NOT_AVAILABLE'
NOT_ENOUGH_LICENSES = 'NOT_ENOUGH_LICENSES'
SCHEDULER_ERROR = 'SCHEDULER_ERROR'
SCHEDULER_JOB_FINISHED = 'SCHEDULER_JOB_FINISHED'
SCHEDULER_NODE_BUSY = 'SCHEDULER_NODE_BUSY'
SCHEDULER_QUEUE_ALREADY_EXISTS = 'SCHEDULER_QUEUE_ALREADY_EXISTS'
SCHEDULER_QUEUE_BUSY = 'SCHEDULER_QUEUE_BUSY'
SCHEDULER_QUEUE_NOT_FOUND = 'SCHEDULER_QUEUE_NOT_FOUND'
SCHEDULER_QUEUE_PROFILE_DISABLED = 'SCHEDULER_QUEUE_PROFILE_DISABLED'
SCHEDULER_QUEUE_PROFILE_NOT_FOUND = 'SCHEDULER_QUEUE_PROFILE_NOT_FOUND'
SCHEDULER_INVALID_LICENSE_RESOURCE_CONFIGURATION = 'INVALID_LICENSE_RESOURCE_CONFIGURATION'
EC2_RESERVED_INSTANCES_NOT_PURCHASED = 'EC2_RESERVED_INSTANCES_NOT_PURCHASED'
EC2_RESERVED_INSTANCES_NOT_AVAILABLE = 'EC2_RESERVED_INSTANCES_NOT_AVAILABLE'
NOT_AUTHORIZED_QUEUE_ACL = 'NOT_AUTHORIZED_QUEUE_ACL'
BUDGET_NOT_FOUND = 'BUDGET_NOT_FOUND'
BUDGETS_PROJECT_IS_REQUIRED = 'BUDGETS_PROJECT_IS_REQUIRED'
BUDGETS_USER_NOT_CONFIGURED = 'BUDGETS_USER_NOT_CONFIGURED'
BUDGETS_LIMIT_EXCEEDED = 'BUDGET_LIMIT_EXCEEDED'
SHARED_CAPACITY_UNAVAILABLE = 'SHARED_CAPACITY_UNAVAILABLE'
SHARED_CAPACITY_INVALID_QUEUE = 'SHARED_CAPACITY_INVALID_QUEUE'
SHARED_CAPACITY_MISMATCH = 'SHARED_CAPACITY_MISMATCH'
CLOUDFORMATION_STACK_BUILDER_FAILED = 'CLOUDFORMATION_STACK_BUILDER_FAILED'
SOCA_SCHEDULER_INVALID_JOB = 'SOCA_SCHEDULER_INVALID_JOB'
SPOT_FLEET_CAPACITY_UPDATE_IN_PROGRESS = 'SPOT_FLEET_CAPACITY_UPDATE_IN_PROGRESS'
MAX_PROVISIONED_INSTANCES_LIMIT = 'MAX_PROVISIONED_INSTANCES_LIMIT'
LOCALE_NOT_FOUND_OR_INVALID = 'LOCALE_NOT_FOUND_OR_INVALID'
INVALID_LOCALE_CONFIGURATION = 'INVALID_LOCALE_CONFIGURATION'
JOB_PROVISIONING_NOT_READY = 'JOB_PROVISIONING_NOT_READY'
EXCEEDED_MAX_RETRIES = 'EXCEEDED_MAX_RETRIES'
NOT_SUPPORTED = 'NOT_SUPPORTED'
DOCUMENT_STORE_CONFIG_ERROR = 'DOCUMENT_STORE_CONFIG_ERROR'
NOT_AUTHORIZED = 'NOT_AUTHORIZED'
USER_INPUT_FLOW_ERROR = 'USER_INPUT_FLOW_ERROR'
USER_INPUT_FLOW_INTERRUPT = 'USER_INPUT_FLOW_INTERRUPT'
INPUT_PARAM_NOT_DEFINED = 'INPUT_PARAM_NOT_DEFINED'
INPUT_PARAM_SPEC_NOT_FOUND = 'INPUT_PARAM_SPEC_FILE_NOT_FOUND'
INPUT_PROMPT_NOT_FOUND = 'INPUT_PROMPT_NOT_FOUND'
AWS_MISSING_PERMISSIONS = 'AWS_MISSING_PERMISSIONS'
INSTALLER_MISSING_PERMISSIONS = AWS_MISSING_PERMISSIONS
INSTALLATION_IN_PROGRESS = 'INSTALLATION_IN_PROGRESS'
INSTALLATION_FAILED = 'INSTALLATION_FAILED'
INSTALLATION_INTERRUPTED = 'INSTALLATION_INTERRUPTED'
INSTALLER_PARAM_VALIDATION_FAILED = 'INSTALLER_PARAM_VALIDATION_FAILED'
INSTALLER_CONFIG_NOT_READY = 'INSTALLER_CONFIG_NOT_READY'
AWS_ENDPOINTS_CONFIG_NOT_FOUND = 'AWS_ENDPOINTS_CONFIG_NOT_FOUND'
AWS_ENDPOINTS_PARTITION_NOT_FOUND = 'AWS_ENDPOINTS_PARTITION_NOT_FOUND'
AWS_CLIENT_PROVIDER_NOT_INITIALIZED = 'AWS_CLIENT_PROVIDER_NOT_INITIALIZED'
CLI_ERROR = 'CLI_ERROR'
AWS_CLI_NOT_INSTALLED = 'AWS_CLI_NOT_INSTALLED'
PORT_IS_ALREADY_IN_USE = 'PORT_IS_ALREADY_IN_USE'
FILE_NOT_FOUND = 'FILE_NOT_FOUND'
INVALID_SEMVER = 'INVALID_SEMVER'
RETRY_JOB_PROVISIONING = 'RETRY_JOB_PROVISIONING'
JOB_SUBMISSION_FAILED = 'JOB_SUBMISSION_FAILED'
JOB_NOT_FOUND = 'JOB_NOT_FOUND'
CONNECTION_ERROR = 'CONNECTION_ERROR'
GID_NOT_FOUND = 'GID_NOT_FOUND'
UID_AND_GID_NOT_FOUND = 'UID_AND_GID_NOT_FOUND'
USER_NOT_AVAILABLE = 'USER_NOT_AVAILABLE'

SERVER_IS_SHUTTING_DOWN = 'SERVER_IS_SHUTTING_DOWN'

AUTH_MULTIPLE_USERS_FOUND = 'MULTIPLE_USERS_FOUND'
AUTH_USER_IS_DISABLED = 'USER_IS_DISABLED'
AUTH_GROUP_IS_DISABLED = 'GROUP_IS_DISABLED'
AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND'
AUTH_USER_ALREADY_EXISTS = 'AUTH_USER_ALREADY_EXISTS'
AUTH_GROUP_ALREADY_EXISTS = 'AUTH_GROUP_ALREADY_EXISTS'
AUTH_GROUP_NOT_FOUND = 'AUTH_GROUP_NOT_FOUND'
AUTH_MAX_UID_LIMIT = 'AUTH_MAX_UID_LIMIT'
AUTH_MAX_GID_LIMIT = 'AUTH_MAX_GID_LIMIT'
AUTH_UID_ALREADY_IN_USE = 'AUTH_UID_ALREADY_IN_USE'
AUTH_GID_ALREADY_IN_USE = 'AUTH_GID_ALREADY_IN_USE'
AUTH_JWK_NOT_INITIALIZED = 'AUTH_JWK_NOT_INITIALIZED'
AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED'
AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID'
AUTH_PASSWORD_RESET_REQUIRED = 'AUTH_PASSWORD_RESET_REQUIRED'
AUTH_INVALID_OPERATION = 'AUTH_INVALID_OPERATION'
AUTH_TOKEN_REVOCATION_FAILED = 'AUTH_TOKEN_REVOCATION_FAILED'

UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS'

PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND'

ROLE_ASSIGNMENT_NOT_FOUND = 'ROLE_ASSIGNMENT_NOT_FOUND'
ROLE_ASSIGNMENT_RESOURCE_KEY_NOT_FOUND = 'ROLE_ASSIGNMENT_RESOURCE_KEY_NOT_FOUND'

ROLE_NOT_FOUND = 'ROLE_NOT_FOUND'
ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS'

# ------- VIRTUAL DESKTOP ERROR CODES START -------
CREATE_SESSION_FAILED = 'CREATE_SESSION_FAILED'
CREATED_SOFTWARE_STACK_FROM_SESSION_FAILED = 'CREATED_SOFTWARE_STACK_FROM_SESSION_FAILED'
SESSION_CONNECTION_ERROR = 'SESSION_CONNECTION_ERROR'
UPDATE_SESSION_FAILED = 'UPDATE_SESSION_FAILED'
DELETE_SESSION_FAILED = 'DELETE_SESSION_FAILED'
INVALID_SESSION = 'INVALID_SESSION'
DO_NOT_DELETE_MESSAGE = 'DO_NOT_DELETE_MESSAGE'
MESSAGE_SOURCE_VALIDATION_FAILED = 'MESSAGE_SOURCE_VALIDATION_FAILED'
# ------- VIRTUAL DESKTOP ERROR CODES END -------

CLUSTER_CONFIG_NOT_INITIALIZED = 'CLUSTER_CONFIG_NOT_INITIALIZED'

FILE_BROWSER_NOT_A_TEXT_FILE = 'NOT_A_TEXT_FILE'
FILE_BROWSER_TAIL_THROTTLE = 'TAIL_THROTTLE'

EMAIL_TEMPLATE_NOT_FOUND = 'EMAIL_TEMPLATE_NOT_FOUND'

AD_AUTOMATION_PRESET_COMPUTER_FAILED = 'AD_AUTOMATION_PRESET_COMPUTER_FAILED'
AD_AUTOMATION_PRESET_COMPUTER_RETRY = 'AD_AUTOMATION_PRESET_COMPUTER_RETRY'

# ------- FILE SYSTEM ERROR CODES START -------
NO_SHARED_FILESYSTEM_FOUND = 'NO_SHARED_FILESYSTEM_FOUND'
FILESYSTEM_NOT_FOUND = 'FILESYSTEM_NOT_FOUND'
FILESYSTEM_ALREADY_ONBOARDED = "FILESYSTEM_ALREADY_ONBOARDED"
FILESYSTEM_NOT_IN_VPC = "FILESYSTEM_NOT_IN_VPC"
FILESYSTEM_MOUNT_POINT_COLLISION = "FILESYSTEM_MOUNT_POINT_COLLISION"
# ------- FILE SYSTEM ERROR CODES END -------

# Integration Tests
INTEGRATION_TEST_FAILED = 'INTEGRATION_TEST_FAILED'

# ------- APPLY SNAPSHOT ERROR CODES START -------
TABLE_IMPORT_FAILED = "TABLE_IMPORT_FAILED"
TABLE_MERGE_FAILED = "TABLE_MERGE_FAILED"
TABLE_ROLLBACK_FAILED = "TABLE_ROLLBACK_FAILED"
# ------- APPLY SNAPSHOT ERROR CODES END -------
