#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.describe_sessions_successful_response import DescribeSessionsSuccessfulResponse
from datamodel.models.describe_sessions_unsuccessful_response import DescribeSessionsUnsuccessfulResponse
from datamodel import util

from datamodel.models.describe_sessions_successful_response import DescribeSessionsSuccessfulResponse  # noqa: E501
from datamodel.models.describe_sessions_unsuccessful_response import DescribeSessionsUnsuccessfulResponse  # noqa: E501

class DescribeSessionsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, successful_list=None, unsuccessful_list=None):  # noqa: E501
        """DescribeSessionsResponseContent - a model defined in OpenAPI

        :param successful_list: The successful_list of this DescribeSessionsResponseContent.  # noqa: E501
        :type successful_list: List[DescribeSessionsSuccessfulResponse]
        :param unsuccessful_list: The unsuccessful_list of this DescribeSessionsResponseContent.  # noqa: E501
        :type unsuccessful_list: List[DescribeSessionsUnsuccessfulResponse]
        """
        self.openapi_types = {
            'successful_list': List[DescribeSessionsSuccessfulResponse],
            'unsuccessful_list': List[DescribeSessionsUnsuccessfulResponse]
        }

        self.attribute_map = {
            'successful_list': 'successful_list',
            'unsuccessful_list': 'unsuccessful_list'
        }

        self._successful_list = successful_list
        self._unsuccessful_list = unsuccessful_list

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeSessionsResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeSessionsResponseContent of this DescribeSessionsResponseContent.  # noqa: E501
        :rtype: DescribeSessionsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def successful_list(self) -> List[DescribeSessionsSuccessfulResponse]:
        """Gets the successful_list of this DescribeSessionsResponseContent.

        The array of sessions successfully described  # noqa: E501

        :return: The successful_list of this DescribeSessionsResponseContent.
        :rtype: List[DescribeSessionsSuccessfulResponse]
        """
        return self._successful_list

    @successful_list.setter
    def successful_list(self, successful_list: List[DescribeSessionsSuccessfulResponse]):
        """Sets the successful_list of this DescribeSessionsResponseContent.

        The array of sessions successfully described  # noqa: E501

        :param successful_list: The successful_list of this DescribeSessionsResponseContent.
        :type successful_list: List[DescribeSessionsSuccessfulResponse]
        """
        if successful_list is None:
            raise ValueError("Invalid value for `successful_list`, must not be `None`")  # noqa: E501

        self._successful_list = successful_list

    @property
    def unsuccessful_list(self) -> List[DescribeSessionsUnsuccessfulResponse]:
        """Gets the unsuccessful_list of this DescribeSessionsResponseContent.

        The array of sessions that failed to describe  # noqa: E501

        :return: The unsuccessful_list of this DescribeSessionsResponseContent.
        :rtype: List[DescribeSessionsUnsuccessfulResponse]
        """
        return self._unsuccessful_list

    @unsuccessful_list.setter
    def unsuccessful_list(self, unsuccessful_list: List[DescribeSessionsUnsuccessfulResponse]):
        """Sets the unsuccessful_list of this DescribeSessionsResponseContent.

        The array of sessions that failed to describe  # noqa: E501

        :param unsuccessful_list: The unsuccessful_list of this DescribeSessionsResponseContent.
        :type unsuccessful_list: List[DescribeSessionsUnsuccessfulResponse]
        """
        if unsuccessful_list is None:
            raise ValueError("Invalid value for `unsuccessful_list`, must not be `None`")  # noqa: E501

        self._unsuccessful_list = unsuccessful_list
