#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class DescribeSessionsSuccessfulResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None, num_of_connections=None):  # noqa: E501
        """DescribeSessionsSuccessfulResponse - a model defined in OpenAPI

        :param session_id: The session_id of this DescribeSessionsSuccessfulResponse.  # noqa: E501
        :type session_id: str
        :param num_of_connections: The num_of_connections of this DescribeSessionsSuccessfulResponse.  # noqa: E501
        :type num_of_connections: int
        """
        self.openapi_types = {
            'session_id': str,
            'num_of_connections': int
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'num_of_connections': 'num_of_connections'
        }

        self._session_id = session_id
        self._num_of_connections = num_of_connections

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeSessionsSuccessfulResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeSessionsSuccessfulResponse of this DescribeSessionsSuccessfulResponse.  # noqa: E501
        :rtype: DescribeSessionsSuccessfulResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this DescribeSessionsSuccessfulResponse.

        The session id  # noqa: E501

        :return: The session_id of this DescribeSessionsSuccessfulResponse.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this DescribeSessionsSuccessfulResponse.

        The session id  # noqa: E501

        :param session_id: The session_id of this DescribeSessionsSuccessfulResponse.
        :type session_id: str
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def num_of_connections(self) -> int:
        """Gets the num_of_connections of this DescribeSessionsSuccessfulResponse.

        The number of active connections to the session  # noqa: E501

        :return: The num_of_connections of this DescribeSessionsSuccessfulResponse.
        :rtype: int
        """
        return self._num_of_connections

    @num_of_connections.setter
    def num_of_connections(self, num_of_connections: int):
        """Sets the num_of_connections of this DescribeSessionsSuccessfulResponse.

        The number of active connections to the session  # noqa: E501

        :param num_of_connections: The num_of_connections of this DescribeSessionsSuccessfulResponse.
        :type num_of_connections: int
        """
        if num_of_connections is None:
            raise ValueError("Invalid value for `num_of_connections`, must not be `None`")  # noqa: E501

        self._num_of_connections = num_of_connections
