#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.describe_sessions_request_data import DescribeSessionsRequestData
from datamodel import util

from datamodel.models.describe_sessions_request_data import DescribeSessionsRequestData  # noqa: E501

class DescribeSessionsRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sessions=None):  # noqa: E501
        """DescribeSessionsRequestContent - a model defined in OpenAPI

        :param sessions: The sessions of this DescribeSessionsRequestContent.  # noqa: E501
        :type sessions: List[DescribeSessionsRequestData]
        """
        self.openapi_types = {
            'sessions': List[DescribeSessionsRequestData]
        }

        self.attribute_map = {
            'sessions': 'sessions'
        }

        self._sessions = sessions

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeSessionsRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeSessionsRequestContent of this DescribeSessionsRequestContent.  # noqa: E501
        :rtype: DescribeSessionsRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sessions(self) -> List[DescribeSessionsRequestData]:
        """Gets the sessions of this DescribeSessionsRequestContent.

        Sessions to describe  # noqa: E501

        :return: The sessions of this DescribeSessionsRequestContent.
        :rtype: List[DescribeSessionsRequestData]
        """
        return self._sessions

    @sessions.setter
    def sessions(self, sessions: List[DescribeSessionsRequestData]):
        """Sets the sessions of this DescribeSessionsRequestContent.

        Sessions to describe  # noqa: E501

        :param sessions: The sessions of this DescribeSessionsRequestContent.
        :type sessions: List[DescribeSessionsRequestData]
        """
        if sessions is None:
            raise ValueError("Invalid value for `sessions`, must not be `None`")  # noqa: E501
        if sessions is not None and len(sessions) < 1:
            raise ValueError("Invalid value for `sessions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._sessions = sessions
