#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.auth_result import AuthResult
from datamodel import util

from datamodel.models.auth_result import AuthResult  # noqa: E501

class ExternalAuthResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None, username=None, message=None):  # noqa: E501
        """ExternalAuthResponseContent - a model defined in OpenAPI

        :param result: The result of this ExternalAuthResponseContent.  # noqa: E501
        :type result: AuthResult
        :param username: The username of this ExternalAuthResponseContent.  # noqa: E501
        :type username: str
        :param message: The message of this ExternalAuthResponseContent.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'result': AuthResult,
            'username': str,
            'message': str
        }

        self.attribute_map = {
            'result': 'result',
            'username': 'username',
            'message': 'message'
        }

        self._result = result
        self._username = username
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ExternalAuthResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExternalAuthResponseContent of this ExternalAuthResponseContent.  # noqa: E501
        :rtype: ExternalAuthResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> AuthResult:
        """Gets the result of this ExternalAuthResponseContent.


        :return: The result of this ExternalAuthResponseContent.
        :rtype: AuthResult
        """
        return self._result

    @result.setter
    def result(self, result: AuthResult):
        """Sets the result of this ExternalAuthResponseContent.


        :param result: The result of this ExternalAuthResponseContent.
        :type result: AuthResult
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result

    @property
    def username(self) -> str:
        """Gets the username of this ExternalAuthResponseContent.

        Authenticated username, present when result is 'yes'  # noqa: E501

        :return: The username of this ExternalAuthResponseContent.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this ExternalAuthResponseContent.

        Authenticated username, present when result is 'yes'  # noqa: E501

        :param username: The username of this ExternalAuthResponseContent.
        :type username: str
        """

        self._username = username

    @property
    def message(self) -> str:
        """Gets the message of this ExternalAuthResponseContent.

        Failure message, present when result is 'no'  # noqa: E501

        :return: The message of this ExternalAuthResponseContent.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ExternalAuthResponseContent.

        Failure message, present when result is 'no'  # noqa: E501

        :param message: The message of this ExternalAuthResponseContent.
        :type message: str
        """

        self._message = message
