#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class ExternalAuthRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None, authentication_token=None, client_address=None):  # noqa: E501
        """ExternalAuthRequestContent - a model defined in OpenAPI

        :param session_id: The session_id of this ExternalAuthRequestContent.  # noqa: E501
        :type session_id: str
        :param authentication_token: The authentication_token of this ExternalAuthRequestContent.  # noqa: E501
        :type authentication_token: str
        :param client_address: The client_address of this ExternalAuthRequestContent.  # noqa: E501
        :type client_address: str
        """
        self.openapi_types = {
            'session_id': str,
            'authentication_token': str,
            'client_address': str
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'authentication_token': 'authentication_token',
            'client_address': 'client_address'
        }

        self._session_id = session_id
        self._authentication_token = authentication_token
        self._client_address = client_address

    @classmethod
    def from_dict(cls, dikt) -> 'ExternalAuthRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExternalAuthRequestContent of this ExternalAuthRequestContent.  # noqa: E501
        :rtype: ExternalAuthRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this ExternalAuthRequestContent.

        DCV session ID (always 'console' for auto-created sessions)  # noqa: E501

        :return: The session_id of this ExternalAuthRequestContent.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this ExternalAuthRequestContent.

        DCV session ID (always 'console' for auto-created sessions)  # noqa: E501

        :param session_id: The session_id of this ExternalAuthRequestContent.
        :type session_id: str
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501
        if session_id is not None and len(session_id) > 64:
            raise ValueError("Invalid value for `session_id`, length must be less than or equal to `64`")  # noqa: E501
        if session_id is not None and len(session_id) < 1:
            raise ValueError("Invalid value for `session_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._session_id = session_id

    @property
    def authentication_token(self) -> str:
        """Gets the authentication_token of this ExternalAuthRequestContent.

        Authentication token  # noqa: E501

        :return: The authentication_token of this ExternalAuthRequestContent.
        :rtype: str
        """
        return self._authentication_token

    @authentication_token.setter
    def authentication_token(self, authentication_token: str):
        """Sets the authentication_token of this ExternalAuthRequestContent.

        Authentication token  # noqa: E501

        :param authentication_token: The authentication_token of this ExternalAuthRequestContent.
        :type authentication_token: str
        """
        if authentication_token is None:
            raise ValueError("Invalid value for `authentication_token`, must not be `None`")  # noqa: E501
        if authentication_token is not None and len(authentication_token) > 2048:
            raise ValueError("Invalid value for `authentication_token`, length must be less than or equal to `2048`")  # noqa: E501
        if authentication_token is not None and len(authentication_token) < 1:
            raise ValueError("Invalid value for `authentication_token`, length must be greater than or equal to `1`")  # noqa: E501

        self._authentication_token = authentication_token

    @property
    def client_address(self) -> str:
        """Gets the client_address of this ExternalAuthRequestContent.

        Client IP address  # noqa: E501

        :return: The client_address of this ExternalAuthRequestContent.
        :rtype: str
        """
        return self._client_address

    @client_address.setter
    def client_address(self, client_address: str):
        """Sets the client_address of this ExternalAuthRequestContent.

        Client IP address  # noqa: E501

        :param client_address: The client_address of this ExternalAuthRequestContent.
        :type client_address: str
        """
        if client_address is None:
            raise ValueError("Invalid value for `client_address`, must not be `None`")  # noqa: E501
        if client_address is not None and len(client_address) > 45:
            raise ValueError("Invalid value for `client_address`, length must be less than or equal to `45`")  # noqa: E501
        if client_address is not None and len(client_address) < 1:
            raise ValueError("Invalid value for `client_address`, length must be greater than or equal to `1`")  # noqa: E501

        self._client_address = client_address
