#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.get_session_screenshot_request_data import GetSessionScreenshotRequestData
from datamodel import util

from datamodel.models.get_session_screenshot_request_data import GetSessionScreenshotRequestData  # noqa: E501

class GetSessionScreenshotUnsuccessfulResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, get_session_screenshot_request_data=None, failure_reason=None):  # noqa: E501
        """GetSessionScreenshotUnsuccessfulResponse - a model defined in OpenAPI

        :param get_session_screenshot_request_data: The get_session_screenshot_request_data of this GetSessionScreenshotUnsuccessfulResponse.  # noqa: E501
        :type get_session_screenshot_request_data: GetSessionScreenshotRequestData
        :param failure_reason: The failure_reason of this GetSessionScreenshotUnsuccessfulResponse.  # noqa: E501
        :type failure_reason: str
        """
        self.openapi_types = {
            'get_session_screenshot_request_data': GetSessionScreenshotRequestData,
            'failure_reason': str
        }

        self.attribute_map = {
            'get_session_screenshot_request_data': 'get_session_screenshot_request_data',
            'failure_reason': 'failure_reason'
        }

        self._get_session_screenshot_request_data = get_session_screenshot_request_data
        self._failure_reason = failure_reason

    @classmethod
    def from_dict(cls, dikt) -> 'GetSessionScreenshotUnsuccessfulResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetSessionScreenshotUnsuccessfulResponse of this GetSessionScreenshotUnsuccessfulResponse.  # noqa: E501
        :rtype: GetSessionScreenshotUnsuccessfulResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def get_session_screenshot_request_data(self) -> GetSessionScreenshotRequestData:
        """Gets the get_session_screenshot_request_data of this GetSessionScreenshotUnsuccessfulResponse.


        :return: The get_session_screenshot_request_data of this GetSessionScreenshotUnsuccessfulResponse.
        :rtype: GetSessionScreenshotRequestData
        """
        return self._get_session_screenshot_request_data

    @get_session_screenshot_request_data.setter
    def get_session_screenshot_request_data(self, get_session_screenshot_request_data: GetSessionScreenshotRequestData):
        """Sets the get_session_screenshot_request_data of this GetSessionScreenshotUnsuccessfulResponse.


        :param get_session_screenshot_request_data: The get_session_screenshot_request_data of this GetSessionScreenshotUnsuccessfulResponse.
        :type get_session_screenshot_request_data: GetSessionScreenshotRequestData
        """
        if get_session_screenshot_request_data is None:
            raise ValueError("Invalid value for `get_session_screenshot_request_data`, must not be `None`")  # noqa: E501

        self._get_session_screenshot_request_data = get_session_screenshot_request_data

    @property
    def failure_reason(self) -> str:
        """Gets the failure_reason of this GetSessionScreenshotUnsuccessfulResponse.

        The failure reason  # noqa: E501

        :return: The failure_reason of this GetSessionScreenshotUnsuccessfulResponse.
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason: str):
        """Sets the failure_reason of this GetSessionScreenshotUnsuccessfulResponse.

        The failure reason  # noqa: E501

        :param failure_reason: The failure_reason of this GetSessionScreenshotUnsuccessfulResponse.
        :type failure_reason: str
        """
        if failure_reason is None:
            raise ValueError("Invalid value for `failure_reason`, must not be `None`")  # noqa: E501

        self._failure_reason = failure_reason
