#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class GetSessionScreenshotRequestData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None):  # noqa: E501
        """GetSessionScreenshotRequestData - a model defined in OpenAPI

        :param session_id: The session_id of this GetSessionScreenshotRequestData.  # noqa: E501
        :type session_id: str
        """
        self.openapi_types = {
            'session_id': str
        }

        self.attribute_map = {
            'session_id': 'session_id'
        }

        self._session_id = session_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetSessionScreenshotRequestData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetSessionScreenshotRequestData of this GetSessionScreenshotRequestData.  # noqa: E501
        :rtype: GetSessionScreenshotRequestData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this GetSessionScreenshotRequestData.

        The RES session id  # noqa: E501

        :return: The session_id of this GetSessionScreenshotRequestData.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this GetSessionScreenshotRequestData.

        The RES session id  # noqa: E501

        :param session_id: The session_id of this GetSessionScreenshotRequestData.
        :type session_id: str
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501
        if session_id is not None and len(session_id) < 1:
            raise ValueError("Invalid value for `session_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._session_id = session_id
