#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.session_screenshot import SessionScreenshot
from datamodel import util

from datamodel.models.session_screenshot import SessionScreenshot  # noqa: E501

class GetSessionScreenshotSuccessfulResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_screenshot=None):  # noqa: E501
        """GetSessionScreenshotSuccessfulResponse - a model defined in OpenAPI

        :param session_screenshot: The session_screenshot of this GetSessionScreenshotSuccessfulResponse.  # noqa: E501
        :type session_screenshot: SessionScreenshot
        """
        self.openapi_types = {
            'session_screenshot': SessionScreenshot
        }

        self.attribute_map = {
            'session_screenshot': 'session_screenshot'
        }

        self._session_screenshot = session_screenshot

    @classmethod
    def from_dict(cls, dikt) -> 'GetSessionScreenshotSuccessfulResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetSessionScreenshotSuccessfulResponse of this GetSessionScreenshotSuccessfulResponse.  # noqa: E501
        :rtype: GetSessionScreenshotSuccessfulResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_screenshot(self) -> SessionScreenshot:
        """Gets the session_screenshot of this GetSessionScreenshotSuccessfulResponse.


        :return: The session_screenshot of this GetSessionScreenshotSuccessfulResponse.
        :rtype: SessionScreenshot
        """
        return self._session_screenshot

    @session_screenshot.setter
    def session_screenshot(self, session_screenshot: SessionScreenshot):
        """Sets the session_screenshot of this GetSessionScreenshotSuccessfulResponse.


        :param session_screenshot: The session_screenshot of this GetSessionScreenshotSuccessfulResponse.
        :type session_screenshot: SessionScreenshot
        """
        if session_screenshot is None:
            raise ValueError("Invalid value for `session_screenshot`, must not be `None`")  # noqa: E501

        self._session_screenshot = session_screenshot
