#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.get_session_screenshot_request_data import GetSessionScreenshotRequestData
from datamodel import util

from datamodel.models.get_session_screenshot_request_data import GetSessionScreenshotRequestData  # noqa: E501

class GetSessionScreenshotsRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, requester=None, sessions=None):  # noqa: E501
        """GetSessionScreenshotsRequestContent - a model defined in OpenAPI

        :param requester: The requester of this GetSessionScreenshotsRequestContent.  # noqa: E501
        :type requester: str
        :param sessions: The sessions of this GetSessionScreenshotsRequestContent.  # noqa: E501
        :type sessions: List[GetSessionScreenshotRequestData]
        """
        self.openapi_types = {
            'requester': str,
            'sessions': List[GetSessionScreenshotRequestData]
        }

        self.attribute_map = {
            'requester': 'requester',
            'sessions': 'sessions'
        }

        self._requester = requester
        self._sessions = sessions

    @classmethod
    def from_dict(cls, dikt) -> 'GetSessionScreenshotsRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetSessionScreenshotsRequestContent of this GetSessionScreenshotsRequestContent.  # noqa: E501
        :rtype: GetSessionScreenshotsRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def requester(self) -> str:
        """Gets the requester of this GetSessionScreenshotsRequestContent.

        The username of the screenshots requester.  # noqa: E501

        :return: The requester of this GetSessionScreenshotsRequestContent.
        :rtype: str
        """
        return self._requester

    @requester.setter
    def requester(self, requester: str):
        """Sets the requester of this GetSessionScreenshotsRequestContent.

        The username of the screenshots requester.  # noqa: E501

        :param requester: The requester of this GetSessionScreenshotsRequestContent.
        :type requester: str
        """
        if requester is None:
            raise ValueError("Invalid value for `requester`, must not be `None`")  # noqa: E501
        if requester is not None and len(requester) < 1:
            raise ValueError("Invalid value for `requester`, length must be greater than or equal to `1`")  # noqa: E501

        self._requester = requester

    @property
    def sessions(self) -> List[GetSessionScreenshotRequestData]:
        """Gets the sessions of this GetSessionScreenshotsRequestContent.

        Sessions to get screenshots for  # noqa: E501

        :return: The sessions of this GetSessionScreenshotsRequestContent.
        :rtype: List[GetSessionScreenshotRequestData]
        """
        return self._sessions

    @sessions.setter
    def sessions(self, sessions: List[GetSessionScreenshotRequestData]):
        """Sets the sessions of this GetSessionScreenshotsRequestContent.

        Sessions to get screenshots for  # noqa: E501

        :param sessions: The sessions of this GetSessionScreenshotsRequestContent.
        :type sessions: List[GetSessionScreenshotRequestData]
        """
        if sessions is None:
            raise ValueError("Invalid value for `sessions`, must not be `None`")  # noqa: E501

        self._sessions = sessions
