#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class ResolveSessionResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None, transport_protocol=None, dcv_server_endpoint=None, port=None, web_url_path=None):  # noqa: E501
        """ResolveSessionResponseContent - a model defined in OpenAPI

        :param session_id: The session_id of this ResolveSessionResponseContent.  # noqa: E501
        :type session_id: str
        :param transport_protocol: The transport_protocol of this ResolveSessionResponseContent.  # noqa: E501
        :type transport_protocol: str
        :param dcv_server_endpoint: The dcv_server_endpoint of this ResolveSessionResponseContent.  # noqa: E501
        :type dcv_server_endpoint: str
        :param port: The port of this ResolveSessionResponseContent.  # noqa: E501
        :type port: int
        :param web_url_path: The web_url_path of this ResolveSessionResponseContent.  # noqa: E501
        :type web_url_path: str
        """
        self.openapi_types = {
            'session_id': str,
            'transport_protocol': str,
            'dcv_server_endpoint': str,
            'port': int,
            'web_url_path': str
        }

        self.attribute_map = {
            'session_id': 'SessionId',
            'transport_protocol': 'TransportProtocol',
            'dcv_server_endpoint': 'DcvServerEndpoint',
            'port': 'Port',
            'web_url_path': 'WebUrlPath'
        }

        self._session_id = session_id
        self._transport_protocol = transport_protocol
        self._dcv_server_endpoint = dcv_server_endpoint
        self._port = port
        self._web_url_path = web_url_path

    @classmethod
    def from_dict(cls, dikt) -> 'ResolveSessionResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResolveSessionResponseContent of this ResolveSessionResponseContent.  # noqa: E501
        :rtype: ResolveSessionResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this ResolveSessionResponseContent.

        Resolved session ID  # noqa: E501

        :return: The session_id of this ResolveSessionResponseContent.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this ResolveSessionResponseContent.

        Resolved session ID  # noqa: E501

        :param session_id: The session_id of this ResolveSessionResponseContent.
        :type session_id: str
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def transport_protocol(self) -> str:
        """Gets the transport_protocol of this ResolveSessionResponseContent.

        Transport protocol for connection  # noqa: E501

        :return: The transport_protocol of this ResolveSessionResponseContent.
        :rtype: str
        """
        return self._transport_protocol

    @transport_protocol.setter
    def transport_protocol(self, transport_protocol: str):
        """Sets the transport_protocol of this ResolveSessionResponseContent.

        Transport protocol for connection  # noqa: E501

        :param transport_protocol: The transport_protocol of this ResolveSessionResponseContent.
        :type transport_protocol: str
        """
        if transport_protocol is None:
            raise ValueError("Invalid value for `transport_protocol`, must not be `None`")  # noqa: E501

        self._transport_protocol = transport_protocol

    @property
    def dcv_server_endpoint(self) -> str:
        """Gets the dcv_server_endpoint of this ResolveSessionResponseContent.

        DCV server DNS name  # noqa: E501

        :return: The dcv_server_endpoint of this ResolveSessionResponseContent.
        :rtype: str
        """
        return self._dcv_server_endpoint

    @dcv_server_endpoint.setter
    def dcv_server_endpoint(self, dcv_server_endpoint: str):
        """Sets the dcv_server_endpoint of this ResolveSessionResponseContent.

        DCV server DNS name  # noqa: E501

        :param dcv_server_endpoint: The dcv_server_endpoint of this ResolveSessionResponseContent.
        :type dcv_server_endpoint: str
        """
        if dcv_server_endpoint is None:
            raise ValueError("Invalid value for `dcv_server_endpoint`, must not be `None`")  # noqa: E501

        self._dcv_server_endpoint = dcv_server_endpoint

    @property
    def port(self) -> int:
        """Gets the port of this ResolveSessionResponseContent.

        Port number for connection  # noqa: E501

        :return: The port of this ResolveSessionResponseContent.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port: int):
        """Sets the port of this ResolveSessionResponseContent.

        Port number for connection  # noqa: E501

        :param port: The port of this ResolveSessionResponseContent.
        :type port: int
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def web_url_path(self) -> str:
        """Gets the web_url_path of this ResolveSessionResponseContent.

        Web URL path for the session  # noqa: E501

        :return: The web_url_path of this ResolveSessionResponseContent.
        :rtype: str
        """
        return self._web_url_path

    @web_url_path.setter
    def web_url_path(self, web_url_path: str):
        """Sets the web_url_path of this ResolveSessionResponseContent.

        Web URL path for the session  # noqa: E501

        :param web_url_path: The web_url_path of this ResolveSessionResponseContent.
        :type web_url_path: str
        """
        if web_url_path is None:
            raise ValueError("Invalid value for `web_url_path`, must not be `None`")  # noqa: E501

        self._web_url_path = web_url_path
