#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class Server(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, web_url_path=None):  # noqa: E501
        """Server - a model defined in OpenAPI

        :param web_url_path: The web_url_path of this Server.  # noqa: E501
        :type web_url_path: str
        """
        self.openapi_types = {
            'web_url_path': str
        }

        self.attribute_map = {
            'web_url_path': 'webUrlPath'
        }

        self._web_url_path = web_url_path

    @classmethod
    def from_dict(cls, dikt) -> 'Server':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Server of this Server.  # noqa: E501
        :rtype: Server
        """
        return util.deserialize_model(dikt, cls)

    @property
    def web_url_path(self) -> str:
        """Gets the web_url_path of this Server.

        The server web url path  # noqa: E501

        :return: The web_url_path of this Server.
        :rtype: str
        """
        return self._web_url_path

    @web_url_path.setter
    def web_url_path(self, web_url_path: str):
        """Sets the web_url_path of this Server.

        The server web url path  # noqa: E501

        :param web_url_path: The web_url_path of this Server.
        :type web_url_path: str
        """
        if web_url_path is None:
            raise ValueError("Invalid value for `web_url_path`, must not be `None`")  # noqa: E501
        if web_url_path is not None and len(web_url_path) < 1:
            raise ValueError("Invalid value for `web_url_path`, length must be greater than or equal to `1`")  # noqa: E501

        self._web_url_path = web_url_path
