#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.session_screenshot_image import SessionScreenshotImage
from datamodel import util

from datamodel.models.session_screenshot_image import SessionScreenshotImage  # noqa: E501

class SessionScreenshot(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None, images=None):  # noqa: E501
        """SessionScreenshot - a model defined in OpenAPI

        :param session_id: The session_id of this SessionScreenshot.  # noqa: E501
        :type session_id: str
        :param images: The images of this SessionScreenshot.  # noqa: E501
        :type images: List[SessionScreenshotImage]
        """
        self.openapi_types = {
            'session_id': str,
            'images': List[SessionScreenshotImage]
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'images': 'images'
        }

        self._session_id = session_id
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'SessionScreenshot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SessionScreenshot of this SessionScreenshot.  # noqa: E501
        :rtype: SessionScreenshot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this SessionScreenshot.

        The id of the session  # noqa: E501

        :return: The session_id of this SessionScreenshot.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this SessionScreenshot.

        The id of the session  # noqa: E501

        :param session_id: The session_id of this SessionScreenshot.
        :type session_id: str
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501
        if session_id is not None and len(session_id) < 1:
            raise ValueError("Invalid value for `session_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._session_id = session_id

    @property
    def images(self) -> List[SessionScreenshotImage]:
        """Gets the images of this SessionScreenshot.

        The array of session screenshots  # noqa: E501

        :return: The images of this SessionScreenshot.
        :rtype: List[SessionScreenshotImage]
        """
        return self._images

    @images.setter
    def images(self, images: List[SessionScreenshotImage]):
        """Sets the images of this SessionScreenshot.

        The array of session screenshots  # noqa: E501

        :param images: The images of this SessionScreenshot.
        :type images: List[SessionScreenshotImage]
        """
        if images is None:
            raise ValueError("Invalid value for `images`, must not be `None`")  # noqa: E501

        self._images = images
