#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.server import Server
from datamodel import util

from datamodel.models.server import Server  # noqa: E501

class Session(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, owner=None, server=None):  # noqa: E501
        """Session - a model defined in OpenAPI

        :param id: The id of this Session.  # noqa: E501
        :type id: str
        :param owner: The owner of this Session.  # noqa: E501
        :type owner: str
        :param server: The server of this Session.  # noqa: E501
        :type server: Server
        """
        self.openapi_types = {
            'id': str,
            'owner': str,
            'server': Server
        }

        self.attribute_map = {
            'id': 'id',
            'owner': 'owner',
            'server': 'server'
        }

        self._id = id
        self._owner = owner
        self._server = server

    @classmethod
    def from_dict(cls, dikt) -> 'Session':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Session of this Session.  # noqa: E501
        :rtype: Session
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Session.

        The id of the session  # noqa: E501

        :return: The id of this Session.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Session.

        The id of the session  # noqa: E501

        :param id: The id of this Session.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501

        self._id = id

    @property
    def owner(self) -> str:
        """Gets the owner of this Session.

        The owner of the session  # noqa: E501

        :return: The owner of this Session.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner: str):
        """Sets the owner of this Session.

        The owner of the session  # noqa: E501

        :param owner: The owner of this Session.
        :type owner: str
        """
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501
        if owner is not None and len(owner) < 1:
            raise ValueError("Invalid value for `owner`, length must be greater than or equal to `1`")  # noqa: E501

        self._owner = owner

    @property
    def server(self) -> Server:
        """Gets the server of this Session.


        :return: The server of this Session.
        :rtype: Server
        """
        return self._server

    @server.setter
    def server(self, server: Server):
        """Sets the server of this Session.


        :param server: The server of this Session.
        :type server: Server
        """
        if server is None:
            raise ValueError("Invalid value for `server`, must not be `None`")  # noqa: E501

        self._server = server
