#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class SessionScreenshotImage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, format=None, data=None, created_on=None, primary=None):  # noqa: E501
        """SessionScreenshotImage - a model defined in OpenAPI

        :param format: The format of this SessionScreenshotImage.  # noqa: E501
        :type format: str
        :param data: The data of this SessionScreenshotImage.  # noqa: E501
        :type data: str
        :param created_on: The created_on of this SessionScreenshotImage.  # noqa: E501
        :type created_on: str
        :param primary: The primary of this SessionScreenshotImage.  # noqa: E501
        :type primary: bool
        """
        self.openapi_types = {
            'format': str,
            'data': str,
            'created_on': str,
            'primary': bool
        }

        self.attribute_map = {
            'format': 'format',
            'data': 'data',
            'created_on': 'created_on',
            'primary': 'primary'
        }

        self._format = format
        self._data = data
        self._created_on = created_on
        self._primary = primary

    @classmethod
    def from_dict(cls, dikt) -> 'SessionScreenshotImage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SessionScreenshotImage of this SessionScreenshotImage.  # noqa: E501
        :rtype: SessionScreenshotImage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def format(self) -> str:
        """Gets the format of this SessionScreenshotImage.

        The image format. Supported formats: jpeg, png  # noqa: E501

        :return: The format of this SessionScreenshotImage.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format: str):
        """Sets the format of this SessionScreenshotImage.

        The image format. Supported formats: jpeg, png  # noqa: E501

        :param format: The format of this SessionScreenshotImage.
        :type format: str
        """
        if format is None:
            raise ValueError("Invalid value for `format`, must not be `None`")  # noqa: E501
        if format is not None and len(format) < 1:
            raise ValueError("Invalid value for `format`, length must be greater than or equal to `1`")  # noqa: E501

        self._format = format

    @property
    def data(self) -> str:
        """Gets the data of this SessionScreenshotImage.

        The base64 image data  # noqa: E501

        :return: The data of this SessionScreenshotImage.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this SessionScreenshotImage.

        The base64 image data  # noqa: E501

        :param data: The data of this SessionScreenshotImage.
        :type data: str
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501
        if data is not None and len(data) < 1:
            raise ValueError("Invalid value for `data`, length must be greater than or equal to `1`")  # noqa: E501

        self._data = data

    @property
    def created_on(self) -> str:
        """Gets the created_on of this SessionScreenshotImage.

        Timestamp when the screenshot was created  # noqa: E501

        :return: The created_on of this SessionScreenshotImage.
        :rtype: str
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on: str):
        """Sets the created_on of this SessionScreenshotImage.

        Timestamp when the screenshot was created  # noqa: E501

        :param created_on: The created_on of this SessionScreenshotImage.
        :type created_on: str
        """
        if created_on is None:
            raise ValueError("Invalid value for `created_on`, must not be `None`")  # noqa: E501
        if created_on is not None and len(created_on) < 1:
            raise ValueError("Invalid value for `created_on`, length must be greater than or equal to `1`")  # noqa: E501

        self._created_on = created_on

    @property
    def primary(self) -> bool:
        """Gets the primary of this SessionScreenshotImage.

        Tells if the image belongs to the primary screen  # noqa: E501

        :return: The primary of this SessionScreenshotImage.
        :rtype: bool
        """
        return self._primary

    @primary.setter
    def primary(self, primary: bool):
        """Sets the primary of this SessionScreenshotImage.

        Tells if the image belongs to the primary screen  # noqa: E501

        :param primary: The primary of this SessionScreenshotImage.
        :type primary: bool
        """
        if primary is None:
            raise ValueError("Invalid value for `primary`, must not be `None`")  # noqa: E501

        self._primary = primary
