#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel import util


class UpdateSessionPermissionsRequestData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None, owner=None, permissions_file=None):  # noqa: E501
        """UpdateSessionPermissionsRequestData - a model defined in OpenAPI

        :param session_id: The session_id of this UpdateSessionPermissionsRequestData.  # noqa: E501
        :type session_id: str
        :param owner: The owner of this UpdateSessionPermissionsRequestData.  # noqa: E501
        :type owner: str
        :param permissions_file: The permissions_file of this UpdateSessionPermissionsRequestData.  # noqa: E501
        :type permissions_file: str
        """
        self.openapi_types = {
            'session_id': str,
            'owner': str,
            'permissions_file': str
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'owner': 'owner',
            'permissions_file': 'permissions_file'
        }

        self._session_id = session_id
        self._owner = owner
        self._permissions_file = permissions_file

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateSessionPermissionsRequestData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateSessionPermissionsRequestData of this UpdateSessionPermissionsRequestData.  # noqa: E501
        :rtype: UpdateSessionPermissionsRequestData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this UpdateSessionPermissionsRequestData.

        The session id  # noqa: E501

        :return: The session_id of this UpdateSessionPermissionsRequestData.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this UpdateSessionPermissionsRequestData.

        The session id  # noqa: E501

        :param session_id: The session_id of this UpdateSessionPermissionsRequestData.
        :type session_id: str
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501
        if session_id is not None and len(session_id) < 1:
            raise ValueError("Invalid value for `session_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._session_id = session_id

    @property
    def owner(self) -> str:
        """Gets the owner of this UpdateSessionPermissionsRequestData.

        The session owner  # noqa: E501

        :return: The owner of this UpdateSessionPermissionsRequestData.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner: str):
        """Sets the owner of this UpdateSessionPermissionsRequestData.

        The session owner  # noqa: E501

        :param owner: The owner of this UpdateSessionPermissionsRequestData.
        :type owner: str
        """
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501
        if owner is not None and len(owner) < 1:
            raise ValueError("Invalid value for `owner`, length must be greater than or equal to `1`")  # noqa: E501

        self._owner = owner

    @property
    def permissions_file(self) -> str:
        """Gets the permissions_file of this UpdateSessionPermissionsRequestData.

        The permissions file base64 encoded  # noqa: E501

        :return: The permissions_file of this UpdateSessionPermissionsRequestData.
        :rtype: str
        """
        return self._permissions_file

    @permissions_file.setter
    def permissions_file(self, permissions_file: str):
        """Sets the permissions_file of this UpdateSessionPermissionsRequestData.

        The permissions file base64 encoded  # noqa: E501

        :param permissions_file: The permissions_file of this UpdateSessionPermissionsRequestData.
        :type permissions_file: str
        """
        if permissions_file is None:
            raise ValueError("Invalid value for `permissions_file`, must not be `None`")  # noqa: E501
        if permissions_file is not None and len(permissions_file) < 1:
            raise ValueError("Invalid value for `permissions_file`, length must be greater than or equal to `1`")  # noqa: E501

        self._permissions_file = permissions_file
