#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.update_session_permissions_successful_response import UpdateSessionPermissionsSuccessfulResponse
from datamodel.models.update_session_permissions_unsuccessful_response import UpdateSessionPermissionsUnsuccessfulResponse
from datamodel import util

from datamodel.models.update_session_permissions_successful_response import UpdateSessionPermissionsSuccessfulResponse  # noqa: E501
from datamodel.models.update_session_permissions_unsuccessful_response import UpdateSessionPermissionsUnsuccessfulResponse  # noqa: E501

class UpdateSessionPermissionsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, successful_list=None, unsuccessful_list=None):  # noqa: E501
        """UpdateSessionPermissionsResponseContent - a model defined in OpenAPI

        :param successful_list: The successful_list of this UpdateSessionPermissionsResponseContent.  # noqa: E501
        :type successful_list: List[UpdateSessionPermissionsSuccessfulResponse]
        :param unsuccessful_list: The unsuccessful_list of this UpdateSessionPermissionsResponseContent.  # noqa: E501
        :type unsuccessful_list: List[UpdateSessionPermissionsUnsuccessfulResponse]
        """
        self.openapi_types = {
            'successful_list': List[UpdateSessionPermissionsSuccessfulResponse],
            'unsuccessful_list': List[UpdateSessionPermissionsUnsuccessfulResponse]
        }

        self.attribute_map = {
            'successful_list': 'successful_list',
            'unsuccessful_list': 'unsuccessful_list'
        }

        self._successful_list = successful_list
        self._unsuccessful_list = unsuccessful_list

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateSessionPermissionsResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateSessionPermissionsResponseContent of this UpdateSessionPermissionsResponseContent.  # noqa: E501
        :rtype: UpdateSessionPermissionsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def successful_list(self) -> List[UpdateSessionPermissionsSuccessfulResponse]:
        """Gets the successful_list of this UpdateSessionPermissionsResponseContent.

        The array of sessions with permissions successfully updated  # noqa: E501

        :return: The successful_list of this UpdateSessionPermissionsResponseContent.
        :rtype: List[UpdateSessionPermissionsSuccessfulResponse]
        """
        return self._successful_list

    @successful_list.setter
    def successful_list(self, successful_list: List[UpdateSessionPermissionsSuccessfulResponse]):
        """Sets the successful_list of this UpdateSessionPermissionsResponseContent.

        The array of sessions with permissions successfully updated  # noqa: E501

        :param successful_list: The successful_list of this UpdateSessionPermissionsResponseContent.
        :type successful_list: List[UpdateSessionPermissionsSuccessfulResponse]
        """
        if successful_list is None:
            raise ValueError("Invalid value for `successful_list`, must not be `None`")  # noqa: E501

        self._successful_list = successful_list

    @property
    def unsuccessful_list(self) -> List[UpdateSessionPermissionsUnsuccessfulResponse]:
        """Gets the unsuccessful_list of this UpdateSessionPermissionsResponseContent.

        The array of sessions with permissions that failed to update  # noqa: E501

        :return: The unsuccessful_list of this UpdateSessionPermissionsResponseContent.
        :rtype: List[UpdateSessionPermissionsUnsuccessfulResponse]
        """
        return self._unsuccessful_list

    @unsuccessful_list.setter
    def unsuccessful_list(self, unsuccessful_list: List[UpdateSessionPermissionsUnsuccessfulResponse]):
        """Sets the unsuccessful_list of this UpdateSessionPermissionsResponseContent.

        The array of sessions with permissions that failed to update  # noqa: E501

        :param unsuccessful_list: The unsuccessful_list of this UpdateSessionPermissionsResponseContent.
        :type unsuccessful_list: List[UpdateSessionPermissionsUnsuccessfulResponse]
        """
        if unsuccessful_list is None:
            raise ValueError("Invalid value for `unsuccessful_list`, must not be `None`")  # noqa: E501

        self._unsuccessful_list = unsuccessful_list
