#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datamodel.models.base_model import Model
from datamodel.models.update_session_permissions_request_data import UpdateSessionPermissionsRequestData
from datamodel import util

from datamodel.models.update_session_permissions_request_data import UpdateSessionPermissionsRequestData  # noqa: E501

class UpdateSessionPermissionsRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sessions=None):  # noqa: E501
        """UpdateSessionPermissionsRequestContent - a model defined in OpenAPI

        :param sessions: The sessions of this UpdateSessionPermissionsRequestContent.  # noqa: E501
        :type sessions: List[UpdateSessionPermissionsRequestData]
        """
        self.openapi_types = {
            'sessions': List[UpdateSessionPermissionsRequestData]
        }

        self.attribute_map = {
            'sessions': 'sessions'
        }

        self._sessions = sessions

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateSessionPermissionsRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateSessionPermissionsRequestContent of this UpdateSessionPermissionsRequestContent.  # noqa: E501
        :rtype: UpdateSessionPermissionsRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sessions(self) -> List[UpdateSessionPermissionsRequestData]:
        """Gets the sessions of this UpdateSessionPermissionsRequestContent.

        DCV Sessions to update permissions for  # noqa: E501

        :return: The sessions of this UpdateSessionPermissionsRequestContent.
        :rtype: List[UpdateSessionPermissionsRequestData]
        """
        return self._sessions

    @sessions.setter
    def sessions(self, sessions: List[UpdateSessionPermissionsRequestData]):
        """Sets the sessions of this UpdateSessionPermissionsRequestContent.

        DCV Sessions to update permissions for  # noqa: E501

        :param sessions: The sessions of this UpdateSessionPermissionsRequestContent.
        :type sessions: List[UpdateSessionPermissionsRequestData]
        """
        if sessions is None:
            raise ValueError("Invalid value for `sessions`, must not be `None`")  # noqa: E501
        if sessions is not None and len(sessions) < 1:
            raise ValueError("Invalid value for `sessions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._sessions = sessions
