version: 0.2
env:
  variables:
    PYTHON_VERSION: "3.9.16" # Python version to setup local dev environment

phases:
  pre_build:
    commands:
       # Update Pyenv
      - echo "Updating Pyenv"
      - echo "Pyenv version"
      - pyenv --version
      - echo "Pyenv version list"
      - pyenv install --list
      - cd /root/.pyenv/plugins/python-build/../.. && git reset --hard && git pull && cd -
      - echo "Post-PyEnv update"
      - pyenv --version
      - pyenv install --list
      # Installing Python
      - pyenv install --skip-existing $PYTHON_VERSION
      - PYENV_VERSION=$PYTHON_VERSION python3 -m venv ~/.venv

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - . ~/.venv/bin/activate
      - pip install bandit
      - |
        if [[ -z "$SCAN_LEVEL" ]]; then
          echo "SCAN_LEVEl environment variable not set, default to -ll"
          SCAN_LEVEL="-ll"
        fi
      - bandit -r source/idea/ $SCAN_LEVEL
