# metrics module configuration
# Note: metrics module must be enabled during initial cluster deployment.
# if module is enabled post initial deployment, metric daemons on existing hosts need to be manually installed and configured.
# same is true for any changes to metrics provider. make an informed decision and choose your metrics provider based on your requirements.

# graphana, visualizations and dashboards is out of IDEA scope.
# you need to manually configure the applicable dashboards based on the metrics provider you've configured for the cluster.

# provider can be one of [cloudwatch, amazon_managed_prometheus, prometheus]
provider: "{{metrics_provider}}"

{%- if metrics_provider == 'cloudwatch' %}
cloudwatch:
  # `dashboard_name` can only contain alphanumerics, dash (-) and underscore (_).
  dashboard_name: "{{cluster_name}}_{{aws_region}}"

  # Specifies the default value for often all metrics are to be collected.
  # Individual modules may choose to override this value for specific types of metrics.
  metrics_collection_interval: 60

  # Specifies in seconds the maximum amount of time that metrics remain in the memory buffer before being sent to the server.
  # No matter the setting for this, if the size of the metrics in the buffer reaches 40 KB or 20 different metrics, the metrics are immediately sent to the server.
  force_flush_interval: 60
{%- endif %}

{%- if metrics_provider == 'amazon_managed_prometheus' %}
amazon_managed_prometheus:
  workspace_name: {{cluster_name}}-workspace
{%- endif %}

{%- if metrics_provider in ['amazon_managed_prometheus', 'prometheus'] %}
prometheus:

  # default scrape_interval. individual modules may override this configuration.
  # How frequently to scrape targets by default.
  # a duration matching the regular expression ((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0), e.g. 1d, 1h30m, 5m, 10s
  scrape_interval: 60s

  # default scrape_timeout. individual modules may override this configuration.
  # How long until a scrape request times out.
  # a duration matching the regular expression ((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0), e.g. 1d, 1h30m, 5m, 10s
  scrape_timeout: 10s

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # Note: If you have existing prometheus timeseries data, adding new labels to
  # external_labels in this config will create new time series for the metrics!!
  external_labels:
    cluster_name: '{{cluster_name}}'
    # enable aws_region, if you are deploying multiple IDEA clusters and collecting all metrics to a single metrics endpoint.
    # aws_region: '{{aws_region}}'

  # if metrics_provider = prometheus, provide your custom prometheus remote write configuration.
  #   for more details, refer to: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
  # for amazon_managed_prometheus, metrics stack will update these parameters via cluster settings custom resource
  # Note: prometheus supports remote write as list. multiple remote writes is not supported in IDEA.
  # You can add additional configuration as specified in the remote_write configuration
  remote_write:
    url: {{ prometheus_remote_write_url if prometheus_remote_write_url else '~' }}
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

    # applicable only for custom prometheus - TODO
    # for custom prometheus, do NOT hardcode credentials using `password`.
    # create a secret in AWS Secrets Manager and provide the ARN as password_file
    # IDEA framework will handle the logic to read the secret at run time.
    # basic_auth:
    #   [ username: <string> ]
    #   [ password: <secret> ]
    #   [ password_file: <SecretArn> ]

    # applicable only for custom prometheus - TODO
    # to configure Authorization header, do NOT hardcode `credentials`.
    # create a secret in AWS Secrets Manager and provide the ARN as credentials_file
    # IDEA framework will handle the logic to read the secret at run time.
    # authorization:
    #   Sets the authentication type.
    #   [ type: <string> | default: Bearer ]
    #   Sets the credentials. It is mutually exclusive with `credentials_file`.
    #   [ credentials: <secret> ]
    #   Sets the credentials to the credentials read from the configured file. It is mutually exclusive with `credentials`.
    #   [ credentials_file: <SecretArn> ]

  # NOTE: this is not used in current IDEA release.
  # this config will not be provisioned in prometheus.yml, but will be used by IDEA to query remote prometheus service.
  # plotting and charting prometheus metrics on IDEA WebPortal is on the roadmap.
  # for Amazon Managed Prometheus, this will be updated via ClusterSettings custom resource after provisioning Prometheus Workspace.
  # for custom prometheus, update this section in a similar fashion as that of remote_write configuration.
  remote_read:
    url: {{ prometheus_query_url if prometheus_query_url else '~' }}
{%- endif %}
