#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

# flake8: noqa
# import models into model package
from api.models.bad_request_exception_response_content import BadRequestExceptionResponseContent
from api.models.batch_get_dcv_sessions_request_content import BatchGetDCVSessionsRequestContent
from api.models.batch_get_dcv_sessions_response_content import BatchGetDCVSessionsResponseContent
from api.models.day_of_week import DayOfWeek
from api.models.get_permission_profile_response_content import GetPermissionProfileResponseContent
from api.models.internal_service_exception_response_content import InternalServiceExceptionResponseContent
from api.models.list_allowed_instance_types_for_session_request_content import ListAllowedInstanceTypesForSessionRequestContent
from api.models.list_allowed_instance_types_for_session_response_content import ListAllowedInstanceTypesForSessionResponseContent
from api.models.list_allowed_instance_types_request_content import ListAllowedInstanceTypesRequestContent
from api.models.list_allowed_instance_types_response_content import ListAllowedInstanceTypesResponseContent
from api.models.list_dcv_servers_response_content import ListDCVServersResponseContent
from api.models.list_permission_profiles_response_content import ListPermissionProfilesResponseContent
from api.models.list_schedule_types_response_content import ListScheduleTypesResponseContent
from api.models.list_supported_gpus_response_content import ListSupportedGpusResponseContent
from api.models.list_supported_oses_response_content import ListSupportedOsesResponseContent
from api.models.list_value import ListValue
from api.models.project import Project
from api.models.res_date_range import ResDateRange
from api.models.res_filter import ResFilter
from api.models.res_filter_value_string_or_list import ResFilterValueStringOrList
from api.models.res_memory import ResMemory
from api.models.res_paginator import ResPaginator
from api.models.res_sort_by import ResSortBy
from api.models.res_sort_order import ResSortOrder
from api.models.string_value import StringValue
from api.models.virtual_desktop_affinity import VirtualDesktopAffinity
from api.models.virtual_desktop_architecture import VirtualDesktopArchitecture
from api.models.virtual_desktop_base_os import VirtualDesktopBaseOs
from api.models.virtual_desktop_gpu import VirtualDesktopGpu
from api.models.virtual_desktop_permission import VirtualDesktopPermission
from api.models.virtual_desktop_permission_profile import VirtualDesktopPermissionProfile
from api.models.virtual_desktop_placement import VirtualDesktopPlacement
from api.models.virtual_desktop_schedule import VirtualDesktopSchedule
from api.models.virtual_desktop_schedule_type import VirtualDesktopScheduleType
from api.models.virtual_desktop_server import VirtualDesktopServer
from api.models.virtual_desktop_session import VirtualDesktopSession
from api.models.virtual_desktop_session_state import VirtualDesktopSessionState
from api.models.virtual_desktop_session_type import VirtualDesktopSessionType
from api.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack
from api.models.virtual_desktop_tenancy import VirtualDesktopTenancy
from api.models.virtual_desktop_week_schedule import VirtualDesktopWeekSchedule
