#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from api import util
from api.models.base_model import Model
from api.models.virtual_desktop_session import VirtualDesktopSession  # noqa: E501


class BatchGetDCVSessionsRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sessions=None, next_token=None):  # noqa: E501
        """BatchGetDCVSessionsRequestContent - a model defined in OpenAPI

        :param sessions: The sessions of this BatchGetDCVSessionsRequestContent.  # noqa: E501
        :type sessions: List[VirtualDesktopSession]
        :param next_token: The next_token of this BatchGetDCVSessionsRequestContent.  # noqa: E501
        :type next_token: str
        """
        self.openapi_types = {
            'sessions': List[VirtualDesktopSession],
            'next_token': str
        }

        self.attribute_map = {
            'sessions': 'sessions',
            'next_token': 'nextToken'
        }

        self._sessions = sessions
        self._next_token = next_token

    @classmethod
    def from_dict(cls, dikt) -> 'BatchGetDCVSessionsRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchGetDCVSessionsRequestContent of this BatchGetDCVSessionsRequestContent.  # noqa: E501
        :rtype: BatchGetDCVSessionsRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sessions(self) -> List[VirtualDesktopSession]:
        """Gets the sessions of this BatchGetDCVSessionsRequestContent.

        List of sessions to retrieve DCV sessions of  # noqa: E501

        :return: The sessions of this BatchGetDCVSessionsRequestContent.
        :rtype: List[VirtualDesktopSession]
        """
        return self._sessions

    @sessions.setter
    def sessions(self, sessions: List[VirtualDesktopSession]):
        """Sets the sessions of this BatchGetDCVSessionsRequestContent.

        List of sessions to retrieve DCV sessions of  # noqa: E501

        :param sessions: The sessions of this BatchGetDCVSessionsRequestContent.
        :type sessions: List[VirtualDesktopSession]
        """

        self._sessions = sessions

    @property
    def next_token(self) -> str:
        """Gets the next_token of this BatchGetDCVSessionsRequestContent.

        Pagination token for next page  # noqa: E501

        :return: The next_token of this BatchGetDCVSessionsRequestContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token: str):
        """Sets the next_token of this BatchGetDCVSessionsRequestContent.

        Pagination token for next page  # noqa: E501

        :param next_token: The next_token of this BatchGetDCVSessionsRequestContent.
        :type next_token: str
        """

        self._next_token = next_token
