#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api import util


class HelloWorldResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, timestamp=None):  # noqa: E501
        """HelloWorldResponseContent - a model defined in OpenAPI

        :param message: The message of this HelloWorldResponseContent.  # noqa: E501
        :type message: str
        :param timestamp: The timestamp of this HelloWorldResponseContent.  # noqa: E501
        :type timestamp: float
        """
        self.openapi_types = {
            'message': str,
            'timestamp': float
        }

        self.attribute_map = {
            'message': 'message',
            'timestamp': 'timestamp'
        }

        self._message = message
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'HelloWorldResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HelloWorldResponseContent of this HelloWorldResponseContent.  # noqa: E501
        :rtype: HelloWorldResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this HelloWorldResponseContent.

        Hello message  # noqa: E501

        :return: The message of this HelloWorldResponseContent.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this HelloWorldResponseContent.

        Hello message  # noqa: E501

        :param message: The message of this HelloWorldResponseContent.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def timestamp(self) -> float:
        """Gets the timestamp of this HelloWorldResponseContent.

        Timestamp of the response  # noqa: E501

        :return: The timestamp of this HelloWorldResponseContent.
        :rtype: float
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: float):
        """Sets the timestamp of this HelloWorldResponseContent.

        Timestamp of the response  # noqa: E501

        :param timestamp: The timestamp of this HelloWorldResponseContent.
        :type timestamp: float
        """

        self._timestamp = timestamp
