#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.res_date_range import ResDateRange
from api.models.res_filter import ResFilter
from api.models.res_paginator import ResPaginator
from api.models.res_sort_by import ResSortBy
from api.models.virtual_desktop_base_os import VirtualDesktopBaseOs
from api import util

from api.models.res_date_range import ResDateRange  # noqa: E501
from api.models.res_filter import ResFilter  # noqa: E501
from api.models.res_paginator import ResPaginator  # noqa: E501
from api.models.res_sort_by import ResSortBy  # noqa: E501
from api.models.virtual_desktop_base_os import VirtualDesktopBaseOs  # noqa: E501

class ListSupportedOsesResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, paginator=None, sort_by=None, data_range=None, filters=None, listing=None):  # noqa: E501
        """ListSupportedOsesResponseContent - a model defined in OpenAPI

        :param paginator: The paginator of this ListSupportedOsesResponseContent.  # noqa: E501
        :type paginator: ResPaginator
        :param sort_by: The sort_by of this ListSupportedOsesResponseContent.  # noqa: E501
        :type sort_by: ResSortBy
        :param data_range: The data_range of this ListSupportedOsesResponseContent.  # noqa: E501
        :type data_range: ResDateRange
        :param filters: The filters of this ListSupportedOsesResponseContent.  # noqa: E501
        :type filters: List[ResFilter]
        :param listing: The listing of this ListSupportedOsesResponseContent.  # noqa: E501
        :type listing: List[VirtualDesktopBaseOs]
        """
        self.openapi_types = {
            'paginator': ResPaginator,
            'sort_by': ResSortBy,
            'data_range': ResDateRange,
            'filters': List[ResFilter],
            'listing': List[VirtualDesktopBaseOs]
        }

        self.attribute_map = {
            'paginator': 'paginator',
            'sort_by': 'sort_by',
            'data_range': 'data_range',
            'filters': 'filters',
            'listing': 'listing'
        }

        self._paginator = paginator
        self._sort_by = sort_by
        self._data_range = data_range
        self._filters = filters
        self._listing = listing

    @classmethod
    def from_dict(cls, dikt) -> 'ListSupportedOsesResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListSupportedOsesResponseContent of this ListSupportedOsesResponseContent.  # noqa: E501
        :rtype: ListSupportedOsesResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paginator(self) -> ResPaginator:
        """Gets the paginator of this ListSupportedOsesResponseContent.


        :return: The paginator of this ListSupportedOsesResponseContent.
        :rtype: ResPaginator
        """
        return self._paginator

    @paginator.setter
    def paginator(self, paginator: ResPaginator):
        """Sets the paginator of this ListSupportedOsesResponseContent.


        :param paginator: The paginator of this ListSupportedOsesResponseContent.
        :type paginator: ResPaginator
        """

        self._paginator = paginator

    @property
    def sort_by(self) -> ResSortBy:
        """Gets the sort_by of this ListSupportedOsesResponseContent.


        :return: The sort_by of this ListSupportedOsesResponseContent.
        :rtype: ResSortBy
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by: ResSortBy):
        """Sets the sort_by of this ListSupportedOsesResponseContent.


        :param sort_by: The sort_by of this ListSupportedOsesResponseContent.
        :type sort_by: ResSortBy
        """

        self._sort_by = sort_by

    @property
    def data_range(self) -> ResDateRange:
        """Gets the data_range of this ListSupportedOsesResponseContent.


        :return: The data_range of this ListSupportedOsesResponseContent.
        :rtype: ResDateRange
        """
        return self._data_range

    @data_range.setter
    def data_range(self, data_range: ResDateRange):
        """Sets the data_range of this ListSupportedOsesResponseContent.


        :param data_range: The data_range of this ListSupportedOsesResponseContent.
        :type data_range: ResDateRange
        """

        self._data_range = data_range

    @property
    def filters(self) -> List[ResFilter]:
        """Gets the filters of this ListSupportedOsesResponseContent.

        List of filters applied to the query  # noqa: E501

        :return: The filters of this ListSupportedOsesResponseContent.
        :rtype: List[ResFilter]
        """
        return self._filters

    @filters.setter
    def filters(self, filters: List[ResFilter]):
        """Sets the filters of this ListSupportedOsesResponseContent.

        List of filters applied to the query  # noqa: E501

        :param filters: The filters of this ListSupportedOsesResponseContent.
        :type filters: List[ResFilter]
        """

        self._filters = filters

    @property
    def listing(self) -> List[VirtualDesktopBaseOs]:
        """Gets the listing of this ListSupportedOsesResponseContent.

        List of available base operating systems for virtual desktops  # noqa: E501

        :return: The listing of this ListSupportedOsesResponseContent.
        :rtype: List[VirtualDesktopBaseOs]
        """
        return self._listing

    @listing.setter
    def listing(self, listing: List[VirtualDesktopBaseOs]):
        """Sets the listing of this ListSupportedOsesResponseContent.

        List of available base operating systems for virtual desktops  # noqa: E501

        :param listing: The listing of this ListSupportedOsesResponseContent.
        :type listing: List[VirtualDesktopBaseOs]
        """

        self._listing = listing
