#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack
from api import util

from api.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack  # noqa: E501

class ListAllowedInstanceTypesRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, hibernation_support=False, software_stack=None):  # noqa: E501
        """ListAllowedInstanceTypesRequestContent - a model defined in OpenAPI

        :param hibernation_support: The hibernation_support of this ListAllowedInstanceTypesRequestContent.  # noqa: E501
        :type hibernation_support: bool
        :param software_stack: The software_stack of this ListAllowedInstanceTypesRequestContent.  # noqa: E501
        :type software_stack: VirtualDesktopSoftwareStack
        """
        self.openapi_types = {
            'hibernation_support': bool,
            'software_stack': VirtualDesktopSoftwareStack
        }

        self.attribute_map = {
            'hibernation_support': 'hibernation_support',
            'software_stack': 'software_stack'
        }

        self._hibernation_support = hibernation_support
        self._software_stack = software_stack

    @classmethod
    def from_dict(cls, dikt) -> 'ListAllowedInstanceTypesRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListAllowedInstanceTypesRequestContent of this ListAllowedInstanceTypesRequestContent.  # noqa: E501
        :rtype: ListAllowedInstanceTypesRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hibernation_support(self) -> bool:
        """Gets the hibernation_support of this ListAllowedInstanceTypesRequestContent.

        Whether the instance types need to support hibernation  # noqa: E501

        :return: The hibernation_support of this ListAllowedInstanceTypesRequestContent.
        :rtype: bool
        """
        return self._hibernation_support

    @hibernation_support.setter
    def hibernation_support(self, hibernation_support: bool):
        """Sets the hibernation_support of this ListAllowedInstanceTypesRequestContent.

        Whether the instance types need to support hibernation  # noqa: E501

        :param hibernation_support: The hibernation_support of this ListAllowedInstanceTypesRequestContent.
        :type hibernation_support: bool
        """

        self._hibernation_support = hibernation_support

    @property
    def software_stack(self) -> VirtualDesktopSoftwareStack:
        """Gets the software_stack of this ListAllowedInstanceTypesRequestContent.


        :return: The software_stack of this ListAllowedInstanceTypesRequestContent.
        :rtype: VirtualDesktopSoftwareStack
        """
        return self._software_stack

    @software_stack.setter
    def software_stack(self, software_stack: VirtualDesktopSoftwareStack):
        """Sets the software_stack of this ListAllowedInstanceTypesRequestContent.


        :param software_stack: The software_stack of this ListAllowedInstanceTypesRequestContent.
        :type software_stack: VirtualDesktopSoftwareStack
        """

        self._software_stack = software_stack
