#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.res_sort_order import ResSortOrder
from api import util

from api.models.res_sort_order import ResSortOrder  # noqa: E501

class ResSortBy(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, key=None, order=None):  # noqa: E501
        """ResSortBy - a model defined in OpenAPI

        :param key: The key of this ResSortBy.  # noqa: E501
        :type key: str
        :param order: The order of this ResSortBy.  # noqa: E501
        :type order: ResSortOrder
        """
        self.openapi_types = {
            'key': str,
            'order': ResSortOrder
        }

        self.attribute_map = {
            'key': 'key',
            'order': 'order'
        }

        self._key = key
        self._order = order

    @classmethod
    def from_dict(cls, dikt) -> 'ResSortBy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResSortBy of this ResSortBy.  # noqa: E501
        :rtype: ResSortBy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this ResSortBy.

        The field key to sort by  # noqa: E501

        :return: The key of this ResSortBy.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this ResSortBy.

        The field key to sort by  # noqa: E501

        :param key: The key of this ResSortBy.
        :type key: str
        """

        self._key = key

    @property
    def order(self) -> ResSortOrder:
        """Gets the order of this ResSortBy.


        :return: The order of this ResSortBy.
        :rtype: ResSortOrder
        """
        return self._order

    @order.setter
    def order(self, order: ResSortOrder):
        """Sets the order of this ResSortBy.


        :param order: The order of this ResSortBy.
        :type order: ResSortOrder
        """

        self._order = order
