#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.list_value import ListValue
from api.models.string_value import StringValue
from api import util

from api.models.list_value import ListValue  # noqa: E501
from api.models.string_value import StringValue  # noqa: E501

class ResFilterValueStringOrList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, string_value=None, list_value=None):  # noqa: E501
        """ResFilterValueStringOrList - a model defined in OpenAPI

        :param string_value: The string_value of this ResFilterValueStringOrList.  # noqa: E501
        :type string_value: str
        :param list_value: The list_value of this ResFilterValueStringOrList.  # noqa: E501
        :type list_value: List[object]
        """
        self.openapi_types = {
            'string_value': str,
            'list_value': List[object]
        }

        self.attribute_map = {
            'string_value': 'stringValue',
            'list_value': 'listValue'
        }

        self._string_value = string_value
        self._list_value = list_value

    @classmethod
    def from_dict(cls, dikt) -> 'ResFilterValueStringOrList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResFilterValueStringOrList of this ResFilterValueStringOrList.  # noqa: E501
        :rtype: ResFilterValueStringOrList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def string_value(self) -> str:
        """Gets the string_value of this ResFilterValueStringOrList.


        :return: The string_value of this ResFilterValueStringOrList.
        :rtype: str
        """
        return self._string_value

    @string_value.setter
    def string_value(self, string_value: str):
        """Sets the string_value of this ResFilterValueStringOrList.


        :param string_value: The string_value of this ResFilterValueStringOrList.
        :type string_value: str
        """
        if string_value is None:
            raise ValueError("Invalid value for `string_value`, must not be `None`")  # noqa: E501

        self._string_value = string_value

    @property
    def list_value(self) -> List[object]:
        """Gets the list_value of this ResFilterValueStringOrList.

        List of filter values  # noqa: E501

        :return: The list_value of this ResFilterValueStringOrList.
        :rtype: List[object]
        """
        return self._list_value

    @list_value.setter
    def list_value(self, list_value: List[object]):
        """Sets the list_value of this ResFilterValueStringOrList.

        List of filter values  # noqa: E501

        :param list_value: The list_value of this ResFilterValueStringOrList.
        :type list_value: List[object]
        """
        if list_value is None:
            raise ValueError("Invalid value for `list_value`, must not be `None`")  # noqa: E501

        self._list_value = list_value
