#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.res_filter_value_string_or_list import ResFilterValueStringOrList
from api import util

from api.models.res_filter_value_string_or_list import ResFilterValueStringOrList  # noqa: E501

class ResFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, key=None, value=None, eq=None, _in=None, like=None, starts_with=None, ends_with=None, _and=None, _or=None):  # noqa: E501
        """ResFilter - a model defined in OpenAPI

        :param key: The key of this ResFilter.  # noqa: E501
        :type key: str
        :param value: The value of this ResFilter.  # noqa: E501
        :type value: object
        :param eq: The eq of this ResFilter.  # noqa: E501
        :type eq: object
        :param _in: The _in of this ResFilter.  # noqa: E501
        :type _in: ResFilterValueStringOrList
        :param like: The like of this ResFilter.  # noqa: E501
        :type like: str
        :param starts_with: The starts_with of this ResFilter.  # noqa: E501
        :type starts_with: str
        :param ends_with: The ends_with of this ResFilter.  # noqa: E501
        :type ends_with: str
        :param _and: The _and of this ResFilter.  # noqa: E501
        :type _and: List[ResFilter]
        :param _or: The _or of this ResFilter.  # noqa: E501
        :type _or: List[ResFilter]
        """
        self.openapi_types = {
            'key': str,
            'value': object,
            'eq': object,
            '_in': ResFilterValueStringOrList,
            'like': str,
            'starts_with': str,
            'ends_with': str,
            '_and': List[ResFilter],
            '_or': List[ResFilter]
        }

        self.attribute_map = {
            'key': 'key',
            'value': 'value',
            'eq': 'eq',
            '_in': 'in',
            'like': 'like',
            'starts_with': 'starts_with',
            'ends_with': 'ends_with',
            '_and': 'and',
            '_or': 'or'
        }

        self._key = key
        self._value = value
        self._eq = eq
        self.__in = _in
        self._like = like
        self._starts_with = starts_with
        self._ends_with = ends_with
        self.__and = _and
        self.__or = _or

    @classmethod
    def from_dict(cls, dikt) -> 'ResFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResFilter of this ResFilter.  # noqa: E501
        :rtype: ResFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this ResFilter.

        The field key to filter on  # noqa: E501

        :return: The key of this ResFilter.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this ResFilter.

        The field key to filter on  # noqa: E501

        :param key: The key of this ResFilter.
        :type key: str
        """

        self._key = key

    @property
    def value(self) -> object:
        """Gets the value of this ResFilter.

        Generic value for the filter  # noqa: E501

        :return: The value of this ResFilter.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """Sets the value of this ResFilter.

        Generic value for the filter  # noqa: E501

        :param value: The value of this ResFilter.
        :type value: object
        """

        self._value = value

    @property
    def eq(self) -> object:
        """Gets the eq of this ResFilter.

        Equality filter value  # noqa: E501

        :return: The eq of this ResFilter.
        :rtype: object
        """
        return self._eq

    @eq.setter
    def eq(self, eq: object):
        """Sets the eq of this ResFilter.

        Equality filter value  # noqa: E501

        :param eq: The eq of this ResFilter.
        :type eq: object
        """

        self._eq = eq

    @property
    def _in(self) -> ResFilterValueStringOrList:
        """Gets the _in of this ResFilter.


        :return: The _in of this ResFilter.
        :rtype: ResFilterValueStringOrList
        """
        return self.__in

    @_in.setter
    def _in(self, _in: ResFilterValueStringOrList):
        """Sets the _in of this ResFilter.


        :param _in: The _in of this ResFilter.
        :type _in: ResFilterValueStringOrList
        """

        self.__in = _in

    @property
    def like(self) -> str:
        """Gets the like of this ResFilter.

        Like pattern for string matching  # noqa: E501

        :return: The like of this ResFilter.
        :rtype: str
        """
        return self._like

    @like.setter
    def like(self, like: str):
        """Sets the like of this ResFilter.

        Like pattern for string matching  # noqa: E501

        :param like: The like of this ResFilter.
        :type like: str
        """

        self._like = like

    @property
    def starts_with(self) -> str:
        """Gets the starts_with of this ResFilter.

        Starts with pattern for string matching  # noqa: E501

        :return: The starts_with of this ResFilter.
        :rtype: str
        """
        return self._starts_with

    @starts_with.setter
    def starts_with(self, starts_with: str):
        """Sets the starts_with of this ResFilter.

        Starts with pattern for string matching  # noqa: E501

        :param starts_with: The starts_with of this ResFilter.
        :type starts_with: str
        """

        self._starts_with = starts_with

    @property
    def ends_with(self) -> str:
        """Gets the ends_with of this ResFilter.

        Ends with pattern for string matching  # noqa: E501

        :return: The ends_with of this ResFilter.
        :rtype: str
        """
        return self._ends_with

    @ends_with.setter
    def ends_with(self, ends_with: str):
        """Sets the ends_with of this ResFilter.

        Ends with pattern for string matching  # noqa: E501

        :param ends_with: The ends_with of this ResFilter.
        :type ends_with: str
        """

        self._ends_with = ends_with

    @property
    def _and(self) -> List[ResFilter]:
        """Gets the _and of this ResFilter.

        AND operation with nested filters  # noqa: E501

        :return: The _and of this ResFilter.
        :rtype: List[ResFilter]
        """
        return self.__and

    @_and.setter
    def _and(self, _and: List[ResFilter]):
        """Sets the _and of this ResFilter.

        AND operation with nested filters  # noqa: E501

        :param _and: The _and of this ResFilter.
        :type _and: List[ResFilter]
        """

        self.__and = _and

    @property
    def _or(self) -> List[ResFilter]:
        """Gets the _or of this ResFilter.

        OR operation with nested filters  # noqa: E501

        :return: The _or of this ResFilter.
        :rtype: List[ResFilter]
        """
        return self.__or

    @_or.setter
    def _or(self, _or: List[ResFilter]):
        """Sets the _or of this ResFilter.

        OR operation with nested filters  # noqa: E501

        :param _or: The _or of this ResFilter.
        :type _or: List[ResFilter]
        """

        self.__or = _or
