#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api import util


class StringValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, string_value=None):  # noqa: E501
        """StringValue - a model defined in OpenAPI

        :param string_value: The string_value of this StringValue.  # noqa: E501
        :type string_value: str
        """
        self.openapi_types = {
            'string_value': str
        }

        self.attribute_map = {
            'string_value': 'stringValue'
        }

        self._string_value = string_value

    @classmethod
    def from_dict(cls, dikt) -> 'StringValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The stringValue of this StringValue.  # noqa: E501
        :rtype: StringValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def string_value(self) -> str:
        """Gets the string_value of this StringValue.


        :return: The string_value of this StringValue.
        :rtype: str
        """
        return self._string_value

    @string_value.setter
    def string_value(self, string_value: str):
        """Sets the string_value of this StringValue.


        :param string_value: The string_value of this StringValue.
        :type string_value: str
        """
        if string_value is None:
            raise ValueError("Invalid value for `string_value`, must not be `None`")  # noqa: E501

        self._string_value = string_value
