#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.virtual_desktop_permission import VirtualDesktopPermission
from api import util

from api.models.virtual_desktop_permission import VirtualDesktopPermission  # noqa: E501

class VirtualDesktopPermissionProfile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, profile_id=None, title=None, description=None, permissions=None, created_on=None, updated_on=None):  # noqa: E501
        """VirtualDesktopPermissionProfile - a model defined in OpenAPI

        :param profile_id: The profile_id of this VirtualDesktopPermissionProfile.  # noqa: E501
        :type profile_id: str
        :param title: The title of this VirtualDesktopPermissionProfile.  # noqa: E501
        :type title: str
        :param description: The description of this VirtualDesktopPermissionProfile.  # noqa: E501
        :type description: str
        :param permissions: The permissions of this VirtualDesktopPermissionProfile.  # noqa: E501
        :type permissions: List[VirtualDesktopPermission]
        :param created_on: The created_on of this VirtualDesktopPermissionProfile.  # noqa: E501
        :type created_on: str
        :param updated_on: The updated_on of this VirtualDesktopPermissionProfile.  # noqa: E501
        :type updated_on: str
        """
        self.openapi_types = {
            'profile_id': str,
            'title': str,
            'description': str,
            'permissions': List[VirtualDesktopPermission],
            'created_on': str,
            'updated_on': str
        }

        self.attribute_map = {
            'profile_id': 'profile_id',
            'title': 'title',
            'description': 'description',
            'permissions': 'permissions',
            'created_on': 'created_on',
            'updated_on': 'updated_on'
        }

        self._profile_id = profile_id
        self._title = title
        self._description = description
        self._permissions = permissions
        self._created_on = created_on
        self._updated_on = updated_on

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopPermissionProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopPermissionProfile of this VirtualDesktopPermissionProfile.  # noqa: E501
        :rtype: VirtualDesktopPermissionProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def profile_id(self) -> str:
        """Gets the profile_id of this VirtualDesktopPermissionProfile.

        Profile identifier  # noqa: E501

        :return: The profile_id of this VirtualDesktopPermissionProfile.
        :rtype: str
        """
        return self._profile_id

    @profile_id.setter
    def profile_id(self, profile_id: str):
        """Sets the profile_id of this VirtualDesktopPermissionProfile.

        Profile identifier  # noqa: E501

        :param profile_id: The profile_id of this VirtualDesktopPermissionProfile.
        :type profile_id: str
        """

        self._profile_id = profile_id

    @property
    def title(self) -> str:
        """Gets the title of this VirtualDesktopPermissionProfile.

        Profile title  # noqa: E501

        :return: The title of this VirtualDesktopPermissionProfile.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this VirtualDesktopPermissionProfile.

        Profile title  # noqa: E501

        :param title: The title of this VirtualDesktopPermissionProfile.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this VirtualDesktopPermissionProfile.

        Profile description  # noqa: E501

        :return: The description of this VirtualDesktopPermissionProfile.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VirtualDesktopPermissionProfile.

        Profile description  # noqa: E501

        :param description: The description of this VirtualDesktopPermissionProfile.
        :type description: str
        """

        self._description = description

    @property
    def permissions(self) -> List[VirtualDesktopPermission]:
        """Gets the permissions of this VirtualDesktopPermissionProfile.

        List of permissions  # noqa: E501

        :return: The permissions of this VirtualDesktopPermissionProfile.
        :rtype: List[VirtualDesktopPermission]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions: List[VirtualDesktopPermission]):
        """Sets the permissions of this VirtualDesktopPermissionProfile.

        List of permissions  # noqa: E501

        :param permissions: The permissions of this VirtualDesktopPermissionProfile.
        :type permissions: List[VirtualDesktopPermission]
        """

        self._permissions = permissions

    @property
    def created_on(self) -> str:
        """Gets the created_on of this VirtualDesktopPermissionProfile.

        Creation timestamp  # noqa: E501

        :return: The created_on of this VirtualDesktopPermissionProfile.
        :rtype: str
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on: str):
        """Sets the created_on of this VirtualDesktopPermissionProfile.

        Creation timestamp  # noqa: E501

        :param created_on: The created_on of this VirtualDesktopPermissionProfile.
        :type created_on: str
        """

        self._created_on = created_on

    @property
    def updated_on(self) -> str:
        """Gets the updated_on of this VirtualDesktopPermissionProfile.

        Last update timestamp  # noqa: E501

        :return: The updated_on of this VirtualDesktopPermissionProfile.
        :rtype: str
        """
        return self._updated_on

    @updated_on.setter
    def updated_on(self, updated_on: str):
        """Sets the updated_on of this VirtualDesktopPermissionProfile.

        Last update timestamp  # noqa: E501

        :param updated_on: The updated_on of this VirtualDesktopPermissionProfile.
        :type updated_on: str
        """

        self._updated_on = updated_on
