#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.res_memory import ResMemory
from api import util

from api.models.res_memory import ResMemory  # noqa: E501

class VirtualDesktopServer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, server_id=None, idea_session_id=None, idea_session_owner=None, instance_id=None, instance_type=None, private_ip=None, private_dns_name=None, public_ip=None, public_dns_name=None, availability=None, unavailability_reason=None, console_session_count=None, virtual_session_count=None, max_concurrent_sessions_per_user=None, max_virtual_sessions=None, state=None, locked=None, root_volume_size=None, root_volume_iops=None, instance_profile_arn=None, security_groups=None, subnet_id=None, key_pair_name=None, is_idle=None):  # noqa: E501
        """VirtualDesktopServer - a model defined in OpenAPI

        :param server_id: The server_id of this VirtualDesktopServer.  # noqa: E501
        :type server_id: str
        :param idea_session_id: The idea_session_id of this VirtualDesktopServer.  # noqa: E501
        :type idea_session_id: str
        :param idea_session_owner: The idea_session_owner of this VirtualDesktopServer.  # noqa: E501
        :type idea_session_owner: str
        :param instance_id: The instance_id of this VirtualDesktopServer.  # noqa: E501
        :type instance_id: str
        :param instance_type: The instance_type of this VirtualDesktopServer.  # noqa: E501
        :type instance_type: str
        :param private_ip: The private_ip of this VirtualDesktopServer.  # noqa: E501
        :type private_ip: str
        :param private_dns_name: The private_dns_name of this VirtualDesktopServer.  # noqa: E501
        :type private_dns_name: str
        :param public_ip: The public_ip of this VirtualDesktopServer.  # noqa: E501
        :type public_ip: str
        :param public_dns_name: The public_dns_name of this VirtualDesktopServer.  # noqa: E501
        :type public_dns_name: str
        :param availability: The availability of this VirtualDesktopServer.  # noqa: E501
        :type availability: str
        :param unavailability_reason: The unavailability_reason of this VirtualDesktopServer.  # noqa: E501
        :type unavailability_reason: str
        :param console_session_count: The console_session_count of this VirtualDesktopServer.  # noqa: E501
        :type console_session_count: int
        :param virtual_session_count: The virtual_session_count of this VirtualDesktopServer.  # noqa: E501
        :type virtual_session_count: int
        :param max_concurrent_sessions_per_user: The max_concurrent_sessions_per_user of this VirtualDesktopServer.  # noqa: E501
        :type max_concurrent_sessions_per_user: int
        :param max_virtual_sessions: The max_virtual_sessions of this VirtualDesktopServer.  # noqa: E501
        :type max_virtual_sessions: int
        :param state: The state of this VirtualDesktopServer.  # noqa: E501
        :type state: str
        :param locked: The locked of this VirtualDesktopServer.  # noqa: E501
        :type locked: bool
        :param root_volume_size: The root_volume_size of this VirtualDesktopServer.  # noqa: E501
        :type root_volume_size: ResMemory
        :param root_volume_iops: The root_volume_iops of this VirtualDesktopServer.  # noqa: E501
        :type root_volume_iops: int
        :param instance_profile_arn: The instance_profile_arn of this VirtualDesktopServer.  # noqa: E501
        :type instance_profile_arn: str
        :param security_groups: The security_groups of this VirtualDesktopServer.  # noqa: E501
        :type security_groups: List[str]
        :param subnet_id: The subnet_id of this VirtualDesktopServer.  # noqa: E501
        :type subnet_id: str
        :param key_pair_name: The key_pair_name of this VirtualDesktopServer.  # noqa: E501
        :type key_pair_name: str
        :param is_idle: The is_idle of this VirtualDesktopServer.  # noqa: E501
        :type is_idle: bool
        """
        self.openapi_types = {
            'server_id': str,
            'idea_session_id': str,
            'idea_session_owner': str,
            'instance_id': str,
            'instance_type': str,
            'private_ip': str,
            'private_dns_name': str,
            'public_ip': str,
            'public_dns_name': str,
            'availability': str,
            'unavailability_reason': str,
            'console_session_count': int,
            'virtual_session_count': int,
            'max_concurrent_sessions_per_user': int,
            'max_virtual_sessions': int,
            'state': str,
            'locked': bool,
            'root_volume_size': ResMemory,
            'root_volume_iops': int,
            'instance_profile_arn': str,
            'security_groups': List[str],
            'subnet_id': str,
            'key_pair_name': str,
            'is_idle': bool
        }

        self.attribute_map = {
            'server_id': 'server_id',
            'idea_session_id': 'idea_session_id',
            'idea_session_owner': 'idea_session_owner',
            'instance_id': 'instance_id',
            'instance_type': 'instance_type',
            'private_ip': 'private_ip',
            'private_dns_name': 'private_dns_name',
            'public_ip': 'public_ip',
            'public_dns_name': 'public_dns_name',
            'availability': 'availability',
            'unavailability_reason': 'unavailability_reason',
            'console_session_count': 'console_session_count',
            'virtual_session_count': 'virtual_session_count',
            'max_concurrent_sessions_per_user': 'max_concurrent_sessions_per_user',
            'max_virtual_sessions': 'max_virtual_sessions',
            'state': 'state',
            'locked': 'locked',
            'root_volume_size': 'root_volume_size',
            'root_volume_iops': 'root_volume_iops',
            'instance_profile_arn': 'instance_profile_arn',
            'security_groups': 'security_groups',
            'subnet_id': 'subnet_id',
            'key_pair_name': 'key_pair_name',
            'is_idle': 'is_idle'
        }

        self._server_id = server_id
        self._idea_session_id = idea_session_id
        self._idea_session_owner = idea_session_owner
        self._instance_id = instance_id
        self._instance_type = instance_type
        self._private_ip = private_ip
        self._private_dns_name = private_dns_name
        self._public_ip = public_ip
        self._public_dns_name = public_dns_name
        self._availability = availability
        self._unavailability_reason = unavailability_reason
        self._console_session_count = console_session_count
        self._virtual_session_count = virtual_session_count
        self._max_concurrent_sessions_per_user = max_concurrent_sessions_per_user
        self._max_virtual_sessions = max_virtual_sessions
        self._state = state
        self._locked = locked
        self._root_volume_size = root_volume_size
        self._root_volume_iops = root_volume_iops
        self._instance_profile_arn = instance_profile_arn
        self._security_groups = security_groups
        self._subnet_id = subnet_id
        self._key_pair_name = key_pair_name
        self._is_idle = is_idle

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopServer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopServer of this VirtualDesktopServer.  # noqa: E501
        :rtype: VirtualDesktopServer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def server_id(self) -> str:
        """Gets the server_id of this VirtualDesktopServer.

        Unique server identifier  # noqa: E501

        :return: The server_id of this VirtualDesktopServer.
        :rtype: str
        """
        return self._server_id

    @server_id.setter
    def server_id(self, server_id: str):
        """Sets the server_id of this VirtualDesktopServer.

        Unique server identifier  # noqa: E501

        :param server_id: The server_id of this VirtualDesktopServer.
        :type server_id: str
        """

        self._server_id = server_id

    @property
    def idea_session_id(self) -> str:
        """Gets the idea_session_id of this VirtualDesktopServer.

        IDEA session ID associated with this server  # noqa: E501

        :return: The idea_session_id of this VirtualDesktopServer.
        :rtype: str
        """
        return self._idea_session_id

    @idea_session_id.setter
    def idea_session_id(self, idea_session_id: str):
        """Sets the idea_session_id of this VirtualDesktopServer.

        IDEA session ID associated with this server  # noqa: E501

        :param idea_session_id: The idea_session_id of this VirtualDesktopServer.
        :type idea_session_id: str
        """

        self._idea_session_id = idea_session_id

    @property
    def idea_session_owner(self) -> str:
        """Gets the idea_session_owner of this VirtualDesktopServer.

        Session owner  # noqa: E501

        :return: The idea_session_owner of this VirtualDesktopServer.
        :rtype: str
        """
        return self._idea_session_owner

    @idea_session_owner.setter
    def idea_session_owner(self, idea_session_owner: str):
        """Sets the idea_session_owner of this VirtualDesktopServer.

        Session owner  # noqa: E501

        :param idea_session_owner: The idea_session_owner of this VirtualDesktopServer.
        :type idea_session_owner: str
        """

        self._idea_session_owner = idea_session_owner

    @property
    def instance_id(self) -> str:
        """Gets the instance_id of this VirtualDesktopServer.

        EC2 instance ID  # noqa: E501

        :return: The instance_id of this VirtualDesktopServer.
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id: str):
        """Sets the instance_id of this VirtualDesktopServer.

        EC2 instance ID  # noqa: E501

        :param instance_id: The instance_id of this VirtualDesktopServer.
        :type instance_id: str
        """

        self._instance_id = instance_id

    @property
    def instance_type(self) -> str:
        """Gets the instance_type of this VirtualDesktopServer.

        EC2 instance type  # noqa: E501

        :return: The instance_type of this VirtualDesktopServer.
        :rtype: str
        """
        return self._instance_type

    @instance_type.setter
    def instance_type(self, instance_type: str):
        """Sets the instance_type of this VirtualDesktopServer.

        EC2 instance type  # noqa: E501

        :param instance_type: The instance_type of this VirtualDesktopServer.
        :type instance_type: str
        """

        self._instance_type = instance_type

    @property
    def private_ip(self) -> str:
        """Gets the private_ip of this VirtualDesktopServer.

        Private IP address  # noqa: E501

        :return: The private_ip of this VirtualDesktopServer.
        :rtype: str
        """
        return self._private_ip

    @private_ip.setter
    def private_ip(self, private_ip: str):
        """Sets the private_ip of this VirtualDesktopServer.

        Private IP address  # noqa: E501

        :param private_ip: The private_ip of this VirtualDesktopServer.
        :type private_ip: str
        """

        self._private_ip = private_ip

    @property
    def private_dns_name(self) -> str:
        """Gets the private_dns_name of this VirtualDesktopServer.

        Private DNS name  # noqa: E501

        :return: The private_dns_name of this VirtualDesktopServer.
        :rtype: str
        """
        return self._private_dns_name

    @private_dns_name.setter
    def private_dns_name(self, private_dns_name: str):
        """Sets the private_dns_name of this VirtualDesktopServer.

        Private DNS name  # noqa: E501

        :param private_dns_name: The private_dns_name of this VirtualDesktopServer.
        :type private_dns_name: str
        """

        self._private_dns_name = private_dns_name

    @property
    def public_ip(self) -> str:
        """Gets the public_ip of this VirtualDesktopServer.

        Public IP address  # noqa: E501

        :return: The public_ip of this VirtualDesktopServer.
        :rtype: str
        """
        return self._public_ip

    @public_ip.setter
    def public_ip(self, public_ip: str):
        """Sets the public_ip of this VirtualDesktopServer.

        Public IP address  # noqa: E501

        :param public_ip: The public_ip of this VirtualDesktopServer.
        :type public_ip: str
        """

        self._public_ip = public_ip

    @property
    def public_dns_name(self) -> str:
        """Gets the public_dns_name of this VirtualDesktopServer.

        Public DNS name  # noqa: E501

        :return: The public_dns_name of this VirtualDesktopServer.
        :rtype: str
        """
        return self._public_dns_name

    @public_dns_name.setter
    def public_dns_name(self, public_dns_name: str):
        """Sets the public_dns_name of this VirtualDesktopServer.

        Public DNS name  # noqa: E501

        :param public_dns_name: The public_dns_name of this VirtualDesktopServer.
        :type public_dns_name: str
        """

        self._public_dns_name = public_dns_name

    @property
    def availability(self) -> str:
        """Gets the availability of this VirtualDesktopServer.

        Server availability status  # noqa: E501

        :return: The availability of this VirtualDesktopServer.
        :rtype: str
        """
        return self._availability

    @availability.setter
    def availability(self, availability: str):
        """Sets the availability of this VirtualDesktopServer.

        Server availability status  # noqa: E501

        :param availability: The availability of this VirtualDesktopServer.
        :type availability: str
        """

        self._availability = availability

    @property
    def unavailability_reason(self) -> str:
        """Gets the unavailability_reason of this VirtualDesktopServer.

        Reason for server unavailability  # noqa: E501

        :return: The unavailability_reason of this VirtualDesktopServer.
        :rtype: str
        """
        return self._unavailability_reason

    @unavailability_reason.setter
    def unavailability_reason(self, unavailability_reason: str):
        """Sets the unavailability_reason of this VirtualDesktopServer.

        Reason for server unavailability  # noqa: E501

        :param unavailability_reason: The unavailability_reason of this VirtualDesktopServer.
        :type unavailability_reason: str
        """

        self._unavailability_reason = unavailability_reason

    @property
    def console_session_count(self) -> int:
        """Gets the console_session_count of this VirtualDesktopServer.

        Number of console sessions  # noqa: E501

        :return: The console_session_count of this VirtualDesktopServer.
        :rtype: int
        """
        return self._console_session_count

    @console_session_count.setter
    def console_session_count(self, console_session_count: int):
        """Sets the console_session_count of this VirtualDesktopServer.

        Number of console sessions  # noqa: E501

        :param console_session_count: The console_session_count of this VirtualDesktopServer.
        :type console_session_count: int
        """

        self._console_session_count = console_session_count

    @property
    def virtual_session_count(self) -> int:
        """Gets the virtual_session_count of this VirtualDesktopServer.

        Number of virtual sessions  # noqa: E501

        :return: The virtual_session_count of this VirtualDesktopServer.
        :rtype: int
        """
        return self._virtual_session_count

    @virtual_session_count.setter
    def virtual_session_count(self, virtual_session_count: int):
        """Sets the virtual_session_count of this VirtualDesktopServer.

        Number of virtual sessions  # noqa: E501

        :param virtual_session_count: The virtual_session_count of this VirtualDesktopServer.
        :type virtual_session_count: int
        """

        self._virtual_session_count = virtual_session_count

    @property
    def max_concurrent_sessions_per_user(self) -> int:
        """Gets the max_concurrent_sessions_per_user of this VirtualDesktopServer.

        Maximum concurrent sessions per user  # noqa: E501

        :return: The max_concurrent_sessions_per_user of this VirtualDesktopServer.
        :rtype: int
        """
        return self._max_concurrent_sessions_per_user

    @max_concurrent_sessions_per_user.setter
    def max_concurrent_sessions_per_user(self, max_concurrent_sessions_per_user: int):
        """Sets the max_concurrent_sessions_per_user of this VirtualDesktopServer.

        Maximum concurrent sessions per user  # noqa: E501

        :param max_concurrent_sessions_per_user: The max_concurrent_sessions_per_user of this VirtualDesktopServer.
        :type max_concurrent_sessions_per_user: int
        """

        self._max_concurrent_sessions_per_user = max_concurrent_sessions_per_user

    @property
    def max_virtual_sessions(self) -> int:
        """Gets the max_virtual_sessions of this VirtualDesktopServer.

        Maximum virtual sessions  # noqa: E501

        :return: The max_virtual_sessions of this VirtualDesktopServer.
        :rtype: int
        """
        return self._max_virtual_sessions

    @max_virtual_sessions.setter
    def max_virtual_sessions(self, max_virtual_sessions: int):
        """Sets the max_virtual_sessions of this VirtualDesktopServer.

        Maximum virtual sessions  # noqa: E501

        :param max_virtual_sessions: The max_virtual_sessions of this VirtualDesktopServer.
        :type max_virtual_sessions: int
        """

        self._max_virtual_sessions = max_virtual_sessions

    @property
    def state(self) -> str:
        """Gets the state of this VirtualDesktopServer.

        Server state  # noqa: E501

        :return: The state of this VirtualDesktopServer.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this VirtualDesktopServer.

        Server state  # noqa: E501

        :param state: The state of this VirtualDesktopServer.
        :type state: str
        """

        self._state = state

    @property
    def locked(self) -> bool:
        """Gets the locked of this VirtualDesktopServer.

        Whether the server is locked  # noqa: E501

        :return: The locked of this VirtualDesktopServer.
        :rtype: bool
        """
        return self._locked

    @locked.setter
    def locked(self, locked: bool):
        """Sets the locked of this VirtualDesktopServer.

        Whether the server is locked  # noqa: E501

        :param locked: The locked of this VirtualDesktopServer.
        :type locked: bool
        """

        self._locked = locked

    @property
    def root_volume_size(self) -> ResMemory:
        """Gets the root_volume_size of this VirtualDesktopServer.


        :return: The root_volume_size of this VirtualDesktopServer.
        :rtype: ResMemory
        """
        return self._root_volume_size

    @root_volume_size.setter
    def root_volume_size(self, root_volume_size: ResMemory):
        """Sets the root_volume_size of this VirtualDesktopServer.


        :param root_volume_size: The root_volume_size of this VirtualDesktopServer.
        :type root_volume_size: ResMemory
        """

        self._root_volume_size = root_volume_size

    @property
    def root_volume_iops(self) -> int:
        """Gets the root_volume_iops of this VirtualDesktopServer.

        Root volume IOPS  # noqa: E501

        :return: The root_volume_iops of this VirtualDesktopServer.
        :rtype: int
        """
        return self._root_volume_iops

    @root_volume_iops.setter
    def root_volume_iops(self, root_volume_iops: int):
        """Sets the root_volume_iops of this VirtualDesktopServer.

        Root volume IOPS  # noqa: E501

        :param root_volume_iops: The root_volume_iops of this VirtualDesktopServer.
        :type root_volume_iops: int
        """

        self._root_volume_iops = root_volume_iops

    @property
    def instance_profile_arn(self) -> str:
        """Gets the instance_profile_arn of this VirtualDesktopServer.

        Instance profile ARN  # noqa: E501

        :return: The instance_profile_arn of this VirtualDesktopServer.
        :rtype: str
        """
        return self._instance_profile_arn

    @instance_profile_arn.setter
    def instance_profile_arn(self, instance_profile_arn: str):
        """Sets the instance_profile_arn of this VirtualDesktopServer.

        Instance profile ARN  # noqa: E501

        :param instance_profile_arn: The instance_profile_arn of this VirtualDesktopServer.
        :type instance_profile_arn: str
        """

        self._instance_profile_arn = instance_profile_arn

    @property
    def security_groups(self) -> List[str]:
        """Gets the security_groups of this VirtualDesktopServer.

        Security group IDs  # noqa: E501

        :return: The security_groups of this VirtualDesktopServer.
        :rtype: List[str]
        """
        return self._security_groups

    @security_groups.setter
    def security_groups(self, security_groups: List[str]):
        """Sets the security_groups of this VirtualDesktopServer.

        Security group IDs  # noqa: E501

        :param security_groups: The security_groups of this VirtualDesktopServer.
        :type security_groups: List[str]
        """

        self._security_groups = security_groups

    @property
    def subnet_id(self) -> str:
        """Gets the subnet_id of this VirtualDesktopServer.

        Subnet ID  # noqa: E501

        :return: The subnet_id of this VirtualDesktopServer.
        :rtype: str
        """
        return self._subnet_id

    @subnet_id.setter
    def subnet_id(self, subnet_id: str):
        """Sets the subnet_id of this VirtualDesktopServer.

        Subnet ID  # noqa: E501

        :param subnet_id: The subnet_id of this VirtualDesktopServer.
        :type subnet_id: str
        """

        self._subnet_id = subnet_id

    @property
    def key_pair_name(self) -> str:
        """Gets the key_pair_name of this VirtualDesktopServer.

        Key pair name  # noqa: E501

        :return: The key_pair_name of this VirtualDesktopServer.
        :rtype: str
        """
        return self._key_pair_name

    @key_pair_name.setter
    def key_pair_name(self, key_pair_name: str):
        """Sets the key_pair_name of this VirtualDesktopServer.

        Key pair name  # noqa: E501

        :param key_pair_name: The key_pair_name of this VirtualDesktopServer.
        :type key_pair_name: str
        """

        self._key_pair_name = key_pair_name

    @property
    def is_idle(self) -> bool:
        """Gets the is_idle of this VirtualDesktopServer.

        Whether the server is idle  # noqa: E501

        :return: The is_idle of this VirtualDesktopServer.
        :rtype: bool
        """
        return self._is_idle

    @is_idle.setter
    def is_idle(self, is_idle: bool):
        """Sets the is_idle of this VirtualDesktopServer.

        Whether the server is idle  # noqa: E501

        :param is_idle: The is_idle of this VirtualDesktopServer.
        :type is_idle: bool
        """

        self._is_idle = is_idle
