#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.day_of_week import DayOfWeek
from api.models.virtual_desktop_schedule_type import VirtualDesktopScheduleType
from api import util

from api.models.day_of_week import DayOfWeek  # noqa: E501
from api.models.virtual_desktop_schedule_type import VirtualDesktopScheduleType  # noqa: E501

class VirtualDesktopSchedule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, schedule_id=None, idea_session_id=None, idea_session_owner=None, day_of_week=None, start_up_time=None, shut_down_time=None, schedule_type=None):  # noqa: E501
        """VirtualDesktopSchedule - a model defined in OpenAPI

        :param schedule_id: The schedule_id of this VirtualDesktopSchedule.  # noqa: E501
        :type schedule_id: str
        :param idea_session_id: The idea_session_id of this VirtualDesktopSchedule.  # noqa: E501
        :type idea_session_id: str
        :param idea_session_owner: The idea_session_owner of this VirtualDesktopSchedule.  # noqa: E501
        :type idea_session_owner: str
        :param day_of_week: The day_of_week of this VirtualDesktopSchedule.  # noqa: E501
        :type day_of_week: DayOfWeek
        :param start_up_time: The start_up_time of this VirtualDesktopSchedule.  # noqa: E501
        :type start_up_time: str
        :param shut_down_time: The shut_down_time of this VirtualDesktopSchedule.  # noqa: E501
        :type shut_down_time: str
        :param schedule_type: The schedule_type of this VirtualDesktopSchedule.  # noqa: E501
        :type schedule_type: VirtualDesktopScheduleType
        """
        self.openapi_types = {
            'schedule_id': str,
            'idea_session_id': str,
            'idea_session_owner': str,
            'day_of_week': DayOfWeek,
            'start_up_time': str,
            'shut_down_time': str,
            'schedule_type': VirtualDesktopScheduleType
        }

        self.attribute_map = {
            'schedule_id': 'schedule_id',
            'idea_session_id': 'idea_session_id',
            'idea_session_owner': 'idea_session_owner',
            'day_of_week': 'day_of_week',
            'start_up_time': 'start_up_time',
            'shut_down_time': 'shut_down_time',
            'schedule_type': 'schedule_type'
        }

        self._schedule_id = schedule_id
        self._idea_session_id = idea_session_id
        self._idea_session_owner = idea_session_owner
        self._day_of_week = day_of_week
        self._start_up_time = start_up_time
        self._shut_down_time = shut_down_time
        self._schedule_type = schedule_type

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopSchedule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopSchedule of this VirtualDesktopSchedule.  # noqa: E501
        :rtype: VirtualDesktopSchedule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def schedule_id(self) -> str:
        """Gets the schedule_id of this VirtualDesktopSchedule.

        Schedule identifier  # noqa: E501

        :return: The schedule_id of this VirtualDesktopSchedule.
        :rtype: str
        """
        return self._schedule_id

    @schedule_id.setter
    def schedule_id(self, schedule_id: str):
        """Sets the schedule_id of this VirtualDesktopSchedule.

        Schedule identifier  # noqa: E501

        :param schedule_id: The schedule_id of this VirtualDesktopSchedule.
        :type schedule_id: str
        """

        self._schedule_id = schedule_id

    @property
    def idea_session_id(self) -> str:
        """Gets the idea_session_id of this VirtualDesktopSchedule.

        IDEA session ID  # noqa: E501

        :return: The idea_session_id of this VirtualDesktopSchedule.
        :rtype: str
        """
        return self._idea_session_id

    @idea_session_id.setter
    def idea_session_id(self, idea_session_id: str):
        """Sets the idea_session_id of this VirtualDesktopSchedule.

        IDEA session ID  # noqa: E501

        :param idea_session_id: The idea_session_id of this VirtualDesktopSchedule.
        :type idea_session_id: str
        """

        self._idea_session_id = idea_session_id

    @property
    def idea_session_owner(self) -> str:
        """Gets the idea_session_owner of this VirtualDesktopSchedule.

        Session owner  # noqa: E501

        :return: The idea_session_owner of this VirtualDesktopSchedule.
        :rtype: str
        """
        return self._idea_session_owner

    @idea_session_owner.setter
    def idea_session_owner(self, idea_session_owner: str):
        """Sets the idea_session_owner of this VirtualDesktopSchedule.

        Session owner  # noqa: E501

        :param idea_session_owner: The idea_session_owner of this VirtualDesktopSchedule.
        :type idea_session_owner: str
        """

        self._idea_session_owner = idea_session_owner

    @property
    def day_of_week(self) -> DayOfWeek:
        """Gets the day_of_week of this VirtualDesktopSchedule.


        :return: The day_of_week of this VirtualDesktopSchedule.
        :rtype: DayOfWeek
        """
        return self._day_of_week

    @day_of_week.setter
    def day_of_week(self, day_of_week: DayOfWeek):
        """Sets the day_of_week of this VirtualDesktopSchedule.


        :param day_of_week: The day_of_week of this VirtualDesktopSchedule.
        :type day_of_week: DayOfWeek
        """

        self._day_of_week = day_of_week

    @property
    def start_up_time(self) -> str:
        """Gets the start_up_time of this VirtualDesktopSchedule.

        Start up time of day (e.g. 09:00)  # noqa: E501

        :return: The start_up_time of this VirtualDesktopSchedule.
        :rtype: str
        """
        return self._start_up_time

    @start_up_time.setter
    def start_up_time(self, start_up_time: str):
        """Sets the start_up_time of this VirtualDesktopSchedule.

        Start up time of day (e.g. 09:00)  # noqa: E501

        :param start_up_time: The start_up_time of this VirtualDesktopSchedule.
        :type start_up_time: str
        """

        self._start_up_time = start_up_time

    @property
    def shut_down_time(self) -> str:
        """Gets the shut_down_time of this VirtualDesktopSchedule.

        Shut down time of day (e.g. 17:30)  # noqa: E501

        :return: The shut_down_time of this VirtualDesktopSchedule.
        :rtype: str
        """
        return self._shut_down_time

    @shut_down_time.setter
    def shut_down_time(self, shut_down_time: str):
        """Sets the shut_down_time of this VirtualDesktopSchedule.

        Shut down time of day (e.g. 17:30)  # noqa: E501

        :param shut_down_time: The shut_down_time of this VirtualDesktopSchedule.
        :type shut_down_time: str
        """

        self._shut_down_time = shut_down_time

    @property
    def schedule_type(self) -> VirtualDesktopScheduleType:
        """Gets the schedule_type of this VirtualDesktopSchedule.


        :return: The schedule_type of this VirtualDesktopSchedule.
        :rtype: VirtualDesktopScheduleType
        """
        return self._schedule_type

    @schedule_type.setter
    def schedule_type(self, schedule_type: VirtualDesktopScheduleType):
        """Sets the schedule_type of this VirtualDesktopSchedule.


        :param schedule_type: The schedule_type of this VirtualDesktopSchedule.
        :type schedule_type: VirtualDesktopScheduleType
        """

        self._schedule_type = schedule_type
