#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.project import Project
from api.models.virtual_desktop_base_os import VirtualDesktopBaseOs
from api.models.virtual_desktop_server import VirtualDesktopServer
from api.models.virtual_desktop_session_state import VirtualDesktopSessionState
from api.models.virtual_desktop_session_type import VirtualDesktopSessionType
from api.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack
from api.models.virtual_desktop_week_schedule import VirtualDesktopWeekSchedule
from api import util

from api.models.project import Project  # noqa: E501
from api.models.virtual_desktop_base_os import VirtualDesktopBaseOs  # noqa: E501
from api.models.virtual_desktop_server import VirtualDesktopServer  # noqa: E501
from api.models.virtual_desktop_session_state import VirtualDesktopSessionState  # noqa: E501
from api.models.virtual_desktop_session_type import VirtualDesktopSessionType  # noqa: E501
from api.models.virtual_desktop_software_stack import VirtualDesktopSoftwareStack  # noqa: E501
from api.models.virtual_desktop_week_schedule import VirtualDesktopWeekSchedule  # noqa: E501

class VirtualDesktopSession(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dcv_session_id=None, idea_session_id=None, base_os=None, name=None, owner=None, type=None, server=None, created_on=None, updated_on=None, state=None, description=None, software_stack=None, project=None, schedule=None, connection_count=None, force=None, hibernation_enabled=None, is_launched_by_admin=None, locked=None, tags=None, logins=None, is_idle=None, failure_reason=None):  # noqa: E501
        """VirtualDesktopSession - a model defined in OpenAPI

        :param dcv_session_id: The dcv_session_id of this VirtualDesktopSession.  # noqa: E501
        :type dcv_session_id: str
        :param idea_session_id: The idea_session_id of this VirtualDesktopSession.  # noqa: E501
        :type idea_session_id: str
        :param base_os: The base_os of this VirtualDesktopSession.  # noqa: E501
        :type base_os: VirtualDesktopBaseOs
        :param name: The name of this VirtualDesktopSession.  # noqa: E501
        :type name: str
        :param owner: The owner of this VirtualDesktopSession.  # noqa: E501
        :type owner: str
        :param type: The type of this VirtualDesktopSession.  # noqa: E501
        :type type: VirtualDesktopSessionType
        :param server: The server of this VirtualDesktopSession.  # noqa: E501
        :type server: VirtualDesktopServer
        :param created_on: The created_on of this VirtualDesktopSession.  # noqa: E501
        :type created_on: str
        :param updated_on: The updated_on of this VirtualDesktopSession.  # noqa: E501
        :type updated_on: str
        :param state: The state of this VirtualDesktopSession.  # noqa: E501
        :type state: VirtualDesktopSessionState
        :param description: The description of this VirtualDesktopSession.  # noqa: E501
        :type description: str
        :param software_stack: The software_stack of this VirtualDesktopSession.  # noqa: E501
        :type software_stack: VirtualDesktopSoftwareStack
        :param project: The project of this VirtualDesktopSession.  # noqa: E501
        :type project: Project
        :param schedule: The schedule of this VirtualDesktopSession.  # noqa: E501
        :type schedule: VirtualDesktopWeekSchedule
        :param connection_count: The connection_count of this VirtualDesktopSession.  # noqa: E501
        :type connection_count: int
        :param force: The force of this VirtualDesktopSession.  # noqa: E501
        :type force: bool
        :param hibernation_enabled: The hibernation_enabled of this VirtualDesktopSession.  # noqa: E501
        :type hibernation_enabled: bool
        :param is_launched_by_admin: The is_launched_by_admin of this VirtualDesktopSession.  # noqa: E501
        :type is_launched_by_admin: bool
        :param locked: The locked of this VirtualDesktopSession.  # noqa: E501
        :type locked: bool
        :param tags: The tags of this VirtualDesktopSession.  # noqa: E501
        :type tags: List[object]
        :param logins: The logins of this VirtualDesktopSession.  # noqa: E501
        :type logins: List[str]
        :param is_idle: The is_idle of this VirtualDesktopSession.  # noqa: E501
        :type is_idle: bool
        :param failure_reason: The failure_reason of this VirtualDesktopSession.  # noqa: E501
        :type failure_reason: str
        """
        self.openapi_types = {
            'dcv_session_id': str,
            'idea_session_id': str,
            'base_os': VirtualDesktopBaseOs,
            'name': str,
            'owner': str,
            'type': VirtualDesktopSessionType,
            'server': VirtualDesktopServer,
            'created_on': str,
            'updated_on': str,
            'state': VirtualDesktopSessionState,
            'description': str,
            'software_stack': VirtualDesktopSoftwareStack,
            'project': Project,
            'schedule': VirtualDesktopWeekSchedule,
            'connection_count': int,
            'force': bool,
            'hibernation_enabled': bool,
            'is_launched_by_admin': bool,
            'locked': bool,
            'tags': List[object],
            'logins': List[str],
            'is_idle': bool,
            'failure_reason': str
        }

        self.attribute_map = {
            'dcv_session_id': 'dcv_session_id',
            'idea_session_id': 'idea_session_id',
            'base_os': 'base_os',
            'name': 'name',
            'owner': 'owner',
            'type': 'type',
            'server': 'server',
            'created_on': 'created_on',
            'updated_on': 'updated_on',
            'state': 'state',
            'description': 'description',
            'software_stack': 'software_stack',
            'project': 'project',
            'schedule': 'schedule',
            'connection_count': 'connection_count',
            'force': 'force',
            'hibernation_enabled': 'hibernation_enabled',
            'is_launched_by_admin': 'is_launched_by_admin',
            'locked': 'locked',
            'tags': 'tags',
            'logins': 'logins',
            'is_idle': 'is_idle',
            'failure_reason': 'failure_reason'
        }

        self._dcv_session_id = dcv_session_id
        self._idea_session_id = idea_session_id
        self._base_os = base_os
        self._name = name
        self._owner = owner
        self._type = type
        self._server = server
        self._created_on = created_on
        self._updated_on = updated_on
        self._state = state
        self._description = description
        self._software_stack = software_stack
        self._project = project
        self._schedule = schedule
        self._connection_count = connection_count
        self._force = force
        self._hibernation_enabled = hibernation_enabled
        self._is_launched_by_admin = is_launched_by_admin
        self._locked = locked
        self._tags = tags
        self._logins = logins
        self._is_idle = is_idle
        self._failure_reason = failure_reason

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopSession':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopSession of this VirtualDesktopSession.  # noqa: E501
        :rtype: VirtualDesktopSession
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dcv_session_id(self) -> str:
        """Gets the dcv_session_id of this VirtualDesktopSession.

        DCV session identifier  # noqa: E501

        :return: The dcv_session_id of this VirtualDesktopSession.
        :rtype: str
        """
        return self._dcv_session_id

    @dcv_session_id.setter
    def dcv_session_id(self, dcv_session_id: str):
        """Sets the dcv_session_id of this VirtualDesktopSession.

        DCV session identifier  # noqa: E501

        :param dcv_session_id: The dcv_session_id of this VirtualDesktopSession.
        :type dcv_session_id: str
        """

        self._dcv_session_id = dcv_session_id

    @property
    def idea_session_id(self) -> str:
        """Gets the idea_session_id of this VirtualDesktopSession.

        IDEA session identifier  # noqa: E501

        :return: The idea_session_id of this VirtualDesktopSession.
        :rtype: str
        """
        return self._idea_session_id

    @idea_session_id.setter
    def idea_session_id(self, idea_session_id: str):
        """Sets the idea_session_id of this VirtualDesktopSession.

        IDEA session identifier  # noqa: E501

        :param idea_session_id: The idea_session_id of this VirtualDesktopSession.
        :type idea_session_id: str
        """

        self._idea_session_id = idea_session_id

    @property
    def base_os(self) -> VirtualDesktopBaseOs:
        """Gets the base_os of this VirtualDesktopSession.


        :return: The base_os of this VirtualDesktopSession.
        :rtype: VirtualDesktopBaseOs
        """
        return self._base_os

    @base_os.setter
    def base_os(self, base_os: VirtualDesktopBaseOs):
        """Sets the base_os of this VirtualDesktopSession.


        :param base_os: The base_os of this VirtualDesktopSession.
        :type base_os: VirtualDesktopBaseOs
        """

        self._base_os = base_os

    @property
    def name(self) -> str:
        """Gets the name of this VirtualDesktopSession.

        Session name  # noqa: E501

        :return: The name of this VirtualDesktopSession.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VirtualDesktopSession.

        Session name  # noqa: E501

        :param name: The name of this VirtualDesktopSession.
        :type name: str
        """

        self._name = name

    @property
    def owner(self) -> str:
        """Gets the owner of this VirtualDesktopSession.

        Session owner  # noqa: E501

        :return: The owner of this VirtualDesktopSession.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner: str):
        """Sets the owner of this VirtualDesktopSession.

        Session owner  # noqa: E501

        :param owner: The owner of this VirtualDesktopSession.
        :type owner: str
        """

        self._owner = owner

    @property
    def type(self) -> VirtualDesktopSessionType:
        """Gets the type of this VirtualDesktopSession.


        :return: The type of this VirtualDesktopSession.
        :rtype: VirtualDesktopSessionType
        """
        return self._type

    @type.setter
    def type(self, type: VirtualDesktopSessionType):
        """Sets the type of this VirtualDesktopSession.


        :param type: The type of this VirtualDesktopSession.
        :type type: VirtualDesktopSessionType
        """

        self._type = type

    @property
    def server(self) -> VirtualDesktopServer:
        """Gets the server of this VirtualDesktopSession.


        :return: The server of this VirtualDesktopSession.
        :rtype: VirtualDesktopServer
        """
        return self._server

    @server.setter
    def server(self, server: VirtualDesktopServer):
        """Sets the server of this VirtualDesktopSession.


        :param server: The server of this VirtualDesktopSession.
        :type server: VirtualDesktopServer
        """

        self._server = server

    @property
    def created_on(self) -> str:
        """Gets the created_on of this VirtualDesktopSession.

        Timestamp when the session was created  # noqa: E501

        :return: The created_on of this VirtualDesktopSession.
        :rtype: str
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on: str):
        """Sets the created_on of this VirtualDesktopSession.

        Timestamp when the session was created  # noqa: E501

        :param created_on: The created_on of this VirtualDesktopSession.
        :type created_on: str
        """

        self._created_on = created_on

    @property
    def updated_on(self) -> str:
        """Gets the updated_on of this VirtualDesktopSession.

        Timestamp when the session was last updated  # noqa: E501

        :return: The updated_on of this VirtualDesktopSession.
        :rtype: str
        """
        return self._updated_on

    @updated_on.setter
    def updated_on(self, updated_on: str):
        """Sets the updated_on of this VirtualDesktopSession.

        Timestamp when the session was last updated  # noqa: E501

        :param updated_on: The updated_on of this VirtualDesktopSession.
        :type updated_on: str
        """

        self._updated_on = updated_on

    @property
    def state(self) -> VirtualDesktopSessionState:
        """Gets the state of this VirtualDesktopSession.


        :return: The state of this VirtualDesktopSession.
        :rtype: VirtualDesktopSessionState
        """
        return self._state

    @state.setter
    def state(self, state: VirtualDesktopSessionState):
        """Sets the state of this VirtualDesktopSession.


        :param state: The state of this VirtualDesktopSession.
        :type state: VirtualDesktopSessionState
        """

        self._state = state

    @property
    def description(self) -> str:
        """Gets the description of this VirtualDesktopSession.

        Session description  # noqa: E501

        :return: The description of this VirtualDesktopSession.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VirtualDesktopSession.

        Session description  # noqa: E501

        :param description: The description of this VirtualDesktopSession.
        :type description: str
        """

        self._description = description

    @property
    def software_stack(self) -> VirtualDesktopSoftwareStack:
        """Gets the software_stack of this VirtualDesktopSession.


        :return: The software_stack of this VirtualDesktopSession.
        :rtype: VirtualDesktopSoftwareStack
        """
        return self._software_stack

    @software_stack.setter
    def software_stack(self, software_stack: VirtualDesktopSoftwareStack):
        """Sets the software_stack of this VirtualDesktopSession.


        :param software_stack: The software_stack of this VirtualDesktopSession.
        :type software_stack: VirtualDesktopSoftwareStack
        """
        if software_stack is None:
            raise ValueError("Invalid value for `software_stack`, must not be `None`")  # noqa: E501

        self._software_stack = software_stack

    @property
    def project(self) -> Project:
        """Gets the project of this VirtualDesktopSession.


        :return: The project of this VirtualDesktopSession.
        :rtype: Project
        """
        return self._project

    @project.setter
    def project(self, project: Project):
        """Sets the project of this VirtualDesktopSession.


        :param project: The project of this VirtualDesktopSession.
        :type project: Project
        """

        self._project = project

    @property
    def schedule(self) -> VirtualDesktopWeekSchedule:
        """Gets the schedule of this VirtualDesktopSession.


        :return: The schedule of this VirtualDesktopSession.
        :rtype: VirtualDesktopWeekSchedule
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule: VirtualDesktopWeekSchedule):
        """Sets the schedule of this VirtualDesktopSession.


        :param schedule: The schedule of this VirtualDesktopSession.
        :type schedule: VirtualDesktopWeekSchedule
        """

        self._schedule = schedule

    @property
    def connection_count(self) -> int:
        """Gets the connection_count of this VirtualDesktopSession.

        Number of active connections  # noqa: E501

        :return: The connection_count of this VirtualDesktopSession.
        :rtype: int
        """
        return self._connection_count

    @connection_count.setter
    def connection_count(self, connection_count: int):
        """Sets the connection_count of this VirtualDesktopSession.

        Number of active connections  # noqa: E501

        :param connection_count: The connection_count of this VirtualDesktopSession.
        :type connection_count: int
        """

        self._connection_count = connection_count

    @property
    def force(self) -> bool:
        """Gets the force of this VirtualDesktopSession.

        Force flag  # noqa: E501

        :return: The force of this VirtualDesktopSession.
        :rtype: bool
        """
        return self._force

    @force.setter
    def force(self, force: bool):
        """Sets the force of this VirtualDesktopSession.

        Force flag  # noqa: E501

        :param force: The force of this VirtualDesktopSession.
        :type force: bool
        """

        self._force = force

    @property
    def hibernation_enabled(self) -> bool:
        """Gets the hibernation_enabled of this VirtualDesktopSession.

        Whether hibernation is enabled  # noqa: E501

        :return: The hibernation_enabled of this VirtualDesktopSession.
        :rtype: bool
        """
        return self._hibernation_enabled

    @hibernation_enabled.setter
    def hibernation_enabled(self, hibernation_enabled: bool):
        """Sets the hibernation_enabled of this VirtualDesktopSession.

        Whether hibernation is enabled  # noqa: E501

        :param hibernation_enabled: The hibernation_enabled of this VirtualDesktopSession.
        :type hibernation_enabled: bool
        """
        if hibernation_enabled is None:
            raise ValueError("Invalid value for `hibernation_enabled`, must not be `None`")  # noqa: E501

        self._hibernation_enabled = hibernation_enabled

    @property
    def is_launched_by_admin(self) -> bool:
        """Gets the is_launched_by_admin of this VirtualDesktopSession.

        Whether the session was launched by an admin  # noqa: E501

        :return: The is_launched_by_admin of this VirtualDesktopSession.
        :rtype: bool
        """
        return self._is_launched_by_admin

    @is_launched_by_admin.setter
    def is_launched_by_admin(self, is_launched_by_admin: bool):
        """Sets the is_launched_by_admin of this VirtualDesktopSession.

        Whether the session was launched by an admin  # noqa: E501

        :param is_launched_by_admin: The is_launched_by_admin of this VirtualDesktopSession.
        :type is_launched_by_admin: bool
        """

        self._is_launched_by_admin = is_launched_by_admin

    @property
    def locked(self) -> bool:
        """Gets the locked of this VirtualDesktopSession.

        Whether the session is locked  # noqa: E501

        :return: The locked of this VirtualDesktopSession.
        :rtype: bool
        """
        return self._locked

    @locked.setter
    def locked(self, locked: bool):
        """Sets the locked of this VirtualDesktopSession.

        Whether the session is locked  # noqa: E501

        :param locked: The locked of this VirtualDesktopSession.
        :type locked: bool
        """

        self._locked = locked

    @property
    def tags(self) -> List[object]:
        """Gets the tags of this VirtualDesktopSession.

        Session tags  # noqa: E501

        :return: The tags of this VirtualDesktopSession.
        :rtype: List[object]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[object]):
        """Sets the tags of this VirtualDesktopSession.

        Session tags  # noqa: E501

        :param tags: The tags of this VirtualDesktopSession.
        :type tags: List[object]
        """

        self._tags = tags

    @property
    def logins(self) -> List[str]:
        """Gets the logins of this VirtualDesktopSession.

        List of allowed logins  # noqa: E501

        :return: The logins of this VirtualDesktopSession.
        :rtype: List[str]
        """
        return self._logins

    @logins.setter
    def logins(self, logins: List[str]):
        """Sets the logins of this VirtualDesktopSession.

        List of allowed logins  # noqa: E501

        :param logins: The logins of this VirtualDesktopSession.
        :type logins: List[str]
        """

        self._logins = logins

    @property
    def is_idle(self) -> bool:
        """Gets the is_idle of this VirtualDesktopSession.

        Whether the session is idle  # noqa: E501

        :return: The is_idle of this VirtualDesktopSession.
        :rtype: bool
        """
        return self._is_idle

    @is_idle.setter
    def is_idle(self, is_idle: bool):
        """Sets the is_idle of this VirtualDesktopSession.

        Whether the session is idle  # noqa: E501

        :param is_idle: The is_idle of this VirtualDesktopSession.
        :type is_idle: bool
        """

        self._is_idle = is_idle

    @property
    def failure_reason(self) -> str:
        """Gets the failure_reason of this VirtualDesktopSession.

        Failure reason for transient API responses  # noqa: E501

        :return: The failure_reason of this VirtualDesktopSession.
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason: str):
        """Sets the failure_reason of this VirtualDesktopSession.

        Failure reason for transient API responses  # noqa: E501

        :param failure_reason: The failure_reason of this VirtualDesktopSession.
        :type failure_reason: str
        """

        self._failure_reason = failure_reason
