#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api.models.virtual_desktop_schedule import VirtualDesktopSchedule
from api import util

from api.models.virtual_desktop_schedule import VirtualDesktopSchedule  # noqa: E501

class VirtualDesktopWeekSchedule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, monday=None, tuesday=None, wednesday=None, thursday=None, friday=None, saturday=None, sunday=None):  # noqa: E501
        """VirtualDesktopWeekSchedule - a model defined in OpenAPI

        :param monday: The monday of this VirtualDesktopWeekSchedule.  # noqa: E501
        :type monday: VirtualDesktopSchedule
        :param tuesday: The tuesday of this VirtualDesktopWeekSchedule.  # noqa: E501
        :type tuesday: VirtualDesktopSchedule
        :param wednesday: The wednesday of this VirtualDesktopWeekSchedule.  # noqa: E501
        :type wednesday: VirtualDesktopSchedule
        :param thursday: The thursday of this VirtualDesktopWeekSchedule.  # noqa: E501
        :type thursday: VirtualDesktopSchedule
        :param friday: The friday of this VirtualDesktopWeekSchedule.  # noqa: E501
        :type friday: VirtualDesktopSchedule
        :param saturday: The saturday of this VirtualDesktopWeekSchedule.  # noqa: E501
        :type saturday: VirtualDesktopSchedule
        :param sunday: The sunday of this VirtualDesktopWeekSchedule.  # noqa: E501
        :type sunday: VirtualDesktopSchedule
        """
        self.openapi_types = {
            'monday': VirtualDesktopSchedule,
            'tuesday': VirtualDesktopSchedule,
            'wednesday': VirtualDesktopSchedule,
            'thursday': VirtualDesktopSchedule,
            'friday': VirtualDesktopSchedule,
            'saturday': VirtualDesktopSchedule,
            'sunday': VirtualDesktopSchedule
        }

        self.attribute_map = {
            'monday': 'monday',
            'tuesday': 'tuesday',
            'wednesday': 'wednesday',
            'thursday': 'thursday',
            'friday': 'friday',
            'saturday': 'saturday',
            'sunday': 'sunday'
        }

        self._monday = monday
        self._tuesday = tuesday
        self._wednesday = wednesday
        self._thursday = thursday
        self._friday = friday
        self._saturday = saturday
        self._sunday = sunday

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualDesktopWeekSchedule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualDesktopWeekSchedule of this VirtualDesktopWeekSchedule.  # noqa: E501
        :rtype: VirtualDesktopWeekSchedule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def monday(self) -> VirtualDesktopSchedule:
        """Gets the monday of this VirtualDesktopWeekSchedule.


        :return: The monday of this VirtualDesktopWeekSchedule.
        :rtype: VirtualDesktopSchedule
        """
        return self._monday

    @monday.setter
    def monday(self, monday: VirtualDesktopSchedule):
        """Sets the monday of this VirtualDesktopWeekSchedule.


        :param monday: The monday of this VirtualDesktopWeekSchedule.
        :type monday: VirtualDesktopSchedule
        """

        self._monday = monday

    @property
    def tuesday(self) -> VirtualDesktopSchedule:
        """Gets the tuesday of this VirtualDesktopWeekSchedule.


        :return: The tuesday of this VirtualDesktopWeekSchedule.
        :rtype: VirtualDesktopSchedule
        """
        return self._tuesday

    @tuesday.setter
    def tuesday(self, tuesday: VirtualDesktopSchedule):
        """Sets the tuesday of this VirtualDesktopWeekSchedule.


        :param tuesday: The tuesday of this VirtualDesktopWeekSchedule.
        :type tuesday: VirtualDesktopSchedule
        """

        self._tuesday = tuesday

    @property
    def wednesday(self) -> VirtualDesktopSchedule:
        """Gets the wednesday of this VirtualDesktopWeekSchedule.


        :return: The wednesday of this VirtualDesktopWeekSchedule.
        :rtype: VirtualDesktopSchedule
        """
        return self._wednesday

    @wednesday.setter
    def wednesday(self, wednesday: VirtualDesktopSchedule):
        """Sets the wednesday of this VirtualDesktopWeekSchedule.


        :param wednesday: The wednesday of this VirtualDesktopWeekSchedule.
        :type wednesday: VirtualDesktopSchedule
        """

        self._wednesday = wednesday

    @property
    def thursday(self) -> VirtualDesktopSchedule:
        """Gets the thursday of this VirtualDesktopWeekSchedule.


        :return: The thursday of this VirtualDesktopWeekSchedule.
        :rtype: VirtualDesktopSchedule
        """
        return self._thursday

    @thursday.setter
    def thursday(self, thursday: VirtualDesktopSchedule):
        """Sets the thursday of this VirtualDesktopWeekSchedule.


        :param thursday: The thursday of this VirtualDesktopWeekSchedule.
        :type thursday: VirtualDesktopSchedule
        """

        self._thursday = thursday

    @property
    def friday(self) -> VirtualDesktopSchedule:
        """Gets the friday of this VirtualDesktopWeekSchedule.


        :return: The friday of this VirtualDesktopWeekSchedule.
        :rtype: VirtualDesktopSchedule
        """
        return self._friday

    @friday.setter
    def friday(self, friday: VirtualDesktopSchedule):
        """Sets the friday of this VirtualDesktopWeekSchedule.


        :param friday: The friday of this VirtualDesktopWeekSchedule.
        :type friday: VirtualDesktopSchedule
        """

        self._friday = friday

    @property
    def saturday(self) -> VirtualDesktopSchedule:
        """Gets the saturday of this VirtualDesktopWeekSchedule.


        :return: The saturday of this VirtualDesktopWeekSchedule.
        :rtype: VirtualDesktopSchedule
        """
        return self._saturday

    @saturday.setter
    def saturday(self, saturday: VirtualDesktopSchedule):
        """Sets the saturday of this VirtualDesktopWeekSchedule.


        :param saturday: The saturday of this VirtualDesktopWeekSchedule.
        :type saturday: VirtualDesktopSchedule
        """

        self._saturday = saturday

    @property
    def sunday(self) -> VirtualDesktopSchedule:
        """Gets the sunday of this VirtualDesktopWeekSchedule.


        :return: The sunday of this VirtualDesktopWeekSchedule.
        :rtype: VirtualDesktopSchedule
        """
        return self._sunday

    @sunday.setter
    def sunday(self, sunday: VirtualDesktopSchedule):
        """Sets the sunday of this VirtualDesktopWeekSchedule.


        :param sunday: The sunday of this VirtualDesktopWeekSchedule.
        :type sunday: VirtualDesktopSchedule
        """

        self._sunday = sunday
