amazonlinux2:
  arm64:
    default-description: Amazon Linux 2 - ARM64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: Amazon Linux 2 - ARM64
    default-allowed-instance-types:
    - m6g
    ap-northeast-1:
    - ami-id: ami-0d6c4a34641cd51d3
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0333d6d8cd3c40082
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-056489e4882a1039f
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0fe1e53378423d816
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0ff84d9b437eb7846
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0173905b67d0feaa5
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0ac50bc63255402f8
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-02daeb05d8402fd74
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0a3f22760351cb5e0
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-00490cba4921496b7
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0bfaa5be9e1019cdd
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0cdc7c345f553c981
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-06218419d46afee90
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-05a91a997663a07f6
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0f9537a2c06bec67d
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-0f92a3f4bcd2f3fb4
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0988057aaf2cd6a23
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0ca84e223d380d50a
      ss-id-suffix: base
  x86-64:
    default-description: Amazon Linux 2 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: Amazon Linux 2 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-026b5ddea758521fe
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0e4f2a1b8f55a8acd
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0b8e60a84f14ce5a3
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0b7a76751c38161e0
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0efef54e960e4e17f
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0d4b1cc4fca195315
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-07cb013c9ecc583f0
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0c66be8c9de421368
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-079d2fd19ecbdb754
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-08a28be5eae6c1d68
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0e5ab72a6bf9765cd
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-002090e223e4263bb
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0a3b5ae607ce0295e
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0c104f6f4a5d9d1d5
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0a31834d359d68156
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-06c442589e803c7ab
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-038d74967dbfcdee5
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-065212a60f30e3798
      ss-id-suffix: base
rhel8:
  x86-64:
    default-description: RHEL8 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: RHEL8 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-074de61ca96feeba2
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0f66f3a9a39c0fbcb
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-09517580784d9c004
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-04d8a3e2be3ff0347
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0fd97caf35d4b312a
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-015ebf0b179dcb89d
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0e9d43a315dacbce6
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-01ca22628cc67f286
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0903c87e955b3bad7
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0d628e1985075adf0
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-06f1dbd45ea749dc1
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-077a684c356aa3275
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-045a0e581d015b76d
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0258229bf3cd8af20
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-02e7b2e016e3f158a
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-035337afa3ba3650b
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0cc438016ac0f31a5
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-08a3957682dc34c0b
      ss-id-suffix: base
ubuntu2204:
  x86-64:
    default-description: UBUNTU2204 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: UBUNTU2204 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-010a4b0c2749001f5
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0971bbf8821e02505
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-088fef2c0bae96cfc
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-034e98a9624d125c4
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-090389d25e1d5aaa6
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0e21b5f0dfb8ac907
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-035f91feb765a0ee1
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-08983c375f11aaac5
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0247bb40cddd738a5
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-073151717783c9ea5
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0431ce328feea0d11
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0bcd1fe1c81d279a5
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0aa886db793a6e808
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0f9575d3d509bae0c
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-00eab7ecccb541f63
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-0158011b8a9e6533f
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0d92b9e5e9f58b958
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0181d6b00c4160daf
      ss-id-suffix: base
rhel9:
  x86-64:
    default-description: RHEL9 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: RHEL9 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0a3299a47e8a9111b
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-09810edf6c4f708dc
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-04708942c263d8190
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0371cc1c8b8e24fdc
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0ade3fd7d152f84df
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-04978032a1284973a
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-076433a70aba7f25d
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-01d565a5f2da42e6f
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-04064cf7aeb268613
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-049b0abf844cab8d7
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-08c3913593117726b
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0bd23a7080ec75f4d
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-03e22ac0ee7ce0d08
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-023c11a32b0207432
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0ef50c2b2eb330511
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-0e980350222c32e74
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0e534e4c6bae7faf7
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-04b4d3355a2e2a403
      ss-id-suffix: base
windows:
  x86-64:
    default-description: Windows - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: Windows - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-09aa5aa9960830408
      ss-id-suffix: base
    - ami-id: ami-0c216418be26140f0
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-070ffbbbc446087f0
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    ap-northeast-2:
    - ami-id: ami-0c8efbd0de607dba9
      ss-id-suffix: base
    - ami-id: ami-060366bb891a0d9b3
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    ap-south-1:
    - ami-id: ami-0ff1117c58634a033
      ss-id-suffix: base
    - ami-id: ami-09597da154f1f7467
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    ap-southeast-1:
    - ami-id: ami-097849f949b6645df
      ss-id-suffix: base
    - ami-id: ami-02e4537badf5bec05
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    ap-southeast-2:
    - ami-id: ami-0b3a9f205adb6a9bd
      ss-id-suffix: base
    - ami-id: ami-0b325064fab711628
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    ca-central-1:
    - ami-id: ami-07e2d9926b8333cfa
      ss-id-suffix: base
    - ami-id: ami-0fb8cdaedf778978f
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-0a20341e8f8723a98
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    eu-central-1:
    - ami-id: ami-0f9de0e6547613419
      ss-id-suffix: base
    - ami-id: ami-02f68df0880c1f397
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-03b78a72de9ee07ef
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    eu-north-1:
    - ami-id: ami-04d24c9028df70ed9
      ss-id-suffix: base
    - ami-id: ami-00299a4678ee77a09
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    eu-south-1:
    - ami-id: ami-0be2afdf7b5eec278
      ss-id-suffix: base
    - ami-id: ami-0f597fff4ef0d2060
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    eu-west-1:
    - ami-id: ami-01ad3e8d5daba94d3
      ss-id-suffix: base
    - ami-id: ami-0729b45f956a22f19
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-07316ad5cf203db6c
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    eu-west-2:
    - ami-id: ami-0bfcfb387a0cdf713
      ss-id-suffix: base
    - ami-id: ami-0b7ebce89ff8d2128
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-0c331334b07b921ad
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    eu-west-3:
    - ami-id: ami-089443ca5f2fc51f3
      ss-id-suffix: base
    - ami-id: ami-084575f3f366d40ea
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    us-east-1:
    - ami-id: ami-06244562918e090e8
      ss-id-suffix: base
    - ami-id: ami-0c204e78e7e8c343b
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-06871ff48caabe79e
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    us-east-2:
    - ami-id: ami-021f003e3636a6f30
      ss-id-suffix: base
    - ami-id: ami-0249fa55e0cdfad19
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-0037c4d2fd44f63aa
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    us-west-1:
    - ami-id: ami-04dbb1c61ff241748
      ss-id-suffix: base
    - ami-id: ami-0e2655fc8958f3bb8
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
    us-west-2:
    - ami-id: ami-0c3d03c46ddcbed18
      ss-id-suffix: base
    - ami-id: ami-03265ce81c5c184e4
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
      allowed-instance-types:
      - g4ad
    - ami-id: ami-049332112750cf05b
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
      allowed-instance-types:
      - g4dn
      - g5
