amzn2023:
  arm64:
    default-description: AL2023 - ARM64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: AL2023 - ARM64
    default-allowed-instance-types:
    - m6g
    ap-northeast-1:
    - ami-id: ami-060ed83c8b95375e2
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0ab38814a224c51c1
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0758a5ff2cd0a6642
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-07c8b91119c5b1b1e
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0c7aee202a3a5b09a
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0d2316cef187452bf
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-0ba103f2cf9a3bd8a
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0f6ab32f1de097ee6
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0ff8810585b183659
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0c970865204fdb801
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0dda566f4d25474c5
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-05f8b52b73ea4f384
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0577776b28f5fa178
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0a7d22992868dade7
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0f21cd571235f1f4d
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0f769ce103c6cf8a0
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-008016473a33eb632
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-0e5508516240be818
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-09317ccfac89b432d
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0f2fdb6865b8e3983
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-077af5b7f0cad3d4c
      default: Y
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-0a78e5274b7986484
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0c4abb990a614dadc
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-04e51e1cc2b75647e
      ss-id-suffix: base
  x86-64:
    default-description: AL2023 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: AL2023 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0b9e39b1fe1c62cac
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-06882388850fd4a12
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-085a2e1351169ba01
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0d15e9052c94acb75
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0835cef4452581dc0
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0d309527510a8a0d2
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-0e3bdbbb7e5f18687
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0b36052818f03d0cb
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0f82f408f5558e47b
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0ecc79fb44c0b5dc4
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0ef91fd8b3791aac0
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0efd219d91e121387
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-062a8901a5ddcf280
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0de87753593ec47fd
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0961b69edb47951c9
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0b3dad5509b9e88ac
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-0df6aa23903f06b06
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-0c153b1b27542dbd5
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0bdc7d025135d7b49
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0742fcde83639b335
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-014bf1b4b82c73a7f
      default: Y
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-0c3c05fdd8bd53e3b
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0dcea41720906e07c
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-072f44400e27b9115
      ss-id-suffix: base
ubuntu2204:
  x86-64:
    default-description: UBUNTU2204 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: UBUNTU2204 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-07b4cf80e7d0a1829
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-012a353bb3afb92ee
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0b36f90f1d89dd6f6
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0aa761682283b4cc8
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-06afb763249172368
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-033bcb92ad88967d2
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-04e519602800d1662
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-02192c4f930e1ddb7
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-063adc3091e7180b9
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0ae88d5843aab690d
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-03c1c093c5c9344ab
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0e042949ef871f509
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-02cc1d87cd15bbf7b
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0d30b6a4d95baf37f
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0e8d619f32b216044
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0008ee1401791cdd4
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-066aefb9693cfbd7f
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-0a8d820d3a2ad655a
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-06e78a71af43ef21a
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-052110b0cc1b500e2
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-00e39050826b587ae
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-0397f68f3817206af
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-058bb94ace0a016a9
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0eb3161272dc9c6eb
      ss-id-suffix: base
ubuntu2404:
  x86-64:
    default-description: UBUNTU2404 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: UBUNTU2404 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0e239f7f4b3226722
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-05fa22e12f2cb12aa
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0c8a26158cbe3462e
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-07e5ce642bbc48c0d
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0ed6a65b84536f6ce
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0eb87ec7ecb669408
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-006ab9896c8737ec5
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0369ebd2c156b1d29
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0d52b1845903f6df7
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-04bc554a9635a77c8
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0cda11afd45b74b89
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-03ca3ec276739af09
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-08c7a4b4f234dfa77
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-01029182857b20417
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0c1002cdaa7a0954f
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0bc9367b83fb51b80
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-0f1da3b0bb18ed1be
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-031a45ebb21af623a
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-052355af2a014bd2c
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0dc6aa44dbcdd872e
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-077ab3d0a99f7e4e1
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0ac74609c6396bed3
      ss-id-suffix: base
rhel9:
  x86-64:
    default-description: RHEL9 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: RHEL9 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-04869bf1fd456d78f
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-034401e7a75c10236
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0375e6156dc4cba90
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-017b4fa3558f4268e
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0ace6c94b5ab2e659
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-00d0b8cb2af9f3b09
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-06ddcb7dd5dfb03de
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0c31da6a26f7dbf9f
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0583f44fed5a1a5c0
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-035f430eefe0c383c
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0398f6e695f104fe4
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0e9fba74af1b28b23
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0d47676200d7fcb26
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0393dcaeccbfa094f
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-00b48edeb4aa07242
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0d35fa9de3fce17eb
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-048d21bb0d69b31b3
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-019569d0da922d589
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0225644bfadc204f7
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0fa0cf9725e3938ae
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-07dda77c7f593b130
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-0c1d8aee4713e7bae
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0fd6ac6c5f71fe86e
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-02990c099b7180454
      ss-id-suffix: base
rocky9:
  x86-64:
    default-description: Rocky9 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: Rocky9 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0f762a1d14ff0e6cb
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0514e5d311a74d68a
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0a8f08229b59c0225
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0ef5ed7f4cfd103f1
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-061dd1267e7b3fca4
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0a37c1e50b4b9f9bf
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-0f34b3c7e7790af8d
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-09e61751aa9008dc0
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-048df6c5b8f47be2a
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0c420049f14d5b7c9
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-086e0ab189429afee
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-084dcba306d924b73
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0737993690fbf1215
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0c5283cba7f33b21b
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-00a7327ab907c2d52
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-03033b4c45b0ef67b
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-03102da6cb6cc7c39
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-07dbf8b6563f5acda
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0a5e563b87d8a92e0
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0077ea0d1a8b35e1e
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-06c2d7e460002336d
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0c5dc805f1647acbf
      ss-id-suffix: base
windows:
  x86-64:
    default-description: Windows - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: Windows - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-08135cadd4593276b
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-06ed1b89c20ada5c6
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0c6997e598e4944ba
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0340d2c0eb945bf80
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-05357f3b297a176d6
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0d50718a549a2bc15
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-031b16ae0fbefbb10
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-02ad2b97b9188f44f
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0e0342aed01cd1e23
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-05bf02f3ff4b4bfca
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-059d87b5f9e68f6fe
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0266f805a064dfffd
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0e2ea34cbea1aa9ee
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0fb748704e97da252
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0d5022d42654f9ce8
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0cd00dd5f2f97b714
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-09a1e9c0692f09023
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-028c1b2359ba963be
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0ed0165f19a049904
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0a309571b4f421554
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-07388959dc952435a
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-037613a54b9f6541a
      ss-id-suffix: base
