amzn2023:
  arm64:
    default-description: AL2023 - ARM64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: AL2023 - ARM64
    default-allowed-instance-types:
    - m6g
    ap-northeast-1:
    - ami-id: ami-01fec6097b327bbce
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-097913a70d9668327
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0325b91cbf56a6708
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-07c687ff88f7820e6
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0469a81a8271485e8
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-08d966145e3bb62be
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-01a8a2e2c41a2167f
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0335dfc4c963a8cce
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-086da02c58c89768d
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0bb1934e84af31b71
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-08dd99dd3489c8806
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-039c0e31385ba42d5
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0075e80a491268493
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-03b9fc3a0623de656
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-059085e02e995b968
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0265b0355c2b070e4
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-008016473a33eb632
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-030b097b971eca6db
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-06d5c141ec5b90893
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-01233be22f6657077
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-0b1b5e1ae54fb69e1
      default: Y
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-023640f7905fd065f
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-08bdac2eca4c8ad98
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-08c28b6151a0ba92f
      ss-id-suffix: base
  x86-64:
    default-description: AL2023 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: AL2023 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-08f122f8e6e9d868f
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-010502f62836f0c67
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-050e19643b8e4a951
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-085c5e1d88d722545
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-05b741ae2ab9f1742
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-024050934c1c66b27
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-0b1a7d9fc455877c5
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-04032a1a46e6cce85
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0344a23c782460e34
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-036bdae36143a955f
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-048a4ba4502b46dd7
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-093fbcd9ec41a255d
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-07da2223cc32a6898
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0272ade54c4f22c84
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-01f71c6770cfff327
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-01a7bea286eb84096
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-0df6aa23903f06b06
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-032dfc01c7f1df070
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-01bda64f81b5f8e4f
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-097a65b0520ee672f
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-001f5163d903ef5dd
      default: Y
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-059a7766742eefb2e
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-031776b784341ba93
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-00563078bca04e287
      ss-id-suffix: base
ubuntu2204:
  x86-64:
    default-description: UBUNTU2204 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: UBUNTU2204 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0379a1f991c2beceb
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0596f7562954deb8e
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-074e887b4a8f0a4d1
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-07b301a23def3266d
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0a010a0312b1400ee
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0e04e402c10e358ef
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-090813c1b06f13dba
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-02b4907e4bd874327
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0ce67f36025e17786
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0c905937c14bd22b0
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0eed6a7e3bd86ff98
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-06e46ee9bb3d8f688
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-017d3e24afcd69bab
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-02b81edd0fb821197
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-073bfc958ad7786ad
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-03a5ec5af9624ca11
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-066aefb9693cfbd7f
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-0f9115282727a06b5
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-02fd066b86800f60c
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0d03e71aa609a9ffa
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-04636581d28bcfd9e
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-0fbd43b89783e4368
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-00e0c7cb3b1822981
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0ababc7e5826abb79
      ss-id-suffix: base
ubuntu2404:
  x86-64:
    default-description: UBUNTU2404 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: UBUNTU2404 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0bf052f8a9dd8bf42
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-08d212701172cba2a
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-03dda1c40c7812d68
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0c54f8b78468b2ba2
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-04592e28abc2b9fc9
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-09a977aafd83c55e7
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-07dc53065d17edee7
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0d06e21ef1f9969b8
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-024208b0e77830ebe
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0a1856b54e6f47c20
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0122da1d0b4a30ec4
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0dd41db19bc0cf79c
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-07dcad2e028cc44c9
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0d534b76b00352b50
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-030cfb51a08050cad
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0cbade6e9fd947c09
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-0f1da3b0bb18ed1be
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-07bd3113fa895305a
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0fc0d6e8d70ab2d42
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-094e02db75d74beed
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0d1c4f45c2b23d0a6
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-06af99ca40d168b3b
      ss-id-suffix: base
rhel9:
  x86-64:
    default-description: RHEL9 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: RHEL9 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-06b08b819edcd2cf0
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-04f9ce8b34396d6aa
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-0b7d0687fe794017c
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0a314bace0ee4b705
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-017e8c7959fcd7be7
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0bb048de29870137f
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-02e238bfe416b969b
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0f00b977f6dbfeaa2
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0e25faa3aa9e314b5
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0e5aed7a95371965c
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-05f0e1fe543949a8f
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-01bb730964179dfdf
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-01c46c4df3f52dbde
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0a004d51dd2cb6939
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0a6342a0f6065ecb3
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0143909e59dd265d8
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-048d21bb0d69b31b3
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-0e6a0a7b2a2865698
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-031486069c5cdd00e
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0889361165cd6f1d1
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-0ac54f3d7969bc55b
      ss-id-suffix: base
    us-gov-east-1:
    - ami-id: ami-0927a1f2f154ff3d6
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0f7f3776d57ecbc20
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0c944ab49a7721a6b
      ss-id-suffix: base
rocky9:
  x86-64:
    default-description: Rocky9 - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: Rocky9 - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0bdd4b6c4c6feca84
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-06b18c6a9a323f75f
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-02da14a96759f4bdf
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-08e313580b7dba0a6
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0058131e22d7c740c
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0e3d660a2b0748434
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-08187f3dae26981ad
      ss-id-suffix: base
    ap-southeast-5:
    - ami-id: ami-0303c2ab5865f0efa
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0dc728f2209249218
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0974816532424c446
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-08a91dd538f707083
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-09157a1cc0d8d7bd8
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-09f73ba1beba9ad07
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-05a5686f0de7aa5d5
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-05e6a5fbf52bcf86a
      ss-id-suffix: base
    il-central-1:
    - ami-id: ami-0c38a49699e54e53a
      ss-id-suffix: base
    me-central-1:
    - ami-id: ami-03102da6cb6cc7c39
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-01d0e68ff218b8ad8
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0f2425d4cce4e97dd
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0e529d862bbe9899c
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0112e62b61894b311
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0adebe3adcec1fa34
      ss-id-suffix: base
windows:
  x86-64:
    default-description: Windows - x86_64
    default-min-ram-unit: gb
    default-min-ram-value: 4
    default-min-storage-unit: gb
    default-min-storage-value: 50
    default-tenancy: default
    default-name: Windows - x86_64
    default-allowed-instance-types:
    - t3
    - m6a
    ap-northeast-1:
    - ami-id: ami-0c368c58e2020eca2
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-05f28d8de96249faf
      ss-id-suffix: base
    ap-northeast-3:
    - ami-id: ami-04956bfcb4ab0dd00
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-05f035b6ae19778b1
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-033712975633946ce
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-003d3c2ade4ab43bb
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0c16e3cbd60ee79c1
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0d3d8e3989cb4a7da
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0f7cfea37bb21e8f4
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-03a957f4788bf477e
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0f625b90f35024136
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0d878dff49c3b7945
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-03b8a5ce341fcd73a
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-06036d0f74c7b1614
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0909cee4864578472
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-00b5771a0180e1763
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-051eb131c7bfa3ecb
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0fb8e4006e2af065e
      ss-id-suffix: base
