# Begin: OpenLDAP Settings (openldap)

public: false
instance_type: {{instance_type}}
base_os: {{base_os}}
instance_ami: {{instance_ami}}
volume_size: {{volume_size}}
hostname: "openldap.{{cluster_name}}.{{aws_region}}.local"
ldap_connection_uri: "ldap://openldap.{{cluster_name}}.{{aws_region}}.local"
cloudwatch_logs:
  enabled: true
ec2:
  # enable detailed monitoring for openldap ec2 instance, disabled by default
  enable_detailed_monitoring: false
  # enable termination protection for openldap ec2 instance, enabled by default
  enable_termination_protection: true
  # instance metadata access method
  metadata_http_tokens: "required"  # supported values are "required" for IMDSv2 or "optional" for IMDSv1

# NOTE: OU configurations will not be supported for OpenLDAP server.
  # refer to source/idea-bootstrap/openldap-server/_templates/install_openldap.jinja2 to customize the OUs based on your requirements.

# End: OpenLDAP Settings (openldap)

