app_package_uri: s3://{{ staging_bucket_name }}/releases/{{ version }}/idea-virtual-desktop-{{ version }}.tar.gz

logging:
  profile: production
  default_log_file_name: application.log

cloudwatch_logs:
  enabled: true
