efs:
  {%- if kwargs.use_existing_fs %}
  use_existing_fs: true
  file_system_id: "{{ kwargs.file_system_id }}" # if an existing file system id is provided, provisioning of EFS will be skipped and above parameters will be applied as is. existing file system is supported only when using existing vpc.
  {%- else %}
  kms_key_id: {{ kwargs.kms_key_id or '~' }} # Specify your own CMK to encrypt EFS file system. If set to ~ encryption will be managed by the default AWS key
  throughput_mode: "bursting" # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-throughputmode
  performance_mode: "generalPurpose" # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-performancemode
  encrypted: true # Select whether you want to encrypt the file system or not.
  removal_policy: "DESTROY" # RETAIN will preserve the EFS even if you delete the stack.
  cloudwatch_monitoring: {{ ( kwargs.efs.cloudwatch_monitoring or False ) | lower }}
  transition_to_ia: {{ kwargs.efs.transition_to_ia or '~' }}
  {%- endif %}
