#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
#  and limitations under the License.

ACCOUNTS_CREATE_USER = 'ACCOUNTS_CREATE_USER'
ACCOUNTS_GET_USER = 'ACCOUNTS_GET_USER'
ACCOUNTS_GET_USER_GROUP = 'ACCOUNTS_GET_USER_GROUP'
ACCOUNTS_LIST_USERS = 'ACCOUNTS_LIST_USERS'
ACCOUNTS_DISABLE_USER = 'ACCOUNTS_DISABLE_USER'
ACCOUNTS_ENABLE_USER = 'ACCOUNTS_ENABLE_USER'
AUTH_INITIATE_AUTH = 'AUTH_INITIATE_AUTH'
AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN'
AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD'
PROJECTS_CREATE_PROJECT = 'PROJECTS_CREATE_PROJECT'
PROJECTS_GET_PROJECT = 'PROJECTS_GET_PROJECT'
PROJECTS_UPDATE_PROJECT = 'PROJECTS_UPDATE_PROJECT'
PROJECTS_LIST_PROJECTS = 'PROJECTS_LIST_PROJECTS'
PROJECTS_DISABLE_PROJECT = 'PROJECTS_DISABLE_PROJECT'
PROJECTS_DELETE_PROJECT = 'PROJECTS_DELETE_PROJECT'
CLUSTER_SETTINGS_UPDATE_MODULE_SETTINGS = 'CLUSTER_SETTINGS_UPDATE_MODULE_SETTINGS'

SCHEDULER_ADMIN_QUEUE_PROFILES = 'SCHEDULER_ADMIN_QUEUE_PROFILES'
SCHEDULER_JOB_TEST_CASES = 'SCHEDULER_JOB_TEST_CASES'

# VDC Admin
VIRTUAL_DESKTOP_TEST_ADMIN_BATCH_SESSION_WORKFLOW = 'VIRTUAL_DESKTOP_TEST_ADMIN_BATCH_SESSION_WORKFLOW'
VIRTUAL_DESKTOP_TEST_ADMIN_GET_SESSION_SCREENSHOT = 'VIRTUAL_DESKTOP_TEST_ADMIN_GET_SESSION_SCREENSHOT'
VIRTUAL_DESKTOP_TEST_ADMIN_UPDATE_SESSION = 'VIRTUAL_DESKTOP_TEST_ADMIN_UPDATE_SESSION'
VIRTUAL_DESKTOP_TEST_ADMIN_GET_SESSION_INFO = 'VIRTUAL_DESKTOP_TEST_ADMIN_GET_SESSION_INFO'
VIRTUAL_DESKTOP_TEST_ADMIN_LIST_SESSIONS = 'VIRTUAL_DESKTOP_TEST_ADMIN_LIST_SESSIONS'
VIRTUAL_DESKTOP_TEST_ADMIN_GET_SESSION_CONNECTION_INFO = 'VIRTUAL_DESKTOP_TEST_ADMIN_GET_SESSION_CONNECTION_INFO'
VIRTUAL_DESKTOP_TEST_ADMIN_DELETE_SESSIONS = 'VIRTUAL_DESKTOP_TEST_ADMIN_DELETE_SESSIONS'


# VDC User
VIRTUAL_DESKTOP_TEST_USER_GET_SESSION_SCREENSHOT = 'VIRTUAL_DESKTOP_TEST_USER_GET_SESSION_SCREENSHOT'
VIRTUAL_DESKTOP_TEST_USER_UPDATE_SESSION = 'VIRTUAL_DESKTOP_TEST_USER_UPDATE_SESSION'
VIRTUAL_DESKTOP_TEST_USER_GET_SESSION_CONNECTION_INFO = 'VIRTUAL_DESKTOP_TEST_USER_GET_SESSION_CONNECTION_INFO'
VIRTUAL_DESKTOP_TEST_USER_GET_SESSION_INFO = 'VIRTUAL_DESKTOP_TEST_USER_GET_SESSION_INFO'
VIRTUAL_DESKTOP_TEST_USER_SESSION_WORKFLOW = 'VIRTUAL_DESKTOP_TEST_USER_SESSION_WORKFLOW'
VIRTUAL_DESKTOP_TEST_USER_LIST_SESSIONS = 'VIRTUAL_DESKTOP_TEST_USER_LIST_SESSIONS'
